package main

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
)

func emit(specification *apiSpec) (map[string][]byte, error) {
	header, err := emitHeader(specification)
	if err != nil {
		return nil, err
	}
	source, err := emitSource(specification)
	if err != nil {
		return nil, err
	}
	base := "h2_" + specification.Package + "_api"
	return map[string][]byte{base + ".h": header, base + ".c": source}, nil
}

func emitHeader(specification *apiSpec) ([]byte, error) {
	var output bytes.Buffer
	prefix := "h2_" + specification.Package
	guard := cMacro(prefix + "_api_h")
	fmt.Fprintf(&output, "// Generated by //tools/openapi_codegen. DO NOT EDIT.\n")
	fmt.Fprintf(&output, "#ifndef %s\n#define %s\n\n", guard, guard)
	output.WriteString("#include \"h2/pal/application/h2_pal_http.h\"\n#include \"h2/pal/os/h2_pal_json.h\"\n#include \"h2/pal/os/h2_pal_mem.h\"\n\n")
	output.WriteString("#include <stdbool.h>\n#include <stddef.h>\n#include <stdint.h>\n\n")
	output.WriteString("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n")
	fmt.Fprintf(&output, "typedef enum %s_result {\n", prefix)
	fmt.Fprintf(&output, "    %s_OK = 0,\n", cMacro(prefix))
	fmt.Fprintf(&output, "    %s_ERR_INVALID_ARG = -1,\n", cMacro(prefix))
	fmt.Fprintf(&output, "    %s_ERR_NO_MEMORY = -2,\n", cMacro(prefix))
	fmt.Fprintf(&output, "    %s_ERR_NO_SPACE = -3,\n", cMacro(prefix))
	fmt.Fprintf(&output, "    %s_ERR_HTTP = -4,\n", cMacro(prefix))
	fmt.Fprintf(&output, "    %s_ERR_HTTP_STATUS = -5,\n", cMacro(prefix))
	fmt.Fprintf(&output, "    %s_ERR_UNEXPECTED_STATUS = -6,\n", cMacro(prefix))
	fmt.Fprintf(&output, "    %s_ERR_JSON = -7,\n", cMacro(prefix))
	fmt.Fprintf(&output, "    %s_ERR_UNSUPPORTED = -8\n", cMacro(prefix))
	fmt.Fprintf(&output, "} %s_result_t;\n\n", prefix)
	fmt.Fprintf(&output, "#define %s_MAX_URL_BYTES ((size_t)64u * 1024u)\n", cMacro(prefix))
	fmt.Fprintf(&output, "#define %s_MAX_RESPONSE_BYTES H2_PAL_JSON_DEFAULT_MAX_DOCUMENT_BYTES\n\n", cMacro(prefix))
	fmt.Fprintf(&output, "#define %s_OPERATION_COUNT %du\n\n", cMacro(prefix), len(specification.Operations))
	fmt.Fprintf(&output, "/** UTF-8 byte view: borrowed in requests; response views are owned by their response. */\ntypedef struct %s_string {\n    const char *data;\n    size_t len;\n} %s_string_t;\n\n", prefix, prefix)
	fmt.Fprintf(&output, "/** Opaque JSON value encoded as one complete UTF-8 JSON document. */\ntypedef %s_string_t %s_json_t;\n\n", prefix, prefix)
	fmt.Fprintf(&output, "/** Borrowed binary byte view used by multipart request fields. */\ntypedef struct %s_bytes {\n    const uint8_t *data;\n    size_t len;\n} %s_bytes_t;\n\n", prefix, prefix)
	for _, model := range specification.Models {
		fmt.Fprintf(&output, "typedef struct %s_%s %s_%s_t;\n", prefix, model.Name, prefix, model.Name)
	}
	output.WriteByte('\n')
	for _, model := range specification.Models {
		for _, field := range model.Fields {
			for index, enumeration := range field.Type.Enum {
				fmt.Fprintf(&output, "#define %s_%s_%s_%d \"%s\"\n", cMacro(prefix), cMacro(model.Name), cMacro(field.CName), index, escapeCString(enumeration))
			}
		}
	}
	output.WriteByte('\n')
	for _, model := range specification.Models {
		if len(model.Variants) != 0 {
			fmt.Fprintf(&output, "typedef enum %s_%s_kind {\n", prefix, model.Name)
			fmt.Fprintf(&output, "    %s_%s_NONE = 0,\n", cMacro(prefix), cMacro(model.Name))
			for index, variant := range model.Variants {
				fmt.Fprintf(&output, "    %s_%s_%s = %d,\n", cMacro(prefix), cMacro(model.Name), cMacro(variant.CName), index+1)
			}
			fmt.Fprintf(&output, "} %s_%s_kind_t;\n\n", prefix, model.Name)
		}
		fmt.Fprintf(&output, "struct %s_%s {\n", prefix, model.Name)
		if model.Alias != nil {
			if model.Alias.Nullable {
				output.WriteString("    bool is_null;\n")
			}
			emitStructMember(&output, prefix, *model.Alias, "value", "    ")
		} else if len(model.Variants) != 0 {
			fmt.Fprintf(&output, "    %s_%s_kind_t kind;\n    union {\n", prefix, model.Name)
			for _, variant := range model.Variants {
				fmt.Fprintf(&output, "        %s %s;\n", cType(prefix, variant.Type), variant.CName)
			}
			output.WriteString("    } value;\n")
		} else if len(model.Fields) == 0 {
			output.WriteString("    uint8_t reserved;\n")
		}
		for _, field := range model.Fields {
			if !field.Required {
				fmt.Fprintf(&output, "    bool %s;\n", field.PresenceName)
			}
			if field.Type.Nullable {
				fmt.Fprintf(&output, "    bool %s;\n", field.NullName)
			}
			emitStructMember(&output, prefix, field.Type, field.CName, "    ")
		}
		output.WriteString("};\n\n")
	}
	fmt.Fprintf(&output, "/**\n * Synchronously edit request headers before encoding and transport.\n *\n * Entries below `*in_out_count` are initialized; remaining entries through\n * `capacity` are zeroed and available for additions. The callback must leave\n * `*in_out_count <= capacity`. Any name/value spans it supplies are borrowed\n * by the operation and must remain valid until that synchronous call returns.\n */\ntypedef %s_result_t (*%s_header_callback_t)(\n    void *user,\n    h2_pal_http_header_t *headers,\n    size_t capacity,\n    size_t *in_out_count);\n\n", prefix, prefix)
	fmt.Fprintf(&output, "/** Borrowed configuration. All pointed-to capabilities and strings must outlive calls. */\ntypedef struct %s_client_config {\n", prefix)
	output.WriteString("    const h2_pal_http_api_t *http;\n    const h2_pal_json_api_t *json;\n    const h2_pal_mem_api_t *mem;\n")
	output.WriteString("    const char *base_url;\n    size_t max_url_bytes;\n    int timeout_ms;\n    size_t max_response_bytes;\n")
	output.WriteString("    size_t max_request_bytes;\n    size_t max_string_bytes;\n    size_t max_array_items;\n")
	fmt.Fprintf(&output, "    %s_string_t bearer_token;\n", prefix)
	fmt.Fprintf(&output, "    %s_header_callback_t header_callback;\n", prefix)
	output.WriteString("    void *header_user;\n    size_t max_extra_headers;\n")
	fmt.Fprintf(&output, "} %s_client_config_t;\n\n", prefix)
	fmt.Fprintf(&output, "typedef struct %s_client {\n    %s_client_config_t config;\n} %s_client_t;\n\n", prefix, prefix, prefix)
	fmt.Fprintf(&output, "/** Initialize a client by borrowing all PAL capabilities and configuration strings. */\n%s_result_t %s_client_init(%s_client_t *client, const %s_client_config_t *config);\n\n", prefix, prefix, prefix, prefix)

	for _, operation := range specification.Operations {
		fmt.Fprintf(&output, "typedef struct %s_%s_request {\n", prefix, operation.Name)
		if len(operation.Parameters) == 0 && operation.RequestModel == "" {
			output.WriteString("    uint8_t reserved;\n")
		}
		for _, parameter := range operation.Parameters {
			if !parameter.Required {
				fmt.Fprintf(&output, "    bool %s;\n", parameter.PresenceName)
			}
			if parameter.Type.Nullable {
				fmt.Fprintf(&output, "    bool %s;\n", parameter.NullName)
			}
			emitStructMember(&output, prefix, parameter.Type, parameter.CName, "    ")
		}
		if operation.RequestModel != "" {
			if !operation.RequestRequired {
				output.WriteString("    bool has_body;\n")
			}
			fmt.Fprintf(&output, "    const %s_%s_t *body;\n", prefix, operation.RequestModel)
		}
		output.WriteString("} ")
		fmt.Fprintf(&output, "%s_%s_request_t;\n\n", prefix, operation.Name)
		fmt.Fprintf(&output, "/** Unique-owned response. Zero-initialize before first use; do not copy while live. */\ntypedef struct %s_%s_response {\n    int status_code;\n    const h2_pal_mem_api_t *mem;\n", prefix, operation.Name)
		if operationHasResponseModel(operation) {
			output.WriteString("    bool has_body;\n    union {\n")
			for _, response := range operation.Responses {
				if response.Model != "" {
					fmt.Fprintf(&output, "        %s_%s_t status_%d;\n", prefix, response.Model, response.Status)
				}
			}
			output.WriteString("    } body;\n")
		}
		for _, header := range operationResponseHeaders(operation) {
			fmt.Fprintf(&output, "    bool has_%s;\n", header.CName)
			emitStructMember(&output, prefix, header.Type, header.CName, "    ")
		}
		fmt.Fprintf(&output, "} %s_%s_response_t;\n\n", prefix, operation.Name)
		fmt.Fprintf(&output, "/** Execute synchronously. Request data is borrowed; any previous response value is released before reuse. */\n%s_result_t %s_%s(\n    %s_client_t *client,\n    const %s_%s_request_t *request,\n    %s_%s_response_t *response);\n", prefix, prefix, operation.Name, prefix, prefix, operation.Name, prefix, operation.Name)
		fmt.Fprintf(&output, "/** Release all response-owned memory. Safe on a zeroed response. */\nvoid %s_%s_response_deinit(%s_%s_response_t *response);\n\n", prefix, operation.Name, prefix, operation.Name)
	}
	output.WriteString("#ifdef __cplusplus\n}\n#endif\n\n")
	fmt.Fprintf(&output, "#endif  // %s\n", guard)
	return finalizeOutput(output.Bytes()), nil
}

func emitSource(specification *apiSpec) ([]byte, error) {
	var output bytes.Buffer
	prefix := "h2_" + specification.Package
	macro := cMacro(prefix)
	fmt.Fprintf(&output, "// Generated by //tools/openapi_codegen. DO NOT EDIT.\n#include \"%s_api.h\"\n\n", prefix)
	output.WriteString("#include <float.h>\n#include <math.h>\n#include <stdio.h>\n#include <string.h>\n\n")
	fmt.Fprintf(&output, "static %s_result_t %s_from_pal(h2_pal_result_t result) {\n", prefix, prefix)
	fmt.Fprintf(&output, "    if (result == H2_PAL_OK) return %s_OK;\n", macro)
	fmt.Fprintf(&output, "    if (result == H2_PAL_ERR_NO_MEMORY) return %s_ERR_NO_MEMORY;\n", macro)
	fmt.Fprintf(&output, "    if (result == H2_PAL_ERR_NO_SPACE) return %s_ERR_NO_SPACE;\n", macro)
	fmt.Fprintf(&output, "    if (result == H2_PAL_ERR_UNSUPPORTED) return %s_ERR_UNSUPPORTED;\n", macro)
	fmt.Fprintf(&output, "    return %s_ERR_JSON;\n}\n\n", macro)
	fmt.Fprintf(&output, "static %s_result_t %s_from_http(int result) {\n", prefix, prefix)
	fmt.Fprintf(&output, "    if (result == H2_PAL_OK) return %s_OK;\n", macro)
	fmt.Fprintf(&output, "    if (result == H2_PAL_ERR_NO_MEMORY) return %s_ERR_NO_MEMORY;\n", macro)
	fmt.Fprintf(&output, "    if (result == H2_PAL_ERR_NO_SPACE) return %s_ERR_NO_SPACE;\n", macro)
	fmt.Fprintf(&output, "    if (result == H2_PAL_ERR_UNSUPPORTED) return %s_ERR_UNSUPPORTED;\n", macro)
	fmt.Fprintf(&output, "    return %s_ERR_HTTP;\n}\n\n", macro)
	fmt.Fprintf(&output, "static bool %s_utf8_valid(const char *data, size_t len) {\n", prefix)
	output.WriteString("    size_t i = 0u;\n    while (i < len) {\n        const unsigned char first = (unsigned char)data[i++];\n        if (first == 0u) return false;\n        if (first < 0x80u) continue;\n        size_t remaining = 0u;\n        unsigned int codepoint = 0u;\n        unsigned int minimum = 0u;\n        if (first >= 0xC2u && first <= 0xDFu) { remaining = 1u; codepoint = first & 0x1Fu; minimum = 0x80u; }\n        else if (first >= 0xE0u && first <= 0xEFu) { remaining = 2u; codepoint = first & 0x0Fu; minimum = 0x800u; }\n        else if (first >= 0xF0u && first <= 0xF4u) { remaining = 3u; codepoint = first & 0x07u; minimum = 0x10000u; }\n        else return false;\n        if (remaining > len - i) return false;\n        while (remaining-- != 0u) {\n            const unsigned char next = (unsigned char)data[i++];\n            if ((next & 0xC0u) != 0x80u) return false;\n            codepoint = (codepoint << 6) | (next & 0x3Fu);\n        }\n        if (codepoint < minimum || codepoint > 0x10FFFFu || (codepoint >= 0xD800u && codepoint <= 0xDFFFu)) return false;\n    }\n    return true;\n}\n\n")
	fmt.Fprintf(&output, "static bool %s_string_valid(%s_string_t value, size_t minimum, size_t maximum) {\n    return value.len >= minimum && value.len <= maximum && (value.data != NULL || value.len == 0u) && %s_utf8_valid(value.data, value.len);\n}\n\n", prefix, prefix, prefix)
	fmt.Fprintf(&output, "static bool %s_header_value_valid(%s_string_t value, size_t minimum, size_t maximum) {\n    if (!%s_string_valid(value, minimum, maximum)) return false;\n    for (size_t i = 0u; i < value.len; ++i) if (value.data[i] == '\\r' || value.data[i] == '\\n') return false;\n    return true;\n}\n\n", prefix, prefix, prefix)
	fmt.Fprintf(&output, "static bool %s_http_header_valid(const h2_pal_http_header_t *header) {\n", prefix)
	output.WriteString("    if (header == NULL || header->name.data == NULL || header->name.len == 0u || (header->value.data == NULL && header->value.len != 0u)) return false;\n    for (size_t i = 0u; i < header->name.len; ++i) {\n        const unsigned char value = (unsigned char)header->name.data[i];\n        const bool alphanumeric = (value >= 'a' && value <= 'z') || (value >= 'A' && value <= 'Z') || (value >= '0' && value <= '9');\n        const bool symbol = value == '!' || value == '#' || value == '$' || value == '%' || value == '&' || value == '\\'' || value == '*' || value == '+' || value == '-' || value == '.' || value == '^' || value == '_' || value == '`' || value == '|' || value == '~';\n        if (!alphanumeric && !symbol) return false;\n    }\n    for (size_t i = 0u; i < header->value.len; ++i) {\n        const unsigned char value = (unsigned char)header->value.data[i];\n        if ((value < 0x20u && value != '\\t') || value == 0x7Fu) return false;\n    }\n    return true;\n}\n\n")
	fmt.Fprintf(&output, "static bool %s_header_name_equal(h2_pal_http_str_t value, const char *expected, size_t expected_len) {\n", prefix)
	output.WriteString("    if (value.len != expected_len || (value.data == NULL && value.len != 0u)) return false;\n    for (size_t i = 0u; i < value.len; ++i) { unsigned char left = (unsigned char)value.data[i]; unsigned char right = (unsigned char)expected[i]; if (left >= 'A' && left <= 'Z') left = (unsigned char)(left + ('a' - 'A')); if (right >= 'A' && right <= 'Z') right = (unsigned char)(right + ('a' - 'A')); if (left != right) return false; }\n    return true;\n}\n\n")
	fmt.Fprintf(&output, "static bool %s_config_valid(const %s_client_config_t *config) {\n", prefix, prefix)
	output.WriteString("    if (config == NULL || config->http == NULL || config->http->vtable == NULL || config->http->vtable->request == NULL || config->http->vtable->response_free == NULL || config->json == NULL || config->json->vtable == NULL || config->mem == NULL || config->mem->vtable == NULL || config->mem->vtable->alloc == NULL || config->mem->vtable->realloc == NULL || config->mem->vtable->free == NULL || config->base_url == NULL || config->base_url[0] == '\\0') return false;\n")
	fmt.Fprintf(&output, "    if (config->max_url_bytes == 0u || config->max_url_bytes > %s_MAX_URL_BYTES || config->max_response_bytes == 0u || config->max_response_bytes > %s_MAX_RESPONSE_BYTES) return false;\n", macro, macro)
	output.WriteString("    if (config->max_request_bytes == 0u || config->max_request_bytes == SIZE_MAX || config->max_string_bytes == 0u || config->max_string_bytes == SIZE_MAX || config->max_array_items == 0u) return false;\n")
	output.WriteString("    if ((config->bearer_token.data == NULL && config->bearer_token.len != 0u) || !")
	output.WriteString(prefix)
	output.WriteString("_utf8_valid(config->bearer_token.data, config->bearer_token.len)) return false;\n")
	output.WriteString("    const h2_pal_json_vtable_t *json = config->json->vtable;\n    return json->document_parse != NULL && json->document_create != NULL && json->document_destroy != NULL && json->document_root != NULL && json->document_set_root != NULL && json->value_create_null != NULL && json->value_create_boolean != NULL && json->value_create_number != NULL && json->value_create_string != NULL && json->value_create_array != NULL && json->value_create_object != NULL && json->value_type != NULL && json->value_get_boolean != NULL && json->value_get_number != NULL && json->value_get_string != NULL && json->array_size != NULL && json->array_get != NULL && json->array_append != NULL && json->object_size != NULL && json->object_entry != NULL && json->object_get != NULL && json->object_set != NULL && json->document_serialize != NULL && json->buffer_release != NULL;\n}\n\n")
	fmt.Fprintf(&output, "static %s_result_t %s_copy_string(const h2_pal_mem_api_t *mem, h2_pal_json_string_view_t source, size_t maximum, %s_string_t *output) {\n", prefix, prefix, prefix)
	fmt.Fprintf(&output, "    if (source.len > maximum) return %s_ERR_NO_SPACE;\n", macro)
	output.WriteString("    char *copy = h2_pal_mem_alloc(mem, source.len + 1u);\n")
	fmt.Fprintf(&output, "    if (copy == NULL) return %s_ERR_NO_MEMORY;\n", macro)
	output.WriteString("    if (source.len != 0u) memcpy(copy, source.data, source.len);\n    copy[source.len] = '\\0';\n    output->data = copy;\n    output->len = source.len;\n")
	fmt.Fprintf(&output, "    return %s_OK;\n}\n\n", macro)
	emitBufferHelpers(&output, prefix, macro)
	emitJSONHelpers(&output, prefix, macro)

	for _, model := range specification.Models {
		fmt.Fprintf(&output, "static void %s_%s_deinit(const h2_pal_mem_api_t *mem, %s_%s_t *value);\n", prefix, model.Name, prefix, model.Name)
		fmt.Fprintf(&output, "static %s_result_t %s_%s_encode(const %s_client_t *client, h2_pal_json_document_t *document, const %s_%s_t *value, h2_pal_json_value_t **output);\n", prefix, prefix, model.Name, prefix, prefix, model.Name)
		fmt.Fprintf(&output, "static %s_result_t %s_%s_decode(const %s_client_t *client, const h2_pal_json_value_t *input, %s_%s_t *output);\n", prefix, prefix, model.Name, prefix, prefix, model.Name)
	}
	output.WriteByte('\n')
	for _, model := range specification.Models {
		emitModelDeinit(&output, prefix, model)
		emitModelEncode(&output, prefix, macro, model)
		emitModelDecode(&output, prefix, macro, model)
	}
	fmt.Fprintf(&output, "%s_result_t %s_client_init(%s_client_t *client, const %s_client_config_t *config) {\n", prefix, prefix, prefix, prefix)
	fmt.Fprintf(&output, "    (void)%s_from_pal;\n    (void)%s_from_http;\n    (void)%s_utf8_valid;\n    (void)%s_string_valid;\n    (void)%s_header_value_valid;\n    (void)%s_http_header_valid;\n    (void)%s_header_name_equal;\n    (void)%s_copy_string;\n    (void)%s_buffer_append;\n    (void)%s_bytes_contain;\n    (void)%s_unreserved;\n    (void)%s_buffer_url_encode;\n    (void)%s_json_clone;\n    (void)%s_json_encode;\n    (void)%s_json_decode;\n", prefix, prefix, prefix, prefix, prefix, prefix, prefix, prefix, prefix, prefix, prefix, prefix, prefix, prefix, prefix)
	for _, model := range specification.Models {
		fmt.Fprintf(&output, "    (void)%s_%s_deinit;\n    (void)%s_%s_encode;\n    (void)%s_%s_decode;\n", prefix, model.Name, prefix, model.Name, prefix, model.Name)
	}
	output.WriteString("    if (client == NULL || !")
	output.WriteString(prefix)
	output.WriteString("_config_valid(config)) {")
	fmt.Fprintf(&output, " return %s_ERR_INVALID_ARG; }\n", macro)
	output.WriteString("    client->config = *config;\n")
	fmt.Fprintf(&output, "    return %s_OK;\n}\n\n", macro)
	for _, operation := range specification.Operations {
		emitResponseHeaderHandler(&output, prefix, macro, operation)
		emitResponseDeinit(&output, prefix, operation)
		emitOperation(&output, prefix, macro, operation, findModel(specification.Models, operation.RequestModel))
	}
	return finalizeOutput(output.Bytes()), nil
}

func finalizeOutput(value []byte) []byte {
	return append(bytes.TrimRight(value, "\n"), '\n')
}

func emitBufferHelpers(output *bytes.Buffer, prefix string, macro string) {
	fmt.Fprintf(output, "typedef struct %s_buffer { char *data; size_t len; size_t cap; } %s_buffer_t;\n\n", prefix, prefix)
	fmt.Fprintf(output, "static %s_result_t %s_buffer_append(%s_buffer_t *buffer, const char *data, size_t len) {\n", prefix, prefix, prefix)
	fmt.Fprintf(output, "    if (len > buffer->cap - buffer->len) return %s_ERR_NO_SPACE;\n", macro)
	output.WriteString("    if (len != 0u) memcpy(buffer->data + buffer->len, data, len);\n    buffer->len += len;\n    buffer->data[buffer->len] = '\\0';\n")
	fmt.Fprintf(output, "    return %s_OK;\n}\n\n", macro)
	fmt.Fprintf(output, "static bool %s_bytes_contain(const void *data, size_t data_len, const char *needle, size_t needle_len) {\n", prefix)
	output.WriteString("    if (needle_len == 0u) return true;\n    if (data == NULL || needle == NULL || needle_len > data_len) return false;\n    const uint8_t *bytes = data;\n    for (size_t offset = 0u; offset <= data_len - needle_len; ++offset) if (memcmp(bytes + offset, needle, needle_len) == 0) return true;\n    return false;\n}\n\n")
	fmt.Fprintf(output, "static bool %s_unreserved(unsigned char value) { return (value >= 'a' && value <= 'z') || (value >= 'A' && value <= 'Z') || (value >= '0' && value <= '9') || value == '-' || value == '.' || value == '_' || value == '~'; }\n\n", prefix)
	fmt.Fprintf(output, "static %s_result_t %s_buffer_url_encode(%s_buffer_t *buffer, %s_string_t value) {\n", prefix, prefix, prefix, prefix)
	output.WriteString("    static const char hex[] = \"0123456789ABCDEF\";\n    for (size_t i = 0u; i < value.len; ++i) {\n        unsigned char current = (unsigned char)value.data[i];\n")
	fmt.Fprintf(output, "        if (%s_unreserved(current)) { %s_result_t result = %s_buffer_append(buffer, (const char *)&value.data[i], 1u); if (result != %s_OK) return result; }\n", prefix, prefix, prefix, macro)
	output.WriteString("        else { char encoded[3] = {'%', hex[current >> 4], hex[current & 15u]}; ")
	fmt.Fprintf(output, "%s_result_t result = %s_buffer_append(buffer, encoded, sizeof(encoded)); if (result != %s_OK) return result; }\n", prefix, prefix, macro)
	output.WriteString("    }\n")
	fmt.Fprintf(output, "    return %s_OK;\n}\n\n", macro)
}

func emitJSONHelpers(output *bytes.Buffer, prefix string, macro string) {
	fmt.Fprintf(output, "static %s_result_t %s_json_clone(const %s_client_t *client, h2_pal_json_document_t *document, const h2_pal_json_value_t *source, h2_pal_json_value_t **target) {\n", prefix, prefix, prefix)
	output.WriteString("    h2_pal_json_type_t type = H2_PAL_JSON_TYPE_INVALID;\n")
	fmt.Fprintf(output, "    %s_result_t result = %s_from_pal(h2_pal_json_value_type(client->config.json, source, &type));\n    if (result != %s_OK) return result;\n", prefix, prefix, macro)
	output.WriteString("    switch (type) {\n")
	fmt.Fprintf(output, "    case H2_PAL_JSON_TYPE_NULL: return %s_from_pal(h2_pal_json_value_create_null(client->config.json, document, target));\n", prefix)
	output.WriteString("    case H2_PAL_JSON_TYPE_BOOLEAN: { bool value = false; ")
	fmt.Fprintf(output, "result = %s_from_pal(h2_pal_json_value_get_boolean(client->config.json, source, &value)); if (result != %s_OK) return result; return %s_from_pal(h2_pal_json_value_create_boolean(client->config.json, document, value, target)); }\n", prefix, macro, prefix)
	output.WriteString("    case H2_PAL_JSON_TYPE_NUMBER: { double value = 0.0; ")
	fmt.Fprintf(output, "result = %s_from_pal(h2_pal_json_value_get_number(client->config.json, source, &value)); if (result != %s_OK) return result; return %s_from_pal(h2_pal_json_value_create_number(client->config.json, document, value, target)); }\n", prefix, macro, prefix)
	output.WriteString("    case H2_PAL_JSON_TYPE_STRING: { h2_pal_json_string_view_t value = {0}; ")
	fmt.Fprintf(output, "result = %s_from_pal(h2_pal_json_value_get_string(client->config.json, source, &value)); if (result != %s_OK) return result; return %s_from_pal(h2_pal_json_value_create_string(client->config.json, document, value.data, value.len, target)); }\n", prefix, macro, prefix)
	output.WriteString("    case H2_PAL_JSON_TYPE_ARRAY: { size_t count = 0u; ")
	fmt.Fprintf(output, "result = %[1]s_from_pal(h2_pal_json_array_size(client->config.json, source, &count)); if (result != %[2]s_OK || count > client->config.max_array_items) return result == %[2]s_OK ? %[2]s_ERR_NO_SPACE : result; result = %[1]s_from_pal(h2_pal_json_value_create_array(client->config.json, document, target)); if (result != %[2]s_OK) return result; for (size_t i = 0u; i < count; ++i) { h2_pal_json_value_t *item = NULL; h2_pal_json_value_t *copy = NULL; result = %[1]s_from_pal(h2_pal_json_array_get(client->config.json, source, i, &item)); if (result == %[2]s_OK) result = %[1]s_json_clone(client, document, item, &copy); if (result == %[2]s_OK) result = %[1]s_from_pal(h2_pal_json_array_append(client->config.json, *target, copy)); if (result != %[2]s_OK) return result; } return %[2]s_OK; }\n", prefix, macro)
	output.WriteString("    case H2_PAL_JSON_TYPE_OBJECT: { size_t count = 0u; ")
	fmt.Fprintf(output, "result = %[1]s_from_pal(h2_pal_json_object_size(client->config.json, source, &count)); if (result != %[2]s_OK || count > client->config.max_array_items) return result == %[2]s_OK ? %[2]s_ERR_NO_SPACE : result; result = %[1]s_from_pal(h2_pal_json_value_create_object(client->config.json, document, target)); if (result != %[2]s_OK) return result; for (size_t i = 0u; i < count; ++i) { h2_pal_json_string_view_t key = {0}; h2_pal_json_value_t *item = NULL; h2_pal_json_value_t *copy = NULL; result = %[1]s_from_pal(h2_pal_json_object_entry(client->config.json, source, i, &key, &item)); if (result == %[2]s_OK && key.len > client->config.max_string_bytes) result = %[2]s_ERR_NO_SPACE; if (result == %[2]s_OK) result = %[1]s_json_clone(client, document, item, &copy); if (result == %[2]s_OK) result = %[1]s_from_pal(h2_pal_json_object_set(client->config.json, *target, key.data, key.len, copy)); if (result != %[2]s_OK) return result; } return %[2]s_OK; }\n", prefix, macro)
	fmt.Fprintf(output, "    default: return %s_ERR_JSON;\n    }\n}\n\n", macro)
	fmt.Fprintf(output, "static %s_result_t %s_json_encode(const %s_client_t *client, h2_pal_json_document_t *document, %s_json_t value, h2_pal_json_value_t **target) {\n", prefix, prefix, prefix, prefix)
	fmt.Fprintf(output, "    if (!%s_string_valid(value, 0u, client->config.max_string_bytes)) return %s_ERR_INVALID_ARG;\n", prefix, macro)
	output.WriteString("    h2_pal_json_document_t *source_document = NULL; h2_pal_json_value_t *source_root = NULL; h2_pal_json_type_t source_type = H2_PAL_JSON_TYPE_INVALID;\n")
	fmt.Fprintf(output, "    %s_result_t result = %s_from_pal(h2_pal_json_document_parse(client->config.json, (const uint8_t *)value.data, value.len, NULL, &source_document));\n", prefix, prefix)
	fmt.Fprintf(output, "    if (result == %s_OK) result = %s_from_pal(h2_pal_json_document_root(client->config.json, source_document, &source_root));\n", macro, prefix)
	fmt.Fprintf(output, "    if (result == %s_OK) result = %s_from_pal(h2_pal_json_value_type(client->config.json, source_root, &source_type));\n", macro, prefix)
	fmt.Fprintf(output, "    if (result == %s_OK && source_type != H2_PAL_JSON_TYPE_OBJECT) result = %s_ERR_INVALID_ARG;\n", macro, macro)
	fmt.Fprintf(output, "    if (result == %s_OK) result = %s_json_clone(client, document, source_root, target);\n", macro, prefix)
	output.WriteString("    (void)h2_pal_json_document_destroy(client->config.json, &source_document);\n    return result;\n}\n\n")
	fmt.Fprintf(output, "static %s_result_t %s_json_decode(const %s_client_t *client, const h2_pal_json_value_t *source, %s_json_t *target) {\n", prefix, prefix, prefix, prefix)
	output.WriteString("    h2_pal_json_type_t source_type = H2_PAL_JSON_TYPE_INVALID; h2_pal_json_document_t *document = NULL; h2_pal_json_value_t *copy = NULL; h2_pal_json_buffer_t serialized = {0};\n")
	fmt.Fprintf(output, "    %s_result_t result = %s_from_pal(h2_pal_json_value_type(client->config.json, source, &source_type));\n", prefix, prefix)
	fmt.Fprintf(output, "    if (result == %s_OK && source_type != H2_PAL_JSON_TYPE_OBJECT) result = %s_ERR_JSON;\n", macro, macro)
	fmt.Fprintf(output, "    if (result == %s_OK) result = %s_from_pal(h2_pal_json_document_create(client->config.json, NULL, &document));\n", macro, prefix)
	fmt.Fprintf(output, "    if (result == %s_OK) result = %s_json_clone(client, document, source, &copy);\n", macro, prefix)
	fmt.Fprintf(output, "    if (result == %s_OK) result = %s_from_pal(h2_pal_json_document_set_root(client->config.json, document, copy));\n", macro, prefix)
	fmt.Fprintf(output, "    if (result == %s_OK) result = %s_from_pal(h2_pal_json_document_serialize(client->config.json, document, &serialized));\n", macro, prefix)
	fmt.Fprintf(output, "    if (result == %s_OK) result = %s_copy_string(client->config.mem, (h2_pal_json_string_view_t){(const char *)serialized.data, serialized.len}, client->config.max_string_bytes, target);\n", macro, prefix)
	output.WriteString("    (void)h2_pal_json_buffer_release(client->config.json, &serialized);\n    (void)h2_pal_json_document_destroy(client->config.json, &document);\n    return result;\n}\n\n")
}

func emitModelDeinit(output *bytes.Buffer, prefix string, model modelSpec) {
	fmt.Fprintf(output, "static void %s_%s_deinit(const h2_pal_mem_api_t *mem, %s_%s_t *value) {\n    if (mem == NULL || value == NULL) return;\n", prefix, model.Name, prefix, model.Name)
	if model.Alias != nil {
		emitDeinitType(output, prefix, *model.Alias, "value->value", "    ")
	} else if len(model.Variants) != 0 {
		output.WriteString("    switch (value->kind) {\n")
		for _, variant := range model.Variants {
			fmt.Fprintf(output, "    case %s_%s_%s:\n", cMacro(prefix), cMacro(model.Name), cMacro(variant.CName))
			emitDeinitType(output, prefix, variant.Type, "value->value."+variant.CName, "        ")
			output.WriteString("        break;\n")
		}
		output.WriteString("    default: break;\n    }\n")
	} else {
		for _, field := range model.Fields {
			emitDeinitType(output, prefix, field.Type, "value->"+field.CName, "    ")
		}
	}
	output.WriteString("    memset(value, 0, sizeof(*value));\n}\n\n")
}

func emitDeinitType(output *bytes.Buffer, prefix string, valueType typeSpec, expression string, indent string) {
	switch valueType.Kind {
	case "string", "json":
		fmt.Fprintf(output, "%sh2_pal_mem_free(mem, (void *)%s.data);\n", indent, expression)
	case "model":
		fmt.Fprintf(output, "%sif (%s != NULL) { %s_%s_deinit(mem, %s); h2_pal_mem_free(mem, %s); }\n", indent, expression, prefix, valueType.Model, expression, expression)
	case "array":
		if valueType.Item.Kind == "string" || valueType.Item.Kind == "json" || valueType.Item.Kind == "model" || valueType.Item.Kind == "array" {
			fmt.Fprintf(output, "%sfor (size_t i = 0u; i < %s.count; ++i) {\n", indent, expression)
			emitDeinitType(output, prefix, *valueType.Item, expression+".items[i]", indent+"    ")
			fmt.Fprintf(output, "%s}\n", indent)
		}
		fmt.Fprintf(output, "%sh2_pal_mem_free(mem, %s.items);\n", indent, expression)
	}
}

func emitModelEncode(output *bytes.Buffer, prefix string, macro string, model modelSpec) {
	fmt.Fprintf(output, "static %s_result_t %s_%s_encode(const %s_client_t *client, h2_pal_json_document_t *document, const %s_%s_t *value, h2_pal_json_value_t **output) {\n", prefix, prefix, model.Name, prefix, prefix, model.Name)
	fmt.Fprintf(output, "    if (value == NULL || output == NULL) return %s_ERR_INVALID_ARG;\n", macro)
	if model.Alias != nil {
		if model.Alias.Nullable {
			fmt.Fprintf(output, "    if (value->is_null) return %s_from_pal(h2_pal_json_value_create_null(client->config.json, document, output));\n", prefix)
		}
		fmt.Fprintf(output, "    %s_result_t result = %s_OK;\n", prefix, macro)
		counter := 0
		emitEncodeType(output, prefix, macro, *model.Alias, "value->value", "alias", "    ", &counter)
		output.WriteString("    *output = alias;\n")
		fmt.Fprintf(output, "    return %s_OK;\n}\n\n", macro)
		return
	}
	if len(model.Variants) != 0 {
		fmt.Fprintf(output, "    %s_result_t result = %s_OK;\n", prefix, macro)
		output.WriteString("    switch (value->kind) {\n")
		for index, variant := range model.Variants {
			fmt.Fprintf(output, "    case %s_%s_%s: {\n", cMacro(prefix), cMacro(model.Name), cMacro(variant.CName))
			counter := index
			emitEncodeType(output, prefix, macro, variant.Type, "value->value."+variant.CName, "variant", "        ", &counter)
			output.WriteString("        *output = variant;\n")
			fmt.Fprintf(output, "        return %s_OK;\n    }\n", macro)
		}
		fmt.Fprintf(output, "    default: return %s_ERR_INVALID_ARG;\n    }\n}\n\n", macro)
		return
	}
	output.WriteString("    h2_pal_json_value_t *object = NULL;\n")
	fmt.Fprintf(output, "    %s_result_t result = %s_from_pal(h2_pal_json_value_create_object(client->config.json, document, &object));\n    if (result != %s_OK) return result;\n", prefix, prefix, macro)
	counter := 0
	for _, field := range model.Fields {
		if field.ReadOnly {
			continue
		}
		condition := "true"
		if !field.Required {
			condition = "value->" + field.PresenceName
		}
		fmt.Fprintf(output, "    if (%s) {\n", condition)
		name := fmt.Sprintf("field_%d", counter)
		counter++
		if field.Type.Nullable {
			fmt.Fprintf(output, "        h2_pal_json_value_t *%s = NULL;\n", name)
			fmt.Fprintf(output, "        if (value->%s) { result = %s_from_pal(h2_pal_json_value_create_null(client->config.json, document, &%s)); } else {\n", field.NullName, prefix, name)
			emitEncodeType(output, prefix, macro, field.Type, "value->"+field.CName, name+"_value", "            ", &counter)
			fmt.Fprintf(output, "            %s = %s_value;\n        }\n", name, name)
			fmt.Fprintf(output, "        if (result != %s_OK) return result;\n", macro)
		} else {
			emitEncodeType(output, prefix, macro, field.Type, "value->"+field.CName, name, "        ", &counter)
		}
		fmt.Fprintf(output, "        result = %s_from_pal(h2_pal_json_object_set(client->config.json, object, \"%s\", %d, %s));\n", prefix, escapeCString(field.JSONName), len(field.JSONName), name)
		fmt.Fprintf(output, "        if (result != %s_OK) return result;\n    }\n", macro)
	}
	output.WriteString("    *output = object;\n")
	fmt.Fprintf(output, "    return %s_OK;\n}\n\n", macro)
}

func emitEncodeType(output *bytes.Buffer, prefix string, macro string, valueType typeSpec, expression string, variable string, indent string, counter *int) {
	fmt.Fprintf(output, "%sh2_pal_json_value_t *%s = NULL;\n", indent, variable)
	switch valueType.Kind {
	case "string":
		fmt.Fprintf(output, "%sif (!%s_string_valid(%s, %d, %s)) return %s_ERR_INVALID_ARG;\n", indent, prefix, expression, valueType.MinLength, maxLengthExpression(valueType), macro)
		emitEnumGuard(output, valueType, expression, indent, macro+"_ERR_INVALID_ARG")
		fmt.Fprintf(output, "%sresult = %s_from_pal(h2_pal_json_value_create_string(client->config.json, document, %s.data, %s.len, &%s));\n", indent, prefix, expression, expression, variable)
	case "json":
		fmt.Fprintf(output, "%sresult = %s_json_encode(client, document, %s, &%s);\n", indent, prefix, expression, variable)
	case "bytes":
		fmt.Fprintf(output, "%s(void)%s; result = %s_ERR_UNSUPPORTED;\n", indent, expression, macro)
	case "bool":
		fmt.Fprintf(output, "%sresult = %s_from_pal(h2_pal_json_value_create_boolean(client->config.json, document, %s, &%s));\n", indent, prefix, expression, variable)
	case "int32", "int64", "float", "double":
		if valueType.Kind == "int64" && valueType.Minimum != nil && valueType.Maximum != nil {
			fmt.Fprintf(output, "%sif (%s < %dLL || %s > %dLL) return %s_ERR_INVALID_ARG;\n", indent, expression, *valueType.Minimum, expression, *valueType.Maximum, macro)
		}
		if valueType.Kind == "float" || valueType.Kind == "double" {
			fmt.Fprintf(output, "%sif (!isfinite((double)%s)) return %s_ERR_INVALID_ARG;\n", indent, expression, macro)
			if valueType.NumberMinimum != nil {
				fmt.Fprintf(output, "%sif ((double)%s < %.17g) return %s_ERR_INVALID_ARG;\n", indent, expression, *valueType.NumberMinimum, macro)
			}
			if valueType.NumberMaximum != nil {
				fmt.Fprintf(output, "%sif ((double)%s > %.17g) return %s_ERR_INVALID_ARG;\n", indent, expression, *valueType.NumberMaximum, macro)
			}
		}
		fmt.Fprintf(output, "%sresult = %s_from_pal(h2_pal_json_value_create_number(client->config.json, document, (double)%s, &%s));\n", indent, prefix, expression, variable)
	case "model":
		fmt.Fprintf(output, "%sif (%s == NULL) return %s_ERR_INVALID_ARG;\n", indent, expression, macro)
		fmt.Fprintf(output, "%sresult = %s_%s_encode(client, document, %s, &%s);\n", indent, prefix, valueType.Model, expression, variable)
	case "array":
		fmt.Fprintf(output, "%sif (", indent)
		if valueType.MinItems != 0 {
			fmt.Fprintf(output, "%s.count < %d || ", expression, valueType.MinItems)
		}
		fmt.Fprintf(output, "%s.count > %s || (%s.items == NULL && %s.count != 0u)) return %s_ERR_INVALID_ARG;\n", expression, maxItemsExpression(valueType), expression, expression, macro)
		fmt.Fprintf(output, "%sresult = %s_from_pal(h2_pal_json_value_create_array(client->config.json, document, &%s));\n", indent, prefix, variable)
		fmt.Fprintf(output, "%sif (result != %s_OK) return result;\n", indent, macro)
		fmt.Fprintf(output, "%sfor (size_t i = 0u; i < %s.count; ++i) {\n", indent, expression)
		child := fmt.Sprintf("item_%d", *counter)
		*counter++
		emitEncodeType(output, prefix, macro, *valueType.Item, expression+".items[i]", child, indent+"    ", counter)
		fmt.Fprintf(output, "%s    result = %s_from_pal(h2_pal_json_array_append(client->config.json, %s, %s));\n", indent, prefix, variable, child)
		fmt.Fprintf(output, "%s    if (result != %s_OK) return result;\n%s}\n", indent, macro, indent)
	}
	fmt.Fprintf(output, "%sif (result != %s_OK) return result;\n", indent, macro)
}

func emitEnumGuard(output *bytes.Buffer, valueType typeSpec, expression string, indent string, errorConstant string) {
	if len(valueType.Enum) == 0 {
		return
	}
	output.WriteString(indent + "if (!(")
	for index, value := range valueType.Enum {
		if index != 0 {
			output.WriteString(" || ")
		}
		if len(value) == 0 {
			fmt.Fprintf(output, "%s.len == 0u", expression)
		} else {
			fmt.Fprintf(output, "(%s.len == %d && memcmp(%s.data, \"%s\", %d) == 0)", expression, len(value), expression, escapeCString(value), len(value))
		}
	}
	fmt.Fprintf(output, ")) return %s;\n", errorConstant)
}

func emitModelDecode(output *bytes.Buffer, prefix string, macro string, model modelSpec) {
	fmt.Fprintf(output, "static %s_result_t %s_%s_decode(const %s_client_t *client, const h2_pal_json_value_t *input, %s_%s_t *output) {\n", prefix, prefix, model.Name, prefix, prefix, model.Name)
	fmt.Fprintf(output, "    if (input == NULL || output == NULL) return %s_ERR_INVALID_ARG;\n    memset(output, 0, sizeof(*output));\n", macro)
	output.WriteString("    h2_pal_json_type_t input_type = H2_PAL_JSON_TYPE_INVALID;\n")
	fmt.Fprintf(output, "    %s_result_t result = %s_from_pal(h2_pal_json_value_type(client->config.json, input, &input_type));\n", prefix, prefix)
	if model.Alias != nil {
		if model.Alias.Nullable {
			fmt.Fprintf(output, "    if (result == %s_OK && input_type == H2_PAL_JSON_TYPE_NULL) { output->is_null = true; return %s_OK; }\n", macro, macro)
		}
		counter := 0
		emitDecodeType(output, prefix, macro, *model.Alias, "input", "output->value", "    ", &counter)
		fmt.Fprintf(output, "    return %s_OK;\n}\n\n", macro)
		return
	}
	if len(model.Variants) != 0 {
		fmt.Fprintf(output, "    if (result != %s_OK || input_type != H2_PAL_JSON_TYPE_OBJECT) return %s_ERR_JSON;\n", macro, macro)
		output.WriteString("    size_t matches = 0u;\n")
		for index, variant := range model.Variants {
			fmt.Fprintf(output, "    %s candidate_%d = NULL;\n", cType(prefix, variant.Type), index)
			fmt.Fprintf(output, "    candidate_%d = h2_pal_mem_alloc(client->config.mem, sizeof(*candidate_%d));\n", index, index)
			fmt.Fprintf(output, "    if (candidate_%d == NULL) return %s_ERR_NO_MEMORY;\n", index, macro)
			fmt.Fprintf(output, "    result = %s_%s_decode(client, input, candidate_%d);\n", prefix, variant.Type.Model, index)
			fmt.Fprintf(output, "    if (result == %s_OK) { ++matches; } else { if (candidate_%d != NULL) { %s_%s_deinit(client->config.mem, candidate_%d); h2_pal_mem_free(client->config.mem, candidate_%d); candidate_%d = NULL; }", macro, index, prefix, variant.Type.Model, index, index, index)
			fmt.Fprintf(output, " if (result != %s_ERR_JSON) {\n", macro)
			for previousIndex, previousVariant := range model.Variants[:index] {
				fmt.Fprintf(output, "        if (candidate_%d != NULL) { %s_%s_deinit(client->config.mem, candidate_%d); h2_pal_mem_free(client->config.mem, candidate_%d); }\n", previousIndex, prefix, previousVariant.Type.Model, previousIndex, previousIndex)
			}
			output.WriteString("        return result;\n    }")
			fmt.Fprintf(output, " result = %s_OK; }\n", macro)
		}
		fmt.Fprintf(output, "    if (matches != 1u) {\n")
		for index, variant := range model.Variants {
			fmt.Fprintf(output, "        if (candidate_%d != NULL) { %s_%s_deinit(client->config.mem, candidate_%d); h2_pal_mem_free(client->config.mem, candidate_%d); }\n", index, prefix, variant.Type.Model, index, index)
		}
		fmt.Fprintf(output, "        return %s_ERR_JSON;\n    }\n", macro)
		for index, variant := range model.Variants {
			if index == 0 {
				fmt.Fprintf(output, "    if (candidate_%d != NULL) {", index)
			} else {
				fmt.Fprintf(output, " else if (candidate_%d != NULL) {", index)
			}
			fmt.Fprintf(output, " output->kind = %s_%s_%s; output->value.%s = candidate_%d; }", cMacro(prefix), cMacro(model.Name), cMacro(variant.CName), variant.CName, index)
		}
		fmt.Fprintf(output, "\n    return %s_OK;\n}\n\n", macro)
		return
	}
	fmt.Fprintf(output, "    if (result != %s_OK || input_type != H2_PAL_JSON_TYPE_OBJECT) return %s_ERR_JSON;\n", macro, macro)
	counter := 0
	for _, field := range model.Fields {
		if field.WriteOnly {
			continue
		}
		variable := fmt.Sprintf("field_%d", counter)
		counter++
		fmt.Fprintf(output, "    h2_pal_json_value_t *%s = NULL;\n    h2_pal_result_t %s_lookup = h2_pal_json_object_get(client->config.json, input, \"%s\", %d, &%s);\n", variable, variable, escapeCString(field.JSONName), len(field.JSONName), variable)
		if field.Required {
			fmt.Fprintf(output, "    if (%s_lookup != H2_PAL_OK) return %s_ERR_JSON;\n", variable, macro)
			emitNullableDecode(output, prefix, macro, field, variable, "    ", &counter)
		} else {
			fmt.Fprintf(output, "    if (%s_lookup == H2_PAL_OK) {\n        output->%s = true;\n", variable, field.PresenceName)
			emitNullableDecode(output, prefix, macro, field, variable, "        ", &counter)
			fmt.Fprintf(output, "    } else if (%s_lookup != H2_PAL_ERR_NOT_FOUND) { return %s_ERR_JSON; }\n", variable, macro)
		}
	}
	fmt.Fprintf(output, "    return %s_OK;\n}\n\n", macro)
}

func emitNullableDecode(output *bytes.Buffer, prefix string, macro string, field fieldSpec, input string, indent string, counter *int) {
	if !field.Type.Nullable {
		emitDecodeType(output, prefix, macro, field.Type, input, "output->"+field.CName, indent, counter)
		return
	}
	typeName := fmt.Sprintf("nullable_type_%d", *counter)
	*counter++
	fmt.Fprintf(output, "%sh2_pal_json_type_t %s = H2_PAL_JSON_TYPE_INVALID;\n", indent, typeName)
	fmt.Fprintf(output, "%sresult = %s_from_pal(h2_pal_json_value_type(client->config.json, %s, &%s));\n", indent, prefix, input, typeName)
	fmt.Fprintf(output, "%sif (result != %s_OK) return %s_ERR_JSON;\n", indent, macro, macro)
	fmt.Fprintf(output, "%sif (%s == H2_PAL_JSON_TYPE_NULL) { output->%s = true; } else {\n", indent, typeName, field.NullName)
	emitDecodeType(output, prefix, macro, field.Type, input, "output->"+field.CName, indent+"    ", counter)
	fmt.Fprintf(output, "%s}\n", indent)
}

func emitDecodeType(output *bytes.Buffer, prefix string, macro string, valueType typeSpec, input string, target string, indent string, counter *int) {
	switch valueType.Kind {
	case "string":
		view := fmt.Sprintf("string_%d", *counter)
		*counter++
		fmt.Fprintf(output, "%sh2_pal_json_string_view_t %s = {0};\n", indent, view)
		fmt.Fprintf(output, "%sresult = %s_from_pal(h2_pal_json_value_get_string(client->config.json, %s, &%s));\n", indent, prefix, input, view)
		fmt.Fprintf(output, "%sif (result != %s_OK) return %s_ERR_JSON;\n", indent, macro, macro)
		if valueType.MinLength != 0 {
			fmt.Fprintf(output, "%sif (%s.len < %d) return %s_ERR_JSON;\n", indent, view, valueType.MinLength, macro)
		}
		fmt.Fprintf(output, "%sresult = %s_copy_string(client->config.mem, %s, %s, &%s);\n", indent, prefix, view, maxLengthExpression(valueType), target)
		fmt.Fprintf(output, "%sif (result != %s_OK) return result;\n", indent, macro)
		emitEnumGuard(output, valueType, target, indent, macro+"_ERR_JSON")
	case "json":
		fmt.Fprintf(output, "%sresult = %s_json_decode(client, %s, &%s);\n", indent, prefix, input, target)
		fmt.Fprintf(output, "%sif (result != %s_OK) return result;\n", indent, macro)
	case "bytes":
		fmt.Fprintf(output, "%s(void)%s; (void)%s; return %s_ERR_UNSUPPORTED;\n", indent, input, target, macro)
	case "bool":
		fmt.Fprintf(output, "%sresult = %s_from_pal(h2_pal_json_value_get_boolean(client->config.json, %s, &%s));\n", indent, prefix, input, target)
		fmt.Fprintf(output, "%sif (result != %s_OK) return %s_ERR_JSON;\n", indent, macro, macro)
	case "int32", "int64", "float", "double":
		number := fmt.Sprintf("number_%d", *counter)
		*counter++
		fmt.Fprintf(output, "%sdouble %s = 0.0;\n", indent, number)
		fmt.Fprintf(output, "%sresult = %s_from_pal(h2_pal_json_value_get_number(client->config.json, %s, &%s));\n", indent, prefix, input, number)
		fmt.Fprintf(output, "%sif (result != %s_OK || !isfinite(%s)", indent, macro, number)
		if valueType.Kind == "int32" {
			fmt.Fprintf(output, " || %s < INT32_MIN || %s > INT32_MAX || %s != (double)(int32_t)%s", number, number, number, number)
		} else if valueType.Kind == "int64" {
			fmt.Fprintf(output, " || %s < %.1f || %s > %.1f || %s != (double)(int64_t)%s", number, float64(*valueType.Minimum), number, float64(*valueType.Maximum), number, number)
		} else if valueType.Kind == "float" {
			fmt.Fprintf(output, " || %s < -(double)FLT_MAX || %s > (double)FLT_MAX", number, number)
		}
		if valueType.NumberMinimum != nil {
			fmt.Fprintf(output, " || %s < %.17g", number, *valueType.NumberMinimum)
		}
		if valueType.NumberMaximum != nil {
			fmt.Fprintf(output, " || %s > %.17g", number, *valueType.NumberMaximum)
		}
		fmt.Fprintf(output, ") return %s_ERR_JSON;\n", macro)
		fmt.Fprintf(output, "%s%s = (%s)%s;\n", indent, target, cType(prefix, valueType), number)
	case "model":
		fmt.Fprintf(output, "%s%s = h2_pal_mem_alloc(client->config.mem, sizeof(*%s));\n", indent, target, target)
		fmt.Fprintf(output, "%sif (%s == NULL) return %s_ERR_NO_MEMORY;\n", indent, target, macro)
		fmt.Fprintf(output, "%sresult = %s_%s_decode(client, %s, %s);\n", indent, prefix, valueType.Model, input, target)
		fmt.Fprintf(output, "%sif (result != %s_OK) return result;\n", indent, macro)
	case "array":
		sizeVariable := fmt.Sprintf("count_%d", *counter)
		*counter++
		fmt.Fprintf(output, "%ssize_t %s = 0u;\n", indent, sizeVariable)
		fmt.Fprintf(output, "%sresult = %s_from_pal(h2_pal_json_array_size(client->config.json, %s, &%s));\n", indent, prefix, input, sizeVariable)
		fmt.Fprintf(output, "%sif (result != %s_OK", indent, macro)
		if valueType.MinItems != 0 {
			fmt.Fprintf(output, " || %s < %d", sizeVariable, valueType.MinItems)
		}
		fmt.Fprintf(output, " || %s > %s) return %s_ERR_JSON;\n", sizeVariable, maxItemsExpression(valueType), macro)
		fmt.Fprintf(output, "%sif (%s != 0u) {\n", indent, sizeVariable)
		fmt.Fprintf(output, "%s    if (%s > SIZE_MAX / sizeof(*%s.items)) return %s_ERR_NO_SPACE;\n", indent, sizeVariable, target, macro)
		fmt.Fprintf(output, "%s    %s.items = h2_pal_mem_alloc(client->config.mem, sizeof(*%s.items) * %s);\n", indent, target, target, sizeVariable)
		fmt.Fprintf(output, "%s    if (%s.items == NULL) return %s_ERR_NO_MEMORY;\n", indent, target, macro)
		fmt.Fprintf(output, "%s    memset(%s.items, 0, sizeof(*%s.items) * %s);\n%s}\n", indent, target, target, sizeVariable, indent)
		fmt.Fprintf(output, "%s%s.count = %s;\n", indent, target, sizeVariable)
		fmt.Fprintf(output, "%sfor (size_t i = 0u; i < %s; ++i) {\n", indent, sizeVariable)
		itemVariable := fmt.Sprintf("item_%d", *counter)
		*counter++
		fmt.Fprintf(output, "%s    h2_pal_json_value_t *%s = NULL;\n", indent, itemVariable)
		fmt.Fprintf(output, "%s    result = %s_from_pal(h2_pal_json_array_get(client->config.json, %s, i, &%s));\n", indent, prefix, input, itemVariable)
		fmt.Fprintf(output, "%s    if (result != %s_OK) return %s_ERR_JSON;\n", indent, macro, macro)
		emitDecodeType(output, prefix, macro, *valueType.Item, itemVariable, target+".items[i]", indent+"    ", counter)
		fmt.Fprintf(output, "%s}\n", indent)
	}
}

func emitResponseDeinit(output *bytes.Buffer, prefix string, operation operation) {
	fmt.Fprintf(output, "void %s_%s_response_deinit(%s_%s_response_t *response) {\n    if (response == NULL) return;\n", prefix, operation.Name, prefix, operation.Name)
	headers := operationResponseHeaders(operation)
	mem := "response->mem"
	if len(headers) != 0 {
		output.WriteString("    const h2_pal_mem_api_t *mem = response->mem;\n")
		mem = "mem"
	}
	if operationHasResponseModel(operation) {
		fmt.Fprintf(output, "    if (%s != NULL && response->has_body) {\n        switch (response->status_code) {\n", mem)
		for _, response := range operation.Responses {
			if response.Model != "" {
				fmt.Fprintf(output, "        case %d: %s_%s_deinit(%s, &response->body.status_%d); break;\n", response.Status, prefix, response.Model, mem, response.Status)
			}
		}
		output.WriteString("        default: break;\n        }\n    }\n")
	}
	for _, header := range headers {
		fmt.Fprintf(output, "    if (mem != NULL && response->has_%s) {\n", header.CName)
		emitDeinitType(output, prefix, header.Type, "response->"+header.CName, "        ")
		output.WriteString("    }\n")
	}
	output.WriteString("    memset(response, 0, sizeof(*response));\n}\n\n")
}

func emitResponseHeaderHandler(output *bytes.Buffer, prefix string, macro string, operation operation) {
	headers := operationResponseHeaders(operation)
	if len(headers) == 0 {
		return
	}
	fmt.Fprintf(output, "typedef struct %s_%s_response_header_context { const %s_client_t *client; %s_%s_response_t *response; } %s_%s_response_header_context_t;\n", prefix, operation.Name, prefix, prefix, operation.Name, prefix, operation.Name)
	fmt.Fprintf(output, "static int %s_%s_response_header(void *user, const h2_pal_http_request_t *request, h2_pal_http_str_t name, h2_pal_http_str_t value) {\n", prefix, operation.Name)
	output.WriteString("    (void)request;\n")
	fmt.Fprintf(output, "    %s_%s_response_header_context_t *context = user;\n    if (context == NULL || context->client == NULL || context->response == NULL || context->response->mem == NULL) return H2_PAL_ERR_INVALID_ARG;\n    const %s_client_t *client = context->client;\n    %s_%s_response_t *response = context->response;\n", prefix, operation.Name, prefix, prefix, operation.Name)
	output.WriteString("    (void)client;\n")
	for _, header := range headers {
		fmt.Fprintf(output, "    if (%s_header_name_equal(name, \"%s\", %du)) {\n", prefix, escapeCString(header.Name), len(header.Name))
		if header.Type.Kind == "string" {
			fmt.Fprintf(output, "        %s_string_t view = {value.data, value.len};\n", prefix)
			fmt.Fprintf(output, "        if (!%s_string_valid(view, %d, %s)) return H2_PAL_ERR_INVALID_ARG;\n", prefix, header.Type.MinLength, maxLengthExpression(header.Type))
			emitEnumGuard(output, header.Type, "view", "        ", "H2_PAL_ERR_INVALID_ARG")
			output.WriteString("        char *copy = h2_pal_mem_alloc(response->mem, value.len + 1u);\n        if (copy == NULL) return H2_PAL_ERR_NO_MEMORY;\n        if (value.len != 0u) memcpy(copy, value.data, value.len);\n        copy[value.len] = '\\0';\n")
			fmt.Fprintf(output, "        if (response->has_%s) h2_pal_mem_free(response->mem, (void *)response->%s.data);\n", header.CName, header.CName)
			fmt.Fprintf(output, "        response->%s = (%s_string_t){copy, value.len};\n        response->has_%s = true;\n        return H2_PAL_OK;\n", header.CName, prefix, header.CName)
		} else {
			fmt.Fprintf(output, "        return H2_PAL_ERR_UNSUPPORTED; /* %s response header */\n", header.Type.Kind)
		}
		output.WriteString("    }\n")
	}
	output.WriteString("    return H2_PAL_OK;\n}\n\n")
	_ = macro
}

func emitOperation(output *bytes.Buffer, prefix string, macro string, operation operation, requestModel *modelSpec) {
	bodyCondition := "true"
	if !operation.RequestRequired {
		bodyCondition = "request->has_body"
	}
	fmt.Fprintf(output, "%s_result_t %s_%s(%s_client_t *client, const %s_%s_request_t *request, %s_%s_response_t *response) {\n", prefix, prefix, operation.Name, prefix, prefix, operation.Name, prefix, operation.Name)
	fmt.Fprintf(output, "    if (client == NULL || request == NULL || response == NULL || !%s_config_valid(&client->config)) return %s_ERR_INVALID_ARG;\n", prefix, macro)
	fmt.Fprintf(output, "    %s_%s_response_deinit(response);\n", prefix, operation.Name)
	output.WriteString("    response->mem = client->config.mem;\n")
	if operation.RequestMediaType == "multipart/form-data" {
		output.WriteString("    char multipart_boundary[48] = {0};\n    size_t multipart_boundary_len = 0u;\n    char multipart_content_type[80] = {0};\n    size_t multipart_content_type_len = 0u;\n")
	}
	for _, parameter := range operation.Parameters {
		condition := "true"
		if !parameter.Required {
			condition = "request->" + parameter.PresenceName
		}
		if parameter.Type.Nullable {
			condition = "(" + condition + " && !request->" + parameter.NullName + ")"
		}
		if parameter.Type.Kind == "string" {
			validator := prefix + "_string_valid"
			if parameter.Location == "header" {
				validator = prefix + "_header_value_valid"
			}
			fmt.Fprintf(output, "    if (%s && !%s(request->%s, %d, %s)) return %s_ERR_INVALID_ARG;\n", condition, validator, parameter.CName, parameter.Type.MinLength, maxLengthExpression(parameter.Type), macro)
			if parameter.Location == "query" && !parameter.AllowEmpty {
				fmt.Fprintf(output, "    if (%s && request->%s.len == 0u) return %s_ERR_INVALID_ARG;\n", condition, parameter.CName, macro)
			}
			if len(parameter.Type.Enum) != 0 {
				fmt.Fprintf(output, "    if (%s) {\n", condition)
				emitEnumGuard(output, parameter.Type, "request->"+parameter.CName, "        ", macro+"_ERR_INVALID_ARG")
				output.WriteString("    }\n")
			}
		}
		if parameter.Type.Kind == "float" || parameter.Type.Kind == "double" {
			fmt.Fprintf(output, "    if (%s && !isfinite((double)request->%s)) return %s_ERR_INVALID_ARG;\n", condition, parameter.CName, macro)
			if parameter.Type.NumberMinimum != nil {
				fmt.Fprintf(output, "    if (%s && (double)request->%s < %.17g) return %s_ERR_INVALID_ARG;\n", condition, parameter.CName, *parameter.Type.NumberMinimum, macro)
			}
			if parameter.Type.NumberMaximum != nil {
				fmt.Fprintf(output, "    if (%s && (double)request->%s > %.17g) return %s_ERR_INVALID_ARG;\n", condition, parameter.CName, *parameter.Type.NumberMaximum, macro)
			}
		}
		if parameter.Type.Kind == "int64" && parameter.Type.Minimum != nil && parameter.Type.Maximum != nil {
			fmt.Fprintf(output, "    if (%s && (request->%s < %dLL || request->%s > %dLL)) return %s_ERR_INVALID_ARG;\n", condition, parameter.CName, *parameter.Type.Minimum, parameter.CName, *parameter.Type.Maximum, macro)
		}
		if parameter.Type.Kind == "array" {
			fmt.Fprintf(output, "    if (%s && (", condition)
			if parameter.Type.MinItems != 0 {
				fmt.Fprintf(output, "request->%s.count < %du || ", parameter.CName, parameter.Type.MinItems)
			}
			fmt.Fprintf(output, "request->%s.count > %s || (request->%s.items == NULL && request->%s.count != 0u))) return %s_ERR_INVALID_ARG;\n", parameter.CName, maxItemsExpression(parameter.Type), parameter.CName, parameter.CName, macro)
		}
	}
	if operation.RequestModel != "" {
		fmt.Fprintf(output, "    if (%s && request->body == NULL) return %s_ERR_INVALID_ARG;\n", bodyCondition, macro)
	}
	if operation.RequestMediaType == "multipart/form-data" {
		emitMultipartBoundary(output, prefix, macro, requestModel, bodyCondition)
	}
	output.WriteString("    char *url_data = h2_pal_mem_alloc(client->config.mem, client->config.max_url_bytes + 1u);\n")
	fmt.Fprintf(output, "    if (url_data == NULL) return %s_ERR_NO_MEMORY;\n", macro)
	fmt.Fprintf(output, "    %s_buffer_t url = {url_data, 0u, client->config.max_url_bytes};\n", prefix)
	fmt.Fprintf(output, "    %s_result_t result = %s_buffer_append(&url, client->config.base_url, strlen(client->config.base_url));\n", prefix, prefix)
	fmt.Fprintf(output, "    if (result != %s_OK) goto cleanup_url;\n", macro)
	emitPath(output, prefix, macro, operation)
	emitQuery(output, prefix, macro, operation)

	headerBase := 0
	for _, parameter := range operation.Parameters {
		if parameter.Location == "header" {
			headerBase++
		}
	}
	if operation.RequestModel != "" {
		headerBase++
	}
	if operationHasResponseModel(operation) {
		headerBase++
	}
	if operation.BearerSecurity {
		headerBase++
	}
	fmt.Fprintf(output, "    if (client->config.max_extra_headers > SIZE_MAX - %d) { result = %s_ERR_NO_SPACE; goto cleanup_url; }\n", headerBase, macro)
	fmt.Fprintf(output, "    size_t header_capacity = %d + client->config.max_extra_headers;\n", headerBase)
	fmt.Fprintf(output, "    if (header_capacity > SIZE_MAX / sizeof(h2_pal_http_header_t)) { result = %s_ERR_NO_SPACE; goto cleanup_url; }\n", macro)
	output.WriteString("    h2_pal_http_header_t *headers = NULL;\n    if (header_capacity != 0u) headers = h2_pal_mem_alloc(client->config.mem, sizeof(*headers) * header_capacity);\n")
	fmt.Fprintf(output, "    if (header_capacity != 0u && headers == NULL) { result = %s_ERR_NO_MEMORY; goto cleanup_url; }\n", macro)
	output.WriteString("    if (headers != NULL) memset(headers, 0, sizeof(*headers) * header_capacity);\n")
	output.WriteString("    size_t header_count = 0u;\n")
	output.WriteString("    char *authorization = NULL;\n")
	if operation.BearerSecurity {
		fmt.Fprintf(output, "    if (client->config.bearer_token.len == 0u || client->config.bearer_token.len > SIZE_MAX - 8u) { result = %s_ERR_INVALID_ARG; goto cleanup_headers; }\n", macro)
		output.WriteString("    authorization = h2_pal_mem_alloc(client->config.mem, client->config.bearer_token.len + 8u);\n")
		fmt.Fprintf(output, "    if (authorization == NULL) { result = %s_ERR_NO_MEMORY; goto cleanup_headers; }\n", macro)
		output.WriteString("    memcpy(authorization, \"Bearer \", 7u); memcpy(authorization + 7u, client->config.bearer_token.data, client->config.bearer_token.len); authorization[client->config.bearer_token.len + 7u] = '\\0';\n")
		output.WriteString("    headers[header_count++] = (h2_pal_http_header_t){{\"Authorization\", 13u}, {authorization, client->config.bearer_token.len + 7u}};\n")
	}
	for _, parameter := range operation.Parameters {
		if parameter.Location == "header" && parameter.Type.Kind != "string" && parameter.Type.Kind != "bool" {
			fmt.Fprintf(output, "    char header_%s_text[48];\n", parameter.CName)
		}
	}
	for _, parameter := range operation.Parameters {
		if parameter.Location != "header" {
			continue
		}
		condition := "true"
		if !parameter.Required {
			condition = "request->" + parameter.PresenceName
		}
		if parameter.Type.Nullable {
			condition = "(" + condition + " && !request->" + parameter.NullName + ")"
		}
		fmt.Fprintf(output, "    if (%s) {\n", condition)
		if parameter.Type.Kind == "string" {
			fmt.Fprintf(output, "        headers[header_count++] = (h2_pal_http_header_t){{\"%s\", %d}, {request->%s.data, request->%s.len}};\n", escapeCString(parameter.Name), len(parameter.Name), parameter.CName, parameter.CName)
		} else if parameter.Type.Kind == "bool" {
			fmt.Fprintf(output, "        headers[header_count++] = (h2_pal_http_header_t){{\"%s\", %d}, {request->%s ? \"true\" : \"false\", request->%s ? 4u : 5u}};\n", escapeCString(parameter.Name), len(parameter.Name), parameter.CName, parameter.CName)
		} else {
			format := "%ld"
			cast := "(long)"
			if parameter.Type.Kind == "int64" {
				format, cast = "%lld", "(long long)"
			}
			if parameter.Type.Kind == "float" || parameter.Type.Kind == "double" {
				format, cast = "%.17g", "(double)"
			}
			fmt.Fprintf(output, "        int header_len = snprintf(header_%s_text, sizeof(header_%s_text), \"%s\", %srequest->%s);\n", parameter.CName, parameter.CName, format, cast, parameter.CName)
			fmt.Fprintf(output, "        if (header_len < 0 || (size_t)header_len >= sizeof(header_%s_text)) { result = %s_ERR_INVALID_ARG; goto cleanup_headers; }\n", parameter.CName, macro)
			fmt.Fprintf(output, "        headers[header_count++] = (h2_pal_http_header_t){{\"%s\", %d}, {header_%s_text, (size_t)header_len}};\n", escapeCString(parameter.Name), len(parameter.Name), parameter.CName)
		}
		output.WriteString("    }\n")
	}
	if operation.RequestModel != "" {
		if operation.RequestMediaType == "multipart/form-data" {
			fmt.Fprintf(output, "    if (%s) headers[header_count++] = (h2_pal_http_header_t){{\"Content-Type\", 12u}, {multipart_content_type, multipart_content_type_len}};\n", bodyCondition)
		} else {
			fmt.Fprintf(output, "    if (%s) headers[header_count++] = (h2_pal_http_header_t){{\"Content-Type\", 12u}, {\"%s\", %du}};\n", bodyCondition, operation.RequestMediaType, len(operation.RequestMediaType))
		}
	}
	if operationHasResponseModel(operation) {
		output.WriteString("    headers[header_count++] = (h2_pal_http_header_t){{\"Accept\", 6u}, {\"application/json\", 16u}};\n")
	}
	output.WriteString("    if (client->config.header_callback != NULL) {\n")
	output.WriteString("        result = client->config.header_callback(client->config.header_user, headers, header_capacity, &header_count);\n")
	fmt.Fprintf(output, "        if (result != %s_OK || header_count > header_capacity) { if (result == %s_OK) result = %s_ERR_INVALID_ARG; goto cleanup_headers; }\n    }\n", macro, macro, macro)
	fmt.Fprintf(output, "    for (size_t i = 0u; i < header_count; ++i) { if (!%s_http_header_valid(&headers[i])) { result = %s_ERR_INVALID_ARG; goto cleanup_headers; } }\n", prefix, macro)

	output.WriteString("    h2_pal_json_document_t *request_document = NULL;\n    h2_pal_json_buffer_t request_body = {0};\n    char *multipart_body = NULL;\n    size_t multipart_body_len = 0u;\n")
	if operation.RequestModel != "" {
		if operation.RequestMediaType == "multipart/form-data" {
			emitMultipartBody(output, prefix, macro, operation, requestModel, bodyCondition)
		} else {
			fmt.Fprintf(output, "    if (%s) {\n", bodyCondition)
			fmt.Fprintf(output, "        result = %s_from_pal(h2_pal_json_document_create(client->config.json, NULL, &request_document));\n", prefix)
			fmt.Fprintf(output, "        if (result != %s_OK) goto cleanup_headers;\n", macro)
			output.WriteString("        h2_pal_json_value_t *request_root = NULL;\n")
			fmt.Fprintf(output, "        result = %s_%s_encode(client, request_document, request->body, &request_root);\n", prefix, operation.RequestModel)
			fmt.Fprintf(output, "        if (result != %s_OK) goto cleanup_json;\n", macro)
			fmt.Fprintf(output, "        result = %s_from_pal(h2_pal_json_document_set_root(client->config.json, request_document, request_root));\n", prefix)
			fmt.Fprintf(output, "        if (result != %s_OK) goto cleanup_json;\n", macro)
			fmt.Fprintf(output, "        result = %s_from_pal(h2_pal_json_document_serialize(client->config.json, request_document, &request_body));\n", prefix)
			fmt.Fprintf(output, "        if (result != %s_OK || request_body.len > client->config.max_request_bytes) { if (result == %s_OK) result = %s_ERR_NO_SPACE; goto cleanup_json; }\n", macro, macro, macro)
			output.WriteString("    }\n")
		}
	}
	output.WriteString("    uint8_t *response_buffer = h2_pal_mem_alloc(client->config.mem, client->config.max_response_bytes);\n")
	fmt.Fprintf(output, "    if (response_buffer == NULL) { result = %s_ERR_NO_MEMORY; goto cleanup_json; }\n", macro)
	if len(operationResponseHeaders(operation)) != 0 {
		fmt.Fprintf(output, "    %s_%s_response_header_context_t response_header_context = {client, response};\n", prefix, operation.Name)
	}
	fmt.Fprintf(output, "    h2_pal_http_request_t http_request = {\n        .method = H2_PAL_HTTP_%s, .url = {url.data, url.len}, .headers = headers, .header_count = header_count,\n", operation.Method)
	output.WriteString("        .body = multipart_body != NULL ? (const uint8_t *)multipart_body : request_body.data, .body_len = multipart_body != NULL ? multipart_body_len : request_body.len, .timeout_ms = client->config.timeout_ms,\n        .response_buf = response_buffer, .response_buf_cap = client->config.max_response_bytes, .allocator = client->config.mem,\n")
	if len(operationResponseHeaders(operation)) != 0 {
		fmt.Fprintf(output, "        .response_header_cb = %s_%s_response_header, .response_header_user = &response_header_context,\n", prefix, operation.Name)
	}
	output.WriteString("    };\n")
	output.WriteString("    h2_pal_http_response_t http_response = {0};\n")
	fmt.Fprintf(output, "    result = %s_from_http(h2_pal_http_request(client->config.http, &http_request, &http_response));\n", prefix)
	fmt.Fprintf(output, "    if (result != %s_OK) goto cleanup_http_response;\n", macro)
	output.WriteString("    response->status_code = http_response.status_code;\n")
	fmt.Fprintf(output, "    result = (http_response.status_code >= 200 && http_response.status_code < 300) ? %s_ERR_UNEXPECTED_STATUS : %s_ERR_HTTP_STATUS;\n", macro, macro)
	output.WriteString("    switch (http_response.status_code) {\n")
	for _, response := range operation.Responses {
		fmt.Fprintf(output, "    case %d:\n", response.Status)
		if response.Model == "" {
			if response.Success {
				fmt.Fprintf(output, "        result = %s_OK;\n", macro)
			} else {
				fmt.Fprintf(output, "        result = %s_ERR_HTTP_STATUS;\n", macro)
			}
			output.WriteString("        break;\n")
			continue
		}
		output.WriteString("    {\n        h2_pal_json_document_t *response_document = NULL;\n")
		if operationHasResponseModel(operation) {
			output.WriteString("        response->has_body = true;\n")
		}
		fmt.Fprintf(output, "        result = %s_from_pal(h2_pal_json_document_parse(client->config.json, http_response.body, http_response.body_len, NULL, &response_document));\n", prefix)
		output.WriteString("        h2_pal_json_value_t *response_root = NULL;\n")
		fmt.Fprintf(output, "        if (result == %s_OK) result = %s_from_pal(h2_pal_json_document_root(client->config.json, response_document, &response_root));\n", macro, prefix)
		fmt.Fprintf(output, "        if (result == %s_OK) result = %s_%s_decode(client, response_root, &response->body.status_%d);\n", macro, prefix, response.Model, response.Status)
		output.WriteString("        (void)h2_pal_json_document_destroy(client->config.json, &response_document);\n")
		if response.Success {
			fmt.Fprintf(output, "        if (result == %s_OK) result = %s_OK;\n", macro, macro)
		} else {
			fmt.Fprintf(output, "        if (result == %s_OK) result = %s_ERR_HTTP_STATUS;\n", macro, macro)
		}
		output.WriteString("        break;\n    }\n")
	}
	output.WriteString("    default:\n        break;\n    }\n")
	output.WriteString("cleanup_http_response:\n    h2_pal_http_response_free(client->config.http, &http_response);\n    h2_pal_mem_free(client->config.mem, response_buffer);\ncleanup_json:\n    h2_pal_mem_free(client->config.mem, multipart_body);\n    (void)h2_pal_json_buffer_release(client->config.json, &request_body);\n    (void)h2_pal_json_document_destroy(client->config.json, &request_document);\ncleanup_headers:\n    h2_pal_mem_free(client->config.mem, authorization);\n    h2_pal_mem_free(client->config.mem, headers);\ncleanup_url:\n    h2_pal_mem_free(client->config.mem, url_data);\n")
	fmt.Fprintf(output, "    if (result != %s_OK && result != %s_ERR_HTTP_STATUS) {\n", macro, macro)
	output.WriteString("        const int completed_status = response->status_code;\n")
	fmt.Fprintf(output, "        %s_%s_response_deinit(response);\n", prefix, operation.Name)
	output.WriteString("        response->status_code = completed_status;\n        response->mem = client->config.mem;\n    }\n")
	output.WriteString("    return result;\n}\n\n")
}

func emitPath(output *bytes.Buffer, prefix string, macro string, operation operation) {
	remaining := operation.Path
	for len(remaining) != 0 {
		start := strings.IndexByte(remaining, '{')
		if start < 0 {
			fmt.Fprintf(output, "    result = %s_buffer_append(&url, \"%s\", %d); if (result != %s_OK) goto cleanup_url;\n", prefix, escapeCString(remaining), len(remaining), macro)
			break
		}
		if start > 0 {
			literal := remaining[:start]
			fmt.Fprintf(output, "    result = %s_buffer_append(&url, \"%s\", %d); if (result != %s_OK) goto cleanup_url;\n", prefix, escapeCString(literal), len(literal), macro)
		}
		end := strings.IndexByte(remaining[start:], '}')
		if end < 0 {
			return
		}
		name := remaining[start+1 : start+end]
		parameter := findParameter(operation.Parameters, "path", name)
		if parameter != nil && parameter.Type.Kind == "string" {
			fmt.Fprintf(output, "    result = %s_buffer_url_encode(&url, request->%s); if (result != %s_OK) goto cleanup_url;\n", prefix, parameter.CName, macro)
		} else if parameter != nil {
			emitScalarAppend(output, prefix, macro, *parameter, "")
		}
		remaining = remaining[start+end+1:]
	}
}

func emitMultipartBoundary(output *bytes.Buffer, prefix string, macro string, model *modelSpec, bodyCondition string) {
	fmt.Fprintf(output, "    if (%s) {\n", bodyCondition)
	output.WriteString("        uint64_t multipart_boundary_index = 0u;\n        for (;;) {\n")
	output.WriteString("            int boundary_len = snprintf(multipart_boundary, sizeof(multipart_boundary), \"h2-openapi-boundary-%016llx\", (unsigned long long)multipart_boundary_index);\n")
	fmt.Fprintf(output, "            if (boundary_len < 0 || (size_t)boundary_len >= sizeof(multipart_boundary)) return %s_ERR_NO_SPACE;\n", macro)
	output.WriteString("            multipart_boundary_len = (size_t)boundary_len;\n            bool boundary_conflict = false;\n")
	if model != nil && model.Alias == nil && len(model.Variants) == 0 {
		for _, field := range model.Fields {
			if field.ReadOnly || (field.Type.Kind != "string" && field.Type.Kind != "bytes") {
				continue
			}
			condition := "true"
			if !field.Required {
				condition = "request->body->" + field.PresenceName
			}
			if field.Type.Nullable {
				condition = "(" + condition + " && !request->body->" + field.NullName + ")"
			}
			fmt.Fprintf(output, "            if (%s && %s_bytes_contain(request->body->%s.data, request->body->%s.len, multipart_boundary, multipart_boundary_len)) boundary_conflict = true;\n", condition, prefix, field.CName, field.CName)
		}
	}
	output.WriteString("            if (!boundary_conflict) break;\n            ++multipart_boundary_index;\n        }\n")
	output.WriteString("        int content_type_len = snprintf(multipart_content_type, sizeof(multipart_content_type), \"multipart/form-data; boundary=%s\", multipart_boundary);\n")
	fmt.Fprintf(output, "        if (content_type_len < 0 || (size_t)content_type_len >= sizeof(multipart_content_type)) return %s_ERR_NO_SPACE;\n", macro)
	output.WriteString("        multipart_content_type_len = (size_t)content_type_len;\n    }\n")
}

func emitMultipartBody(output *bytes.Buffer, prefix string, macro string, operation operation, model *modelSpec, bodyCondition string) {
	fmt.Fprintf(output, "    if (%s) {\n", bodyCondition)
	output.WriteString("        if (client->config.max_request_bytes == SIZE_MAX) { result = ")
	output.WriteString(macro)
	output.WriteString("_ERR_NO_SPACE; goto cleanup_json; }\n")
	output.WriteString("        multipart_body = h2_pal_mem_alloc(client->config.mem, client->config.max_request_bytes + 1u);\n")
	fmt.Fprintf(output, "        if (multipart_body == NULL) { result = %s_ERR_NO_MEMORY; goto cleanup_json; }\n", macro)
	fmt.Fprintf(output, "        %s_buffer_t multipart = {multipart_body, 0u, client->config.max_request_bytes};\n", prefix)
	if model == nil || model.Alias != nil || len(model.Variants) != 0 {
		fmt.Fprintf(output, "        result = %s_ERR_UNSUPPORTED; goto cleanup_json;\n", macro)
	} else {
		for _, field := range model.Fields {
			if field.ReadOnly {
				continue
			}
			condition := "true"
			if !field.Required {
				condition = "request->body->" + field.PresenceName
			}
			if field.Type.Nullable {
				condition = "(" + condition + " && !request->body->" + field.NullName + ")"
			}
			fmt.Fprintf(output, "        if (%s) {\n", condition)
			prefixText := "\r\nContent-Disposition: form-data; name=\"" + escapeMultipartQuoted(field.JSONName) + "\""
			if field.Type.Kind == "bytes" {
				prefixText += "; filename=\"blob\"\r\nContent-Type: application/octet-stream"
			}
			prefixText += "\r\n\r\n"
			fmt.Fprintf(output, "            result = %s_buffer_append(&multipart, \"--\", 2u); if (result != %s_OK) goto cleanup_json;\n", prefix, macro)
			fmt.Fprintf(output, "            result = %s_buffer_append(&multipart, multipart_boundary, multipart_boundary_len); if (result != %s_OK) goto cleanup_json;\n", prefix, macro)
			fmt.Fprintf(output, "            result = %s_buffer_append(&multipart, \"%s\", %du); if (result != %s_OK) goto cleanup_json;\n", prefix, escapeCString(prefixText), len(prefixText), macro)
			switch field.Type.Kind {
			case "string":
				fmt.Fprintf(output, "            if (!%s_string_valid(request->body->%s, %d, %s)) { result = %s_ERR_INVALID_ARG; goto cleanup_json; }\n", prefix, field.CName, field.Type.MinLength, maxLengthExpression(field.Type), macro)
				emitEnumGuardGoto(output, field.Type, "request->body->"+field.CName, "            ", macro+"_ERR_INVALID_ARG", "cleanup_json")
				fmt.Fprintf(output, "            result = %s_buffer_append(&multipart, request->body->%s.data, request->body->%s.len); if (result != %s_OK) goto cleanup_json;\n", prefix, field.CName, field.CName, macro)
			case "bytes":
				fmt.Fprintf(output, "            if (request->body->%s.data == NULL && request->body->%s.len != 0u) { result = %s_ERR_INVALID_ARG; goto cleanup_json; }\n", field.CName, field.CName, macro)
				fmt.Fprintf(output, "            result = %s_buffer_append(&multipart, (const char *)request->body->%s.data, request->body->%s.len); if (result != %s_OK) goto cleanup_json;\n", prefix, field.CName, field.CName, macro)
			default:
				fmt.Fprintf(output, "            result = %s_ERR_UNSUPPORTED; goto cleanup_json;\n", macro)
			}
			fmt.Fprintf(output, "            result = %s_buffer_append(&multipart, \"\\r\\n\", 2u); if (result != %s_OK) goto cleanup_json;\n", prefix, macro)
			output.WriteString("        }\n")
		}
		fmt.Fprintf(output, "        result = %s_buffer_append(&multipart, \"--\", 2u); if (result != %s_OK) goto cleanup_json;\n", prefix, macro)
		fmt.Fprintf(output, "        result = %s_buffer_append(&multipart, multipart_boundary, multipart_boundary_len); if (result != %s_OK) goto cleanup_json;\n", prefix, macro)
		fmt.Fprintf(output, "        result = %s_buffer_append(&multipart, \"--\\r\\n\", 4u); if (result != %s_OK) goto cleanup_json;\n", prefix, macro)
		output.WriteString("        multipart_body_len = multipart.len;\n")
	}
	output.WriteString("    }\n")
}

func emitQuery(output *bytes.Buffer, prefix string, macro string, operation operation) {
	hasQuery := false
	for _, parameter := range operation.Parameters {
		if parameter.Location == "query" {
			hasQuery = true
			break
		}
	}
	if hasQuery {
		output.WriteString("    bool url_has_query = false;\n")
	}
	for _, parameter := range operation.Parameters {
		if parameter.Location != "query" {
			continue
		}
		condition := "true"
		if !parameter.Required {
			condition = "request->" + parameter.PresenceName
		}
		if parameter.Type.Nullable {
			condition = "(" + condition + " && !request->" + parameter.NullName + ")"
		}
		fmt.Fprintf(output, "    if (%s) {\n", condition)
		encodedName := urlEncodedLiteral(parameter.Name)
		if parameter.Type.Kind == "array" {
			fmt.Fprintf(output, "        for (size_t query_index = 0u; query_index < request->%s.count; ++query_index) {\n", parameter.CName)
			fmt.Fprintf(output, "            result = %s_buffer_append(&url, url_has_query ? \"&%s=\" : \"?%s=\", %d); if (result != %s_OK) goto cleanup_url;\n", prefix, encodedName, encodedName, len(encodedName)+2, macro)
			output.WriteString("            url_has_query = true;\n")
			itemExpression := "request->" + parameter.CName + ".items[query_index]"
			if parameter.Type.Item.Kind == "string" {
				fmt.Fprintf(output, "            if (!%s_string_valid(%s, %d, %s)) { result = %s_ERR_INVALID_ARG; goto cleanup_url; }\n", prefix, itemExpression, parameter.Type.Item.MinLength, maxLengthExpression(*parameter.Type.Item), macro)
				emitEnumGuardGoto(output, *parameter.Type.Item, itemExpression, "            ", macro+"_ERR_INVALID_ARG", "cleanup_url")
				fmt.Fprintf(output, "            result = %s_buffer_url_encode(&url, %s); if (result != %s_OK) goto cleanup_url;\n", prefix, itemExpression, macro)
			} else {
				if parameter.Type.Item.Kind == "int64" && parameter.Type.Item.Minimum != nil && parameter.Type.Item.Maximum != nil {
					fmt.Fprintf(output, "            if (%s < %dLL || %s > %dLL) { result = %s_ERR_INVALID_ARG; goto cleanup_url; }\n", itemExpression, *parameter.Type.Item.Minimum, itemExpression, *parameter.Type.Item.Maximum, macro)
				}
				if parameter.Type.Item.Kind == "float" || parameter.Type.Item.Kind == "double" {
					fmt.Fprintf(output, "            if (!isfinite((double)%s)) { result = %s_ERR_INVALID_ARG; goto cleanup_url; }\n", itemExpression, macro)
					if parameter.Type.Item.NumberMinimum != nil {
						fmt.Fprintf(output, "            if ((double)%s < %.17g) { result = %s_ERR_INVALID_ARG; goto cleanup_url; }\n", itemExpression, *parameter.Type.Item.NumberMinimum, macro)
					}
					if parameter.Type.Item.NumberMaximum != nil {
						fmt.Fprintf(output, "            if ((double)%s > %.17g) { result = %s_ERR_INVALID_ARG; goto cleanup_url; }\n", itemExpression, *parameter.Type.Item.NumberMaximum, macro)
					}
				}
				emitScalarExpressionAppend(output, prefix, macro, *parameter.Type.Item, itemExpression, parameter.CName+"_item", "            ")
			}
			output.WriteString("        }\n")
		} else {
			fmt.Fprintf(output, "        result = %s_buffer_append(&url, url_has_query ? \"&%s=\" : \"?%s=\", %d); if (result != %s_OK) goto cleanup_url;\n", prefix, encodedName, encodedName, len(encodedName)+2, macro)
			output.WriteString("        url_has_query = true;\n")
			if parameter.Type.Kind == "string" {
				fmt.Fprintf(output, "        if (!%s_string_valid(request->%s, %d, %s)) { result = %s_ERR_INVALID_ARG; goto cleanup_url; }\n", prefix, parameter.CName, parameter.Type.MinLength, maxLengthExpression(parameter.Type), macro)
				fmt.Fprintf(output, "        result = %s_buffer_url_encode(&url, request->%s); if (result != %s_OK) goto cleanup_url;\n", prefix, parameter.CName, macro)
			} else {
				emitScalarAppend(output, prefix, macro, parameter, "        ")
			}
		}
		output.WriteString("    }\n")
	}
}

func emitScalarAppend(output *bytes.Buffer, prefix string, macro string, parameter parameterSpec, indent string) {
	emitScalarExpressionAppend(output, prefix, macro, parameter.Type, "request->"+parameter.CName, parameter.CName, indent)
}

func emitScalarExpressionAppend(output *bytes.Buffer, prefix string, macro string, valueType typeSpec, expression string, variableBase string, indent string) {
	format := "%ld"
	cast := "(long)"
	switch valueType.Kind {
	case "bool":
		fmt.Fprintf(output, "%sresult = %s_buffer_append(&url, %s ? \"true\" : \"false\", %s ? 4u : 5u); if (result != %s_OK) goto cleanup_url;\n", indent, prefix, expression, expression, macro)
		return
	case "int64":
		format = "%lld"
		cast = "(long long)"
	case "float", "double":
		format = "%.17g"
		cast = "(double)"
	}
	name := variableBase + "_text"
	fmt.Fprintf(output, "%schar %s[48];\n", indent, name)
	fmt.Fprintf(output, "%sint %s_len = snprintf(%s, sizeof(%s), \"%s\", %s%s);\n", indent, name, name, name, format, cast, expression)
	fmt.Fprintf(output, "%sif (%s_len < 0 || (size_t)%s_len >= sizeof(%s)) { result = %s_ERR_INVALID_ARG; goto cleanup_url; }\n", indent, name, name, name, macro)
	fmt.Fprintf(output, "%s%s_string_t %s_view = {%s, (size_t)%s_len};\n", indent, prefix, name, name, name)
	fmt.Fprintf(output, "%sresult = %s_buffer_url_encode(&url, %s_view); if (result != %s_OK) goto cleanup_url;\n", indent, prefix, name, macro)
}

func emitEnumGuardGoto(output *bytes.Buffer, valueType typeSpec, expression string, indent string, errorConstant string, label string) {
	if len(valueType.Enum) == 0 {
		return
	}
	output.WriteString(indent + "if (!( ")
	for index, value := range valueType.Enum {
		if index != 0 {
			output.WriteString(" || ")
		}
		if len(value) == 0 {
			fmt.Fprintf(output, "%s.len == 0u", expression)
		} else {
			fmt.Fprintf(output, "(%s.len == %d && memcmp(%s.data, \"%s\", %d) == 0)", expression, len(value), expression, escapeCString(value), len(value))
		}
	}
	fmt.Fprintf(output, ")) { result = %s; goto %s; }\n", errorConstant, label)
}

func findParameter(parameters []parameterSpec, location string, name string) *parameterSpec {
	for index := range parameters {
		if parameters[index].Location == location && parameters[index].Name == name {
			return &parameters[index]
		}
	}
	return nil
}

func findModel(models []modelSpec, name string) *modelSpec {
	for index := range models {
		if models[index].Name == name {
			return &models[index]
		}
	}
	return nil
}

func operationHasResponseModel(operation operation) bool {
	for _, response := range operation.Responses {
		if response.Model != "" {
			return true
		}
	}
	return false
}

func operationResponseHeaders(operation operation) []responseHeaderSpec {
	byName := make(map[string]responseHeaderSpec)
	for _, response := range operation.Responses {
		for _, header := range response.Headers {
			if _, exists := byName[strings.ToLower(header.Name)]; !exists {
				byName[strings.ToLower(header.Name)] = header
			}
		}
	}
	result := make([]responseHeaderSpec, 0, len(byName))
	for _, header := range byName {
		result = append(result, header)
	}
	sort.Slice(result, func(left, right int) bool {
		return strings.ToLower(result[left].Name) < strings.ToLower(result[right].Name)
	})
	return result
}

func emitStructMember(output *bytes.Buffer, prefix string, valueType typeSpec, name string, indent string) {
	if valueType.Kind == "array" {
		fmt.Fprintf(output, "%sstruct {\n%s    %s *items;\n%s    size_t count;\n%s} %s;\n", indent, indent, cType(prefix, *valueType.Item), indent, indent, name)
		return
	}
	fmt.Fprintf(output, "%s%s %s;\n", indent, cType(prefix, valueType), name)
}

func maxLengthExpression(valueType typeSpec) string {
	if valueType.MaxLengthSet {
		return fmt.Sprintf("(size_t)%du", valueType.MaxLength)
	}
	return "client->config.max_string_bytes"
}

func maxItemsExpression(valueType typeSpec) string {
	if valueType.MaxItemsSet {
		return fmt.Sprintf("(size_t)%du", valueType.MaxItems)
	}
	return "client->config.max_array_items"
}

func cType(prefix string, valueType typeSpec) string {
	switch valueType.Kind {
	case "string":
		return prefix + "_string_t"
	case "json":
		return prefix + "_json_t"
	case "bytes":
		return prefix + "_bytes_t"
	case "bool":
		return "bool"
	case "int32":
		return "int32_t"
	case "int64":
		return "int64_t"
	case "float":
		return "float"
	case "double":
		return "double"
	case "model":
		return prefix + "_" + valueType.Model + "_t *"
	default:
		return "void"
	}
}

func escapeCString(value string) string {
	var output strings.Builder
	for _, current := range []byte(value) {
		switch current {
		case '\\':
			output.WriteString("\\\\")
		case '"':
			output.WriteString("\\\"")
		default:
			if current >= 0x20 && current <= 0x7E {
				output.WriteByte(current)
			} else {
				fmt.Fprintf(&output, "\\%03o", current)
			}
		}
	}
	return output.String()
}

func escapeMultipartQuoted(value string) string {
	value = strings.ReplaceAll(value, "\\", "\\\\")
	return strings.ReplaceAll(value, "\"", "\\\"")
}

func urlEncodedLiteral(value string) string {
	const hex = "0123456789ABCDEF"
	var output strings.Builder
	for _, current := range []byte(value) {
		if (current >= 'a' && current <= 'z') || (current >= 'A' && current <= 'Z') || (current >= '0' && current <= '9') || current == '-' || current == '.' || current == '_' || current == '~' {
			output.WriteByte(current)
			continue
		}
		output.WriteByte('%')
		output.WriteByte(hex[current>>4])
		output.WriteByte(hex[current&15])
	}
	return output.String()
}

func sortedModelNames(models []modelSpec) []string {
	names := make([]string, 0, len(models))
	for _, model := range models {
		names = append(names, model.Name)
	}
	sort.Strings(names)
	return names
}
