load("//tools/bazel:native_component.bzl", "firmware_native_component")

package(default_visibility = ["//visibility:public"])

exports_files([
    "cp.defaults",
    "usr_gpio_cfg.h",
])

firmware_native_component(
    name = "cp",
    srcs = ["src/h2_bk7258_chip_cp.c"],
    hdrs = ["include/h2_bk7258_chip.h"],
    component_directory = "boards/bk7258_chip/cp",
    component_name = "h2_bk7258_chip_cp",
    data = ["CMakeLists.txt"],
    execution_unit = "cp",
    tags = ["manual"],
)
