package(default_visibility = ["//visibility:public"])

filegroup(
    name = "tuxemon",
    srcs = glob(
        ["**"],
        allow_empty = True,
        exclude = [
            "BUILD.bazel",
            "README.md",
        ],
    ) + [
        "//projects/pixa_games/apps/tuxemon/app:tuxemon",
    ],
)
