load("@aspect_rules_js//npm:defs.bzl", "npm_package")
load("@rules_python//python:defs.bzl", "py_test")
load("//tools/bazel/platforms:compatibility.bzl", "HOST_TOOL_COMPATIBILITY")

package(default_visibility = ["//visibility:public"])

npm_package(
    name = "h2loader",
    srcs = [
        "README.md",
        "package.json",
        "//:LICENSE",
        "//projects/h2loader/libs/web:h2loader_runtime.wasm",
        "//projects/h2loader/libs/web:h2loader_runtime.js",
        "//projects/h2loader/libs/web:src/h2loader.js",
        "//projects/h2loader/libs/web:src/h2loader_ports.js",
        "//projects/h2loader/libs/web:src/h2loader_protocol.js",
    ],
    include_runfiles = False,
    include_sources = False,
    include_srcs_packages = ["**"],
    include_transitive_sources = False,
    include_transitive_types = False,
    include_types = False,
    publishable = True,
    root_paths = [
        ".",
        "projects/h2loader/libs/web",
        "projects/h2loader/libs/web/src",
    ],
    target_compatible_with = HOST_TOOL_COMPATIBILITY,
)

py_test(
    name = "wasm_url_test",
    srcs = ["wasm_url_test.py"],
    data = [":h2loader"],
    target_compatible_with = HOST_TOOL_COMPATIBILITY,
)
