module(
    name = "gizos",
    version = "0.0.0",
)

bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "rules_cc", version = "0.2.17")

cc_configure = use_extension("@rules_cc//cc:extensions.bzl", "cc_configure_extension")
use_repo(cc_configure, "local_config_cc")

vendor_repositories = use_extension(
    "//tools/bazel/vendor:repositories.bzl",
    "vendor_repositories",
)
vendor_repositories.repository(
    name = "h2_vendor_ikcp",
    build_file = "//third_party:ikcp.BUILD.bazel",
    path = "third_party/ikcp",
)
use_repo(vendor_repositories, "h2_vendor_ikcp")

esp_repositories = use_extension(
    "//tools/bazel/native_repositories:esp_repositories.bzl",
    "esp_repositories",
)
use_repo(esp_repositories, "gizos_esp_idf_sdk", "gizos_esp_idf_tools")

esp32s3_cc = use_extension(
    "//tools/bazel/toolchains/esp32s3_cc:repositories.bzl",
    "esp32s3_cc_toolchain",
)
use_repo(esp32s3_cc, "gizos_esp32s3_cc_toolchain")

register_toolchains("@gizos_esp32s3_cc_toolchain//:toolchain")
