load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")
load("//tools/bazel:cc_options.bzl", "H2_C11_OPTS", "H2_WARNING_COPTS")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "c11",
    srcs = ["src/h2_atomic_c11.c"],
    conlyopts = H2_C11_OPTS,
    copts = H2_WARNING_COPTS,
    target_compatible_with = select({
        "//tools/bazel/platforms:host_linux_target_linux": [],
        "//tools/bazel/platforms:host_macos_target_macos": [],
        "@platforms//cpu:wasm32": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = ["//libs/atomic"],
)

cc_test(
    name = "c11_test",
    srcs = ["tests/test_h2_atomic_c11.c"],
    conlyopts = H2_C11_OPTS,
    copts = H2_WARNING_COPTS,
    linkopts = ["-pthread"],
    target_compatible_with = select({
        "//tools/bazel/platforms:host_linux_target_linux": [],
        "//tools/bazel/platforms:host_macos_target_macos": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [":c11", "//libs/atomic"],
)
