#ifndef H2_AC707N_COMPILE_ONLY_APP_CONFIG_H
#define H2_AC707N_COMPILE_ONLY_APP_CONFIG_H
// Bare-chip firmware: no display, radio, audio, PSRAM or cache-as-RAM.
#define CONFIG_FLASH_SIZE 0x800000
#define CONFIG_DEBUG_ENABLE 0
#define CONFIG_DEBUG_LITE_ENABLE 0
#define TCFG_FREE_DCACHE_WAY 0
#define TCFG_FREE_ICACHE_WAY 0
#define TCFG_PSRAM_DEV_ENABLE 0
#define TCFG_AUDIO_DISABLE 1
#define DAC_OBUF_OVERLAY_LP_BSS_EN 0
#define TCFG_ICACHE_RUN_BT_STATIC_RAM 0
#define TCFG_DCACHE_RUN_BT_STATIC_RAM 0
#define TCFG_ICACHE_RUN_DATA_CODE 0
#define CONFIG_SD_LATCH_IO 0
#define CONFIG_JL_UI_ENABLE 0
#define CONFIG_LVGL_UI_ENABLE 0
#define TCFG_CLOCK_OSC_HZ 24000000
#define CONFIG_SUPPORTED_CHIP_VERSION A,B,C
#define CONFIG_CHIP_NAME AC707N
#define CONFIG_PID AC707N
#define CONFIG_VID 0.01
#define CONFIG_DOUBLE_BANK_ENABLE 0
#define CONFIG_UPDATE_JUMP_TO_MASK 0
#define CONFIG_FLASH_DTR_EN 1
#define CONFIG_FLASH_WPS_EN 0
#define CONFIG_VM_OPT 1
#define CONFIG_BTIF_OPT 1
#define CONFIG_VOTP_SIZE 128
#define CONFIG_ANC_ENABLE 0
#define CONFIG_ONLY_GRENERATE_ALIGN_4K_CODE 1
#define CONFIG_RESET_PIN PB07
#define CONFIG_RESET_TIME 08
#define CONFIG_RESET_LEVEL 0
#define CONFIG_BREDR_STATIC_RAM_LEN 0
#define TCFG_EXCEPTION_CODE_AT_RAM 0
#define TCFG_UI_ENABLE 0
#define ALIGN_UNIT_256B 0
#define CONFIG_PLL_SOURCE_USING_LRC 0
// VM size is in KiB; retain room for all SDK-shipped OTA loader variants.
#define TCFG_VM_SIZE 128
#define CONFIG_FINDMY_INFO_ENABLE 0
#define RCSP_UPDATE_EN 0
#define TCFG_LRC_LYRICS_ENABLE 0
#define LRC_ENABLE_SAVE_LABEL_TO_FLASH 0

#define TCFG_BT_VOL_SYNC_ENABLE 0
#define TCFG_ADC0_ENABLE 0
#define TCFG_AUDIO_ANC_ENABLE 0
#endif
