#ifndef H2_ESP_BOARD_CONFIG_H
#define H2_ESP_BOARD_CONFIG_H

#define H2_ESP_BOARD_NAME "devkit"
#define H2_ESP_BOARD_FS_BASE_PATH "/h2fs"
#define H2_ESP_BOARD_FS_PARTITION_LABEL "h2test"
#define H2_ESP_BOARD_HAS_LED_STRIP 1
#define H2_DEVKIT_LED_STRIP_ID 601u
#define H2_DEVKIT_LED_STRIP_GPIO 48u
#define H2_DEVKIT_LED_STRIP_PIXEL_COUNT 1u
#define H2_DEVKIT_LED_STRIP_CHANNELS_PER_PIXEL 3u
#define H2_DEVKIT_LED_STRIP_RMT_RES_HZ 10000000u
#define H2_DEVKIT_LED_STRIP_RMT_DMA 0

#endif
