load("@rules_cc//cc:defs.bzl", "cc_library")
load("//tools/bazel:cc_options.bzl", "H2_C11_OPTS", "H2_WARNING_COPTS")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "pthread",
    srcs = ["src/h2_atomic_pthread.c"],
    conlyopts = H2_C11_OPTS,
    copts = H2_WARNING_COPTS,
    target_compatible_with = select({
        "//tools/bazel/platforms:is_android_arm64": ["@platforms//os:android"],
        "//tools/bazel/platforms:is_ios_sim_arm64": ["@platforms//os:ios"],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = ["//libs/atomic:locked_template"],
)
