load("@rules_python//python:defs.bzl", "py_binary", "py_library")
load("//tools/bazel/platforms:compatibility.bzl", "HOST_OR_MOBILE_TOOL_COMPATIBILITY")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "fixture",
    srcs = ["mqtt_fixture.py"],
    imports = ["."],
    target_compatible_with = HOST_OR_MOBILE_TOOL_COMPATIBILITY,
    deps = ["//projects/e2e/libs/pal-http-fixture:fixture"],
)

py_binary(
    name = "serve",
    srcs = ["serve.py"],
    legacy_create_init = 0,
    main = "serve.py",
    target_compatible_with = HOST_OR_MOBILE_TOOL_COMPATIBILITY,
    deps = [":fixture"],
)
