load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")
load("//tools/bazel:cc_options.bzl", "H2_C11_OPTS", "H2_WARNING_COPTS")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "task_names",
    srcs = ["src/h2_loader_task_names.c"],
    hdrs = ["include/h2_loader_task_names.h"],
    includes = ["include"],
)

cc_library(
    name = "h2loader",
    srcs = [
        "src/h2_loader_app_client.c",
        "src/h2_loader_ble.c",
        "src/h2_loader_boot.c",
        "src/h2_loader_command.c",
        "src/h2_loader_metadata.c",
        "src/h2_loader_package.c",
        "src/h2_loader_status.c",
        "src/h2_loader_stage.c",
    ],
    hdrs = [
        "include/h2_loader_app_client.h",
        "include/h2_loader_ble.h",
        "include/h2_loader_boot.h",
        "include/h2_loader_command.h",
        "include/h2_loader_memory.h",
        "include/h2_loader_metadata.h",
        "include/h2_loader_package.h",
        "include/h2_loader_status.h",
        "include/h2_loader_stage.h",
    ],
    conlyopts = H2_C11_OPTS,
    copts = H2_WARNING_COPTS,
    includes = ["include"],
    deps = [
        ":task_names",
        "//libs/bleikcp",
        "//libs/bundle",
        "//libs/command",
        "//libs/pal",
        "//tools/bazel:vendor_third_party_zlib",
    ],
)

cc_test(
    name = "h2loader_test",
    srcs = ["tests/test_h2loader.c"],
    conlyopts = H2_C11_OPTS,
    copts = H2_WARNING_COPTS,
    target_compatible_with = select({
        "//tools/bazel/platforms:host_linux_target_linux": [],
        "//tools/bazel/platforms:host_macos_target_macos": [],
        "//tools/bazel/platforms:host_windows_target_windows": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [":h2loader"],
)

cc_test(
    name = "h2loader_metadata_test",
    srcs = ["tests/test_h2loader_metadata.c"],
    conlyopts = H2_C11_OPTS,
    copts = H2_WARNING_COPTS,
    target_compatible_with = select({
        "//tools/bazel/platforms:host_linux_target_linux": [],
        "//tools/bazel/platforms:host_macos_target_macos": [],
        "//tools/bazel/platforms:host_windows_target_windows": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [":h2loader"],
)
