load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

exports_files(["cc_options.bzl"])

exports_files([
    "firmware_components.bzl",
    "native_component.bzl",
    "native_component.cmake",
    "native_versions/esp_idf_commit.txt",
    "native_versions/esp_idf_tool_versions.txt",
])

cc_library(
    name = "vendor_third_party_ikcp",
    tags = ["manual"],
    deps = ["@h2_vendor_ikcp//:ikcp"],
)

cc_library(
    name = "vendor_third_party_yyjson",
    tags = ["manual"],
    deps = ["@h2_vendor_yyjson//:yyjson"],
)

cc_library(
    name = "vendor_third_party_corehttp",
    data = ["@h2_vendor_corehttp//:all_sources"],
    tags = ["manual"],
    deps = ["@h2_vendor_corehttp//:headers"],
)

cc_library(
    name = "vendor_third_party_coremqtt",
    tags = ["manual"],
    deps = ["@h2_vendor_coremqtt//:coremqtt"],
)

cc_library(
    name = "vendor_third_party_sdl3",
    data = ["@h2_vendor_sdl3//:all_sources"],
    tags = ["manual"],
)

cc_library(
    name = "vendor_third_party_tinyh264",
    tags = ["manual"],
    deps = ["@h2_vendor_tinyh264//:tinyh264"],
)
