load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:private"])

cc_library(
    name = "gizclaw_headers",
    hdrs = glob([
        "sdk/c/gizclaw/generated/**/*.h",
        "sdk/c/gizclaw/include/**/*.h",
        "sdk/c/gizclaw/src/*.h",
    ]),
    includes = [
        "sdk/c/gizclaw/generated",
        "sdk/c/gizclaw/include",
    ],
    deps = ["@h2_gizclaw_nanopb//:nanopb"],
)

cc_library(
    name = "gizclaw_core",
    srcs = glob(
        [
            "sdk/c/gizclaw/generated/**/*.c",
            "sdk/c/gizclaw/src/*.c",
        ],
        exclude = ["sdk/c/gizclaw/src/gzc_platform.c"],
    ),
    conlyopts = ["-std=c11"],
    copts = [
        "-Wall",
        "-Wextra",
        "-Werror",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":gizclaw_headers",
        "@h2_gizclaw_nanopb//:nanopb",
    ],
)

cc_library(
    name = "default_platform",
    srcs = ["sdk/c/gizclaw/src/gzc_platform.c"],
    conlyopts = ["-std=c11"],
    copts = [
        "-Wall",
        "-Wextra",
        "-Werror",
    ],
    visibility = ["//visibility:public"],
    deps = [":gizclaw_headers"],
)

cc_library(
    name = "gizclaw",
    visibility = ["//visibility:public"],
    deps = [
        ":default_platform",
        ":gizclaw_core",
    ],
)
