#ifndef H2_GIZCLAW_RPC_H
#define H2_GIZCLAW_RPC_H

#include "h2_gizclaw_types.h"

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/** Wire method number from gizclaw.rpc.v1.RpcMethod. */
typedef int32_t h2_gizclaw_rpc_method_t;

enum {
  H2_GIZCLAW_RPC_ALL_PING = 1,
  H2_GIZCLAW_RPC_ALL_SPEED_TEST_RUN = 2,
  H2_GIZCLAW_RPC_CLIENT_INFO_GET = 3,
  H2_GIZCLAW_RPC_CLIENT_IDENTIFIERS_GET = 4,
  H2_GIZCLAW_RPC_SERVER_INFO_GET = 5,
  H2_GIZCLAW_RPC_SERVER_INFO_PUT = 6,
  H2_GIZCLAW_RPC_SERVER_RUN_WORKSPACE_GET = 11,
  H2_GIZCLAW_RPC_SERVER_RUN_WORKSPACE_SET = 12,
  H2_GIZCLAW_RPC_SERVER_RUN_WORKSPACE_RELOAD = 13,
  H2_GIZCLAW_RPC_SERVER_FIRMWARE_GET = 22,
  H2_GIZCLAW_RPC_SERVER_WORKSPACE_LIST = 24,
  H2_GIZCLAW_RPC_SERVER_WORKSPACE_GET = 25,
  H2_GIZCLAW_RPC_SERVER_WORKSPACE_CREATE = 26,
  H2_GIZCLAW_RPC_SERVER_WORKSPACE_PUT = 27,
  H2_GIZCLAW_RPC_SERVER_WORKSPACE_DELETE = 28,
  H2_GIZCLAW_RPC_SERVER_WORKSPACE_HISTORY_LIST = 29,
  H2_GIZCLAW_RPC_SERVER_WORKSPACE_HISTORY_GET = 30,
  H2_GIZCLAW_RPC_SERVER_WORKSPACE_HISTORY_AUDIO_DOWNLOAD = 31,
  H2_GIZCLAW_RPC_SERVER_WORKFLOW_LIST = 32,
  H2_GIZCLAW_RPC_SERVER_WORKFLOW_GET = 33,
  H2_GIZCLAW_RPC_SERVER_CONTACT_LIST = 38,
  H2_GIZCLAW_RPC_SERVER_CONTACT_GET = 39,
  H2_GIZCLAW_RPC_SERVER_CONTACT_CREATE = 40,
  H2_GIZCLAW_RPC_SERVER_CONTACT_PUT = 41,
  H2_GIZCLAW_RPC_SERVER_CONTACT_DELETE = 42,
  H2_GIZCLAW_RPC_SERVER_FRIEND_INVITE_TOKEN_GET = 43,
  H2_GIZCLAW_RPC_SERVER_FRIEND_INVITE_TOKEN_CREATE = 44,
  H2_GIZCLAW_RPC_SERVER_FRIEND_INVITE_TOKEN_CLEAR = 45,
  H2_GIZCLAW_RPC_SERVER_FRIEND_ADD = 46,
  H2_GIZCLAW_RPC_SERVER_FRIEND_LIST = 47,
  H2_GIZCLAW_RPC_SERVER_FRIEND_DELETE = 48,
  H2_GIZCLAW_RPC_SERVER_FRIEND_GROUP_LIST = 49,
  H2_GIZCLAW_RPC_SERVER_FRIEND_GROUP_GET = 50,
  H2_GIZCLAW_RPC_SERVER_FRIEND_GROUP_CREATE = 51,
  H2_GIZCLAW_RPC_SERVER_FRIEND_GROUP_PUT = 52,
  H2_GIZCLAW_RPC_SERVER_FRIEND_GROUP_DELETE = 53,
  H2_GIZCLAW_RPC_SERVER_FRIEND_GROUP_INVITE_TOKEN_GET = 54,
  H2_GIZCLAW_RPC_SERVER_FRIEND_GROUP_INVITE_TOKEN_CREATE = 55,
  H2_GIZCLAW_RPC_SERVER_FRIEND_GROUP_INVITE_TOKEN_CLEAR = 56,
  H2_GIZCLAW_RPC_SERVER_FRIEND_GROUP_JOIN = 57,
  H2_GIZCLAW_RPC_SERVER_FRIEND_GROUP_MEMBERS_LIST = 58,
  H2_GIZCLAW_RPC_SERVER_FRIEND_GROUP_MEMBERS_ADD = 59,
  H2_GIZCLAW_RPC_SERVER_FRIEND_GROUP_MEMBERS_PUT = 60,
  H2_GIZCLAW_RPC_SERVER_FRIEND_GROUP_MEMBERS_DELETE = 61,
  H2_GIZCLAW_RPC_SERVER_PET_LIST = 65,
  H2_GIZCLAW_RPC_SERVER_PET_GET = 66,
  H2_GIZCLAW_RPC_RUNTIME_ADOPT = 67,
  H2_GIZCLAW_RPC_SERVER_PET_PUT = 68,
  H2_GIZCLAW_RPC_SERVER_PET_DELETE = 69,
  H2_GIZCLAW_RPC_SERVER_PET_DRIVE = 70,
  H2_GIZCLAW_RPC_SERVER_POINTS_GET = 71,
  H2_GIZCLAW_RPC_SERVER_POINTS_TRANSACTIONS_LIST = 72,
  H2_GIZCLAW_RPC_SERVER_POINTS_TRANSACTIONS_GET = 73,
  H2_GIZCLAW_RPC_CLIENT_TOOL_INVOKE = 82,
  H2_GIZCLAW_RPC_SERVER_PET_ACTIONS_GET = 86,
  H2_GIZCLAW_RPC_SERVER_PET_PIXA_DOWNLOAD = 87,
  H2_GIZCLAW_RPC_SERVER_FRIEND_INFO_GET = 89,
  H2_GIZCLAW_RPC_SERVER_REGISTER = 90,
  H2_GIZCLAW_RPC_SERVER_SPEECH_TRANSCRIBE = 91,
  H2_GIZCLAW_RPC_SERVER_SPEECH_SYNTHESIZE = 92,
  H2_GIZCLAW_RPC_SERVER_PEER_DELETE = 93,
  H2_GIZCLAW_RPC_SERVER_SPEECH_EXTRACT = 94,
  H2_GIZCLAW_RPC_SERVER_WORKSPACE_INPUT_PUT = 107,
};

/** Canonical gRPC status codes (google.rpc.Code) carried by RpcStatus.code.
 * The values are the wire values; a provider response uses the same set. */
enum {
  H2_GIZCLAW_RPC_ERROR_OK = 0,
  H2_GIZCLAW_RPC_ERROR_CANCELLED = 1,
  H2_GIZCLAW_RPC_ERROR_UNKNOWN = 2,
  H2_GIZCLAW_RPC_ERROR_INVALID_ARGUMENT = 3,
  H2_GIZCLAW_RPC_ERROR_DEADLINE_EXCEEDED = 4,
  H2_GIZCLAW_RPC_ERROR_NOT_FOUND = 5,
  H2_GIZCLAW_RPC_ERROR_ALREADY_EXISTS = 6,
  H2_GIZCLAW_RPC_ERROR_PERMISSION_DENIED = 7,
  H2_GIZCLAW_RPC_ERROR_RESOURCE_EXHAUSTED = 8,
  H2_GIZCLAW_RPC_ERROR_FAILED_PRECONDITION = 9,
  H2_GIZCLAW_RPC_ERROR_ABORTED = 10,
  H2_GIZCLAW_RPC_ERROR_OUT_OF_RANGE = 11,
  H2_GIZCLAW_RPC_ERROR_UNIMPLEMENTED = 12,
  H2_GIZCLAW_RPC_ERROR_INTERNAL = 13,
  H2_GIZCLAW_RPC_ERROR_UNAVAILABLE = 14,
  H2_GIZCLAW_RPC_ERROR_DATA_LOSS = 15,
  H2_GIZCLAW_RPC_ERROR_UNAUTHENTICATED = 16,
};

typedef struct h2_gizclaw_rpc_bytes {
  const uint8_t *data;
  size_t len;
} h2_gizclaw_rpc_bytes_t;

typedef struct h2_gizclaw_rpc_provider_response {
  h2_gizclaw_rpc_bytes_t payload;
  bool has_error;
  int error_code;
  h2_gizclaw_rpc_bytes_t error_message;
} h2_gizclaw_rpc_provider_response_t;

/**
 * Handle a server-initiated client.* method.
 *
 * Request and response payloads are protobuf message bytes. Returned views are
 * borrowed and need to remain valid only until the callback returns.
 */
typedef int (*h2_gizclaw_rpc_provider_fn)(
    void *user, h2_gizclaw_rpc_method_t method,
    h2_gizclaw_rpc_bytes_t request_payload,
    h2_gizclaw_rpc_provider_response_t *out_response);

#ifdef __cplusplus
}
#endif

#endif
