load("@rules_cc//cc:defs.bzl", "cc_library")
load("//tools/bazel:cc_options.bzl", "H2_C11_OPTS", "H2_WARNING_COPTS")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "qmi8658",
    srcs = ["src/h2_qmi8658.c"],
    hdrs = [
        "include/h2_qmi8658.h",
        "include/h2_qmi8658_defs.h",
        "include/h2_qmi8658_transport.h",
    ],
    conlyopts = H2_C11_OPTS,
    copts = H2_WARNING_COPTS,
    includes = ["include"],
    deps = ["//libs/pal"],
)
