#include "h2_windows_platform.h"

#include <assert.h>

int main(void) {
    const h2_windows_platform_config_t config = {0};
    h2_windows_platform_t *platform = NULL;
    assert(h2_windows_platform_create(&config, &platform) == H2_PAL_OK);
    assert(h2_windows_mem_api(platform)->vtable->alloc != NULL);
    assert(h2_windows_mem_api(platform)->vtable->realloc != NULL);
    assert(h2_windows_mem_api(platform)->vtable->free != NULL);
    assert(h2_windows_log_api(platform)->vtable->write != NULL);
    assert(h2_windows_time_api(platform)->vtable->get_monotonic_ms != NULL);
    assert(h2_windows_time_api(platform)->vtable->get_wall_ms != NULL);
    assert(h2_windows_time_api(platform)->vtable->set_wall_ms != NULL);
    assert(h2_windows_time_api(platform)->vtable->get_wall_status != NULL);
    assert(h2_windows_time_api(platform)->vtable->sleep_ms != NULL);
    assert(h2_windows_timer_api(platform)->vtable->create != NULL);
    assert(h2_windows_timer_api(platform)->vtable->destroy != NULL);
    assert(h2_windows_timer_api(platform)->vtable->start != NULL);
    assert(h2_windows_timer_api(platform)->vtable->stop != NULL);
    assert(h2_windows_timer_api(platform)->vtable->reset != NULL);
    assert(h2_windows_timer_api(platform)->vtable->set_period_ms != NULL);
    assert(h2_windows_timer_api(platform)->vtable->is_running != NULL);
    assert(h2_windows_task_api(platform)->vtable->start != NULL);
    assert(h2_windows_task_api(platform)->vtable->join != NULL);
    assert(h2_windows_queue_api(platform)->vtable->create != NULL);
    assert(h2_windows_queue_api(platform)->vtable->destroy != NULL);
    assert(h2_windows_queue_api(platform)->vtable->send != NULL);
    assert(h2_windows_queue_api(platform)->vtable->send_latest != NULL);
    assert(h2_windows_queue_api(platform)->vtable->recv != NULL);
    assert(h2_windows_queue_api(platform)->vtable->reset != NULL);
    assert(h2_windows_queue_api(platform)->vtable->close != NULL);
    assert(h2_windows_sync_api(platform)->vtable->create_mutex != NULL);
    assert(h2_windows_sync_api(platform)->vtable->destroy_mutex != NULL);
    assert(h2_windows_sync_api(platform)->vtable->lock_mutex != NULL);
    assert(h2_windows_sync_api(platform)->vtable->try_lock_mutex != NULL);
    assert(h2_windows_sync_api(platform)->vtable->unlock_mutex != NULL);
    assert(h2_windows_sync_api(platform)->vtable->create_semaphore != NULL);
    assert(h2_windows_sync_api(platform)->vtable->destroy_semaphore != NULL);
    assert(h2_windows_sync_api(platform)->vtable->take_semaphore != NULL);
    assert(h2_windows_sync_api(platform)->vtable->give_semaphore != NULL);
    assert(h2_windows_sync_api(platform)->vtable->create_cond != NULL);
    assert(h2_windows_sync_api(platform)->vtable->destroy_cond != NULL);
    assert(h2_windows_sync_api(platform)->vtable->wait_cond != NULL);
    assert(h2_windows_sync_api(platform)->vtable->signal_cond != NULL);
    assert(h2_windows_sync_api(platform)->vtable->broadcast_cond != NULL);
    assert(h2_windows_fs_api(platform)->vtable->mkdir != NULL);
    assert(h2_windows_fs_api(platform)->vtable->open != NULL);
    assert(h2_windows_fs_api(platform)->vtable->read != NULL);
    assert(h2_windows_fs_api(platform)->vtable->seek != NULL);
    assert(h2_windows_fs_api(platform)->vtable->write != NULL);
    assert(h2_windows_fs_api(platform)->vtable->sync != NULL);
    assert(h2_windows_fs_api(platform)->vtable->close != NULL);
    assert(h2_windows_fs_api(platform)->vtable->stat != NULL);
    assert(h2_windows_fs_api(platform)->vtable->clear != NULL);
    assert(h2_windows_fs_api(platform)->vtable->remove != NULL);
    assert(h2_windows_fs_api(platform)->vtable->rename != NULL);
    assert(h2_windows_net_api(platform)->vtable->resolve_addr != NULL);
    assert(h2_windows_net_api(platform)->vtable->resolve_start != NULL);
    assert(h2_windows_net_api(platform)->vtable->resolve_poll != NULL);
    assert(h2_windows_net_api(platform)->vtable->resolve_close != NULL);
    assert(h2_windows_net_api(platform)->vtable->get_host_addr != NULL);
    assert(h2_windows_net_api(platform)->vtable->udp_open != NULL);
    assert(h2_windows_net_api(platform)->vtable->udp_sendto != NULL);
    assert(h2_windows_net_api(platform)->vtable->udp_recvfrom != NULL);
    assert(h2_windows_net_api(platform)->vtable->udp_open_bound != NULL);
    assert(h2_windows_net_api(platform)->vtable->udp_join_multicast != NULL);
    assert(h2_windows_net_api(platform)->vtable->tcp_open != NULL);
    assert(h2_windows_net_api(platform)->vtable->tcp_open_bound != NULL);
    assert(h2_windows_net_api(platform)->vtable->tcp_connect != NULL);
    assert(h2_windows_net_api(platform)->vtable->tcp_send != NULL);
    assert(h2_windows_net_api(platform)->vtable->tcp_send_timeout != NULL);
    assert(h2_windows_net_api(platform)->vtable->tcp_recv != NULL);
    assert(h2_windows_net_api(platform)->vtable->tls_wrap != NULL);
    assert(h2_windows_net_api(platform)->vtable->icmp_echo != NULL);
    assert(h2_windows_net_api(platform)->vtable->close != NULL);
    assert(h2_windows_netif_api(platform)->vtable->list != NULL);
    assert(h2_windows_netif_api(platform)->vtable->find != NULL);
    assert(h2_windows_netif_api(platform)->vtable->get_status != NULL);
    assert(h2_windows_netif_api(platform)->vtable->get_dns_servers != NULL);
    assert(h2_windows_system_event_api(platform)->vtable->init != NULL);
    assert(h2_windows_system_event_api(platform)->vtable->deinit != NULL);
    assert(h2_windows_system_event_api(platform)->vtable->post != NULL);
    assert(h2_windows_system_event_api(platform)->vtable->subscribe != NULL);
    assert(h2_windows_system_event_api(platform)->vtable->unsubscribe != NULL);
    assert(h2_windows_platform_destroy(&platform) == H2_PAL_OK);
    return 0;
}
