// Generated by //tools/openapi_codegen. DO NOT EDIT.
#ifndef H2_STATUS_API_H
#define H2_STATUS_API_H

#include "h2/pal/application/h2_pal_http.h"
#include "h2/pal/os/h2_pal_json.h"
#include "h2/pal/os/h2_pal_mem.h"

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum h2_status_result {
    H2_STATUS_OK = 0,
    H2_STATUS_ERR_INVALID_ARG = -1,
    H2_STATUS_ERR_NO_MEMORY = -2,
    H2_STATUS_ERR_NO_SPACE = -3,
    H2_STATUS_ERR_HTTP = -4,
    H2_STATUS_ERR_HTTP_STATUS = -5,
    H2_STATUS_ERR_UNEXPECTED_STATUS = -6,
    H2_STATUS_ERR_JSON = -7,
    H2_STATUS_ERR_UNSUPPORTED = -8
} h2_status_result_t;

#define H2_STATUS_MAX_URL_BYTES ((size_t)64u * 1024u)
#define H2_STATUS_MAX_RESPONSE_BYTES H2_PAL_JSON_DEFAULT_MAX_DOCUMENT_BYTES

#define H2_STATUS_OPERATION_COUNT 1u

/** UTF-8 byte view: borrowed in requests; response views are owned by their response. */
typedef struct h2_status_string {
    const char *data;
    size_t len;
} h2_status_string_t;

/** Opaque JSON value encoded as one complete UTF-8 JSON document. */
typedef h2_status_string_t h2_status_json_t;

/** Borrowed binary byte view used by multipart request fields. */
typedef struct h2_status_bytes {
    const uint8_t *data;
    size_t len;
} h2_status_bytes_t;



/**
 * Synchronously edit request headers before encoding and transport.
 *
 * Entries below `*in_out_count` are initialized; remaining entries through
 * `capacity` are zeroed and available for additions. The callback must leave
 * `*in_out_count <= capacity`. Any name/value spans it supplies are borrowed
 * by the operation and must remain valid until that synchronous call returns.
 */
typedef h2_status_result_t (*h2_status_header_callback_t)(
    void *user,
    h2_pal_http_header_t *headers,
    size_t capacity,
    size_t *in_out_count);

/** Borrowed configuration. All pointed-to capabilities and strings must outlive calls. */
typedef struct h2_status_client_config {
    const h2_pal_http_api_t *http;
    const h2_pal_json_api_t *json;
    const h2_pal_mem_api_t *mem;
    const char *base_url;
    size_t max_url_bytes;
    int timeout_ms;
    size_t max_response_bytes;
    size_t max_request_bytes;
    size_t max_string_bytes;
    size_t max_array_items;
    h2_status_string_t bearer_token;
    h2_status_header_callback_t header_callback;
    void *header_user;
    size_t max_extra_headers;
} h2_status_client_config_t;

typedef struct h2_status_client {
    h2_status_client_config_t config;
} h2_status_client_t;

/** Initialize a client by borrowing all PAL capabilities and configuration strings. */
h2_status_result_t h2_status_client_init(h2_status_client_t *client, const h2_status_client_config_t *config);

typedef struct h2_status_get_health_request {
    uint8_t reserved;
} h2_status_get_health_request_t;

/** Unique-owned response. Zero-initialize before first use; do not copy while live. */
typedef struct h2_status_get_health_response {
    int status_code;
    const h2_pal_mem_api_t *mem;
} h2_status_get_health_response_t;

/** Execute synchronously. Request data is borrowed; any previous response value is released before reuse. */
h2_status_result_t h2_status_get_health(
    h2_status_client_t *client,
    const h2_status_get_health_request_t *request,
    h2_status_get_health_response_t *response);
/** Release all response-owned memory. Safe on a zeroed response. */
void h2_status_get_health_response_deinit(h2_status_get_health_response_t *response);

#ifdef __cplusplus
}
#endif

#endif  // H2_STATUS_API_H
