// Generated by //tools/openapi_codegen. DO NOT EDIT.
#include "h2_status_api.h"

#include <float.h>
#include <math.h>
#include <stdio.h>
#include <string.h>

static h2_status_result_t h2_status_from_pal(h2_pal_result_t result) {
    if (result == H2_PAL_OK) return H2_STATUS_OK;
    if (result == H2_PAL_ERR_NO_MEMORY) return H2_STATUS_ERR_NO_MEMORY;
    if (result == H2_PAL_ERR_NO_SPACE) return H2_STATUS_ERR_NO_SPACE;
    if (result == H2_PAL_ERR_UNSUPPORTED) return H2_STATUS_ERR_UNSUPPORTED;
    return H2_STATUS_ERR_JSON;
}

static h2_status_result_t h2_status_from_http(int result) {
    if (result == H2_PAL_OK) return H2_STATUS_OK;
    if (result == H2_PAL_ERR_NO_MEMORY) return H2_STATUS_ERR_NO_MEMORY;
    if (result == H2_PAL_ERR_NO_SPACE) return H2_STATUS_ERR_NO_SPACE;
    if (result == H2_PAL_ERR_UNSUPPORTED) return H2_STATUS_ERR_UNSUPPORTED;
    return H2_STATUS_ERR_HTTP;
}

static bool h2_status_utf8_valid(const char *data, size_t len) {
    size_t i = 0u;
    while (i < len) {
        const unsigned char first = (unsigned char)data[i++];
        if (first == 0u) return false;
        if (first < 0x80u) continue;
        size_t remaining = 0u;
        unsigned int codepoint = 0u;
        unsigned int minimum = 0u;
        if (first >= 0xC2u && first <= 0xDFu) { remaining = 1u; codepoint = first & 0x1Fu; minimum = 0x80u; }
        else if (first >= 0xE0u && first <= 0xEFu) { remaining = 2u; codepoint = first & 0x0Fu; minimum = 0x800u; }
        else if (first >= 0xF0u && first <= 0xF4u) { remaining = 3u; codepoint = first & 0x07u; minimum = 0x10000u; }
        else return false;
        if (remaining > len - i) return false;
        while (remaining-- != 0u) {
            const unsigned char next = (unsigned char)data[i++];
            if ((next & 0xC0u) != 0x80u) return false;
            codepoint = (codepoint << 6) | (next & 0x3Fu);
        }
        if (codepoint < minimum || codepoint > 0x10FFFFu || (codepoint >= 0xD800u && codepoint <= 0xDFFFu)) return false;
    }
    return true;
}

static bool h2_status_string_valid(h2_status_string_t value, size_t minimum, size_t maximum) {
    return value.len >= minimum && value.len <= maximum && (value.data != NULL || value.len == 0u) && h2_status_utf8_valid(value.data, value.len);
}

static bool h2_status_header_value_valid(h2_status_string_t value, size_t minimum, size_t maximum) {
    if (!h2_status_string_valid(value, minimum, maximum)) return false;
    for (size_t i = 0u; i < value.len; ++i) if (value.data[i] == '\r' || value.data[i] == '\n') return false;
    return true;
}

static bool h2_status_http_header_valid(const h2_pal_http_header_t *header) {
    if (header == NULL || header->name.data == NULL || header->name.len == 0u || (header->value.data == NULL && header->value.len != 0u)) return false;
    for (size_t i = 0u; i < header->name.len; ++i) {
        const unsigned char value = (unsigned char)header->name.data[i];
        const bool alphanumeric = (value >= 'a' && value <= 'z') || (value >= 'A' && value <= 'Z') || (value >= '0' && value <= '9');
        const bool symbol = value == '!' || value == '#' || value == '$' || value == '%' || value == '&' || value == '\'' || value == '*' || value == '+' || value == '-' || value == '.' || value == '^' || value == '_' || value == '`' || value == '|' || value == '~';
        if (!alphanumeric && !symbol) return false;
    }
    for (size_t i = 0u; i < header->value.len; ++i) {
        const unsigned char value = (unsigned char)header->value.data[i];
        if ((value < 0x20u && value != '\t') || value == 0x7Fu) return false;
    }
    return true;
}

static bool h2_status_header_name_equal(h2_pal_http_str_t value, const char *expected, size_t expected_len) {
    if (value.len != expected_len || (value.data == NULL && value.len != 0u)) return false;
    for (size_t i = 0u; i < value.len; ++i) { unsigned char left = (unsigned char)value.data[i]; unsigned char right = (unsigned char)expected[i]; if (left >= 'A' && left <= 'Z') left = (unsigned char)(left + ('a' - 'A')); if (right >= 'A' && right <= 'Z') right = (unsigned char)(right + ('a' - 'A')); if (left != right) return false; }
    return true;
}

static bool h2_status_config_valid(const h2_status_client_config_t *config) {
    if (config == NULL || config->http == NULL || config->http->vtable == NULL || config->http->vtable->request == NULL || config->http->vtable->response_free == NULL || config->json == NULL || config->json->vtable == NULL || config->mem == NULL || config->mem->vtable == NULL || config->mem->vtable->alloc == NULL || config->mem->vtable->realloc == NULL || config->mem->vtable->free == NULL || config->base_url == NULL || config->base_url[0] == '\0') return false;
    if (config->max_url_bytes == 0u || config->max_url_bytes > H2_STATUS_MAX_URL_BYTES || config->max_response_bytes == 0u || config->max_response_bytes > H2_STATUS_MAX_RESPONSE_BYTES) return false;
    if (config->max_request_bytes == 0u || config->max_request_bytes == SIZE_MAX || config->max_string_bytes == 0u || config->max_string_bytes == SIZE_MAX || config->max_array_items == 0u) return false;
    if ((config->bearer_token.data == NULL && config->bearer_token.len != 0u) || !h2_status_utf8_valid(config->bearer_token.data, config->bearer_token.len)) return false;
    const h2_pal_json_vtable_t *json = config->json->vtable;
    return json->document_parse != NULL && json->document_create != NULL && json->document_destroy != NULL && json->document_root != NULL && json->document_set_root != NULL && json->value_create_null != NULL && json->value_create_boolean != NULL && json->value_create_number != NULL && json->value_create_string != NULL && json->value_create_array != NULL && json->value_create_object != NULL && json->value_type != NULL && json->value_get_boolean != NULL && json->value_get_number != NULL && json->value_get_string != NULL && json->array_size != NULL && json->array_get != NULL && json->array_append != NULL && json->object_size != NULL && json->object_entry != NULL && json->object_get != NULL && json->object_set != NULL && json->document_serialize != NULL && json->buffer_release != NULL;
}

static h2_status_result_t h2_status_copy_string(const h2_pal_mem_api_t *mem, h2_pal_json_string_view_t source, size_t maximum, h2_status_string_t *output) {
    if (source.len > maximum) return H2_STATUS_ERR_NO_SPACE;
    char *copy = h2_pal_mem_alloc(mem, source.len + 1u);
    if (copy == NULL) return H2_STATUS_ERR_NO_MEMORY;
    if (source.len != 0u) memcpy(copy, source.data, source.len);
    copy[source.len] = '\0';
    output->data = copy;
    output->len = source.len;
    return H2_STATUS_OK;
}

typedef struct h2_status_buffer { char *data; size_t len; size_t cap; } h2_status_buffer_t;

static h2_status_result_t h2_status_buffer_append(h2_status_buffer_t *buffer, const char *data, size_t len) {
    if (len > buffer->cap - buffer->len) return H2_STATUS_ERR_NO_SPACE;
    if (len != 0u) memcpy(buffer->data + buffer->len, data, len);
    buffer->len += len;
    buffer->data[buffer->len] = '\0';
    return H2_STATUS_OK;
}

static bool h2_status_bytes_contain(const void *data, size_t data_len, const char *needle, size_t needle_len) {
    if (needle_len == 0u) return true;
    if (data == NULL || needle == NULL || needle_len > data_len) return false;
    const uint8_t *bytes = data;
    for (size_t offset = 0u; offset <= data_len - needle_len; ++offset) if (memcmp(bytes + offset, needle, needle_len) == 0) return true;
    return false;
}

static bool h2_status_unreserved(unsigned char value) { return (value >= 'a' && value <= 'z') || (value >= 'A' && value <= 'Z') || (value >= '0' && value <= '9') || value == '-' || value == '.' || value == '_' || value == '~'; }

static h2_status_result_t h2_status_buffer_url_encode(h2_status_buffer_t *buffer, h2_status_string_t value) {
    static const char hex[] = "0123456789ABCDEF";
    for (size_t i = 0u; i < value.len; ++i) {
        unsigned char current = (unsigned char)value.data[i];
        if (h2_status_unreserved(current)) { h2_status_result_t result = h2_status_buffer_append(buffer, (const char *)&value.data[i], 1u); if (result != H2_STATUS_OK) return result; }
        else { char encoded[3] = {'%', hex[current >> 4], hex[current & 15u]}; h2_status_result_t result = h2_status_buffer_append(buffer, encoded, sizeof(encoded)); if (result != H2_STATUS_OK) return result; }
    }
    return H2_STATUS_OK;
}

static h2_status_result_t h2_status_json_clone(const h2_status_client_t *client, h2_pal_json_document_t *document, const h2_pal_json_value_t *source, h2_pal_json_value_t **target) {
    h2_pal_json_type_t type = H2_PAL_JSON_TYPE_INVALID;
    h2_status_result_t result = h2_status_from_pal(h2_pal_json_value_type(client->config.json, source, &type));
    if (result != H2_STATUS_OK) return result;
    switch (type) {
    case H2_PAL_JSON_TYPE_NULL: return h2_status_from_pal(h2_pal_json_value_create_null(client->config.json, document, target));
    case H2_PAL_JSON_TYPE_BOOLEAN: { bool value = false; result = h2_status_from_pal(h2_pal_json_value_get_boolean(client->config.json, source, &value)); if (result != H2_STATUS_OK) return result; return h2_status_from_pal(h2_pal_json_value_create_boolean(client->config.json, document, value, target)); }
    case H2_PAL_JSON_TYPE_NUMBER: { double value = 0.0; result = h2_status_from_pal(h2_pal_json_value_get_number(client->config.json, source, &value)); if (result != H2_STATUS_OK) return result; return h2_status_from_pal(h2_pal_json_value_create_number(client->config.json, document, value, target)); }
    case H2_PAL_JSON_TYPE_STRING: { h2_pal_json_string_view_t value = {0}; result = h2_status_from_pal(h2_pal_json_value_get_string(client->config.json, source, &value)); if (result != H2_STATUS_OK) return result; return h2_status_from_pal(h2_pal_json_value_create_string(client->config.json, document, value.data, value.len, target)); }
    case H2_PAL_JSON_TYPE_ARRAY: { size_t count = 0u; result = h2_status_from_pal(h2_pal_json_array_size(client->config.json, source, &count)); if (result != H2_STATUS_OK || count > client->config.max_array_items) return result == H2_STATUS_OK ? H2_STATUS_ERR_NO_SPACE : result; result = h2_status_from_pal(h2_pal_json_value_create_array(client->config.json, document, target)); if (result != H2_STATUS_OK) return result; for (size_t i = 0u; i < count; ++i) { h2_pal_json_value_t *item = NULL; h2_pal_json_value_t *copy = NULL; result = h2_status_from_pal(h2_pal_json_array_get(client->config.json, source, i, &item)); if (result == H2_STATUS_OK) result = h2_status_json_clone(client, document, item, &copy); if (result == H2_STATUS_OK) result = h2_status_from_pal(h2_pal_json_array_append(client->config.json, *target, copy)); if (result != H2_STATUS_OK) return result; } return H2_STATUS_OK; }
    case H2_PAL_JSON_TYPE_OBJECT: { size_t count = 0u; result = h2_status_from_pal(h2_pal_json_object_size(client->config.json, source, &count)); if (result != H2_STATUS_OK || count > client->config.max_array_items) return result == H2_STATUS_OK ? H2_STATUS_ERR_NO_SPACE : result; result = h2_status_from_pal(h2_pal_json_value_create_object(client->config.json, document, target)); if (result != H2_STATUS_OK) return result; for (size_t i = 0u; i < count; ++i) { h2_pal_json_string_view_t key = {0}; h2_pal_json_value_t *item = NULL; h2_pal_json_value_t *copy = NULL; result = h2_status_from_pal(h2_pal_json_object_entry(client->config.json, source, i, &key, &item)); if (result == H2_STATUS_OK && key.len > client->config.max_string_bytes) result = H2_STATUS_ERR_NO_SPACE; if (result == H2_STATUS_OK) result = h2_status_json_clone(client, document, item, &copy); if (result == H2_STATUS_OK) result = h2_status_from_pal(h2_pal_json_object_set(client->config.json, *target, key.data, key.len, copy)); if (result != H2_STATUS_OK) return result; } return H2_STATUS_OK; }
    default: return H2_STATUS_ERR_JSON;
    }
}

static h2_status_result_t h2_status_json_encode(const h2_status_client_t *client, h2_pal_json_document_t *document, h2_status_json_t value, h2_pal_json_value_t **target) {
    if (!h2_status_string_valid(value, 0u, client->config.max_string_bytes)) return H2_STATUS_ERR_INVALID_ARG;
    h2_pal_json_document_t *source_document = NULL; h2_pal_json_value_t *source_root = NULL; h2_pal_json_type_t source_type = H2_PAL_JSON_TYPE_INVALID;
    h2_status_result_t result = h2_status_from_pal(h2_pal_json_document_parse(client->config.json, (const uint8_t *)value.data, value.len, NULL, &source_document));
    if (result == H2_STATUS_OK) result = h2_status_from_pal(h2_pal_json_document_root(client->config.json, source_document, &source_root));
    if (result == H2_STATUS_OK) result = h2_status_from_pal(h2_pal_json_value_type(client->config.json, source_root, &source_type));
    if (result == H2_STATUS_OK && source_type != H2_PAL_JSON_TYPE_OBJECT) result = H2_STATUS_ERR_INVALID_ARG;
    if (result == H2_STATUS_OK) result = h2_status_json_clone(client, document, source_root, target);
    (void)h2_pal_json_document_destroy(client->config.json, &source_document);
    return result;
}

static h2_status_result_t h2_status_json_decode(const h2_status_client_t *client, const h2_pal_json_value_t *source, h2_status_json_t *target) {
    h2_pal_json_type_t source_type = H2_PAL_JSON_TYPE_INVALID; h2_pal_json_document_t *document = NULL; h2_pal_json_value_t *copy = NULL; h2_pal_json_buffer_t serialized = {0};
    h2_status_result_t result = h2_status_from_pal(h2_pal_json_value_type(client->config.json, source, &source_type));
    if (result == H2_STATUS_OK && source_type != H2_PAL_JSON_TYPE_OBJECT) result = H2_STATUS_ERR_JSON;
    if (result == H2_STATUS_OK) result = h2_status_from_pal(h2_pal_json_document_create(client->config.json, NULL, &document));
    if (result == H2_STATUS_OK) result = h2_status_json_clone(client, document, source, &copy);
    if (result == H2_STATUS_OK) result = h2_status_from_pal(h2_pal_json_document_set_root(client->config.json, document, copy));
    if (result == H2_STATUS_OK) result = h2_status_from_pal(h2_pal_json_document_serialize(client->config.json, document, &serialized));
    if (result == H2_STATUS_OK) result = h2_status_copy_string(client->config.mem, (h2_pal_json_string_view_t){(const char *)serialized.data, serialized.len}, client->config.max_string_bytes, target);
    (void)h2_pal_json_buffer_release(client->config.json, &serialized);
    (void)h2_pal_json_document_destroy(client->config.json, &document);
    return result;
}


h2_status_result_t h2_status_client_init(h2_status_client_t *client, const h2_status_client_config_t *config) {
    (void)h2_status_from_pal;
    (void)h2_status_from_http;
    (void)h2_status_utf8_valid;
    (void)h2_status_string_valid;
    (void)h2_status_header_value_valid;
    (void)h2_status_http_header_valid;
    (void)h2_status_header_name_equal;
    (void)h2_status_copy_string;
    (void)h2_status_buffer_append;
    (void)h2_status_bytes_contain;
    (void)h2_status_unreserved;
    (void)h2_status_buffer_url_encode;
    (void)h2_status_json_clone;
    (void)h2_status_json_encode;
    (void)h2_status_json_decode;
    if (client == NULL || !h2_status_config_valid(config)) { return H2_STATUS_ERR_INVALID_ARG; }
    client->config = *config;
    return H2_STATUS_OK;
}

void h2_status_get_health_response_deinit(h2_status_get_health_response_t *response) {
    if (response == NULL) return;
    memset(response, 0, sizeof(*response));
}

h2_status_result_t h2_status_get_health(h2_status_client_t *client, const h2_status_get_health_request_t *request, h2_status_get_health_response_t *response) {
    if (client == NULL || request == NULL || response == NULL || !h2_status_config_valid(&client->config)) return H2_STATUS_ERR_INVALID_ARG;
    h2_status_get_health_response_deinit(response);
    response->mem = client->config.mem;
    char *url_data = h2_pal_mem_alloc(client->config.mem, client->config.max_url_bytes + 1u);
    if (url_data == NULL) return H2_STATUS_ERR_NO_MEMORY;
    h2_status_buffer_t url = {url_data, 0u, client->config.max_url_bytes};
    h2_status_result_t result = h2_status_buffer_append(&url, client->config.base_url, strlen(client->config.base_url));
    if (result != H2_STATUS_OK) goto cleanup_url;
    result = h2_status_buffer_append(&url, "/health", 7); if (result != H2_STATUS_OK) goto cleanup_url;
    if (client->config.max_extra_headers > SIZE_MAX - 0) { result = H2_STATUS_ERR_NO_SPACE; goto cleanup_url; }
    size_t header_capacity = 0 + client->config.max_extra_headers;
    if (header_capacity > SIZE_MAX / sizeof(h2_pal_http_header_t)) { result = H2_STATUS_ERR_NO_SPACE; goto cleanup_url; }
    h2_pal_http_header_t *headers = NULL;
    if (header_capacity != 0u) headers = h2_pal_mem_alloc(client->config.mem, sizeof(*headers) * header_capacity);
    if (header_capacity != 0u && headers == NULL) { result = H2_STATUS_ERR_NO_MEMORY; goto cleanup_url; }
    if (headers != NULL) memset(headers, 0, sizeof(*headers) * header_capacity);
    size_t header_count = 0u;
    char *authorization = NULL;
    if (client->config.header_callback != NULL) {
        result = client->config.header_callback(client->config.header_user, headers, header_capacity, &header_count);
        if (result != H2_STATUS_OK || header_count > header_capacity) { if (result == H2_STATUS_OK) result = H2_STATUS_ERR_INVALID_ARG; goto cleanup_headers; }
    }
    for (size_t i = 0u; i < header_count; ++i) { if (!h2_status_http_header_valid(&headers[i])) { result = H2_STATUS_ERR_INVALID_ARG; goto cleanup_headers; } }
    h2_pal_json_document_t *request_document = NULL;
    h2_pal_json_buffer_t request_body = {0};
    char *multipart_body = NULL;
    size_t multipart_body_len = 0u;
    uint8_t *response_buffer = h2_pal_mem_alloc(client->config.mem, client->config.max_response_bytes);
    if (response_buffer == NULL) { result = H2_STATUS_ERR_NO_MEMORY; goto cleanup_json; }
    h2_pal_http_request_t http_request = {
        .method = H2_PAL_HTTP_GET, .url = {url.data, url.len}, .headers = headers, .header_count = header_count,
        .body = multipart_body != NULL ? (const uint8_t *)multipart_body : request_body.data, .body_len = multipart_body != NULL ? multipart_body_len : request_body.len, .timeout_ms = client->config.timeout_ms,
        .response_buf = response_buffer, .response_buf_cap = client->config.max_response_bytes, .allocator = client->config.mem,
    };
    h2_pal_http_response_t http_response = {0};
    result = h2_status_from_http(h2_pal_http_request(client->config.http, &http_request, &http_response));
    if (result != H2_STATUS_OK) goto cleanup_http_response;
    response->status_code = http_response.status_code;
    result = (http_response.status_code >= 200 && http_response.status_code < 300) ? H2_STATUS_ERR_UNEXPECTED_STATUS : H2_STATUS_ERR_HTTP_STATUS;
    switch (http_response.status_code) {
    case 204:
        result = H2_STATUS_OK;
        break;
    default:
        break;
    }
cleanup_http_response:
    h2_pal_http_response_free(client->config.http, &http_response);
    h2_pal_mem_free(client->config.mem, response_buffer);
cleanup_json:
    h2_pal_mem_free(client->config.mem, multipart_body);
    (void)h2_pal_json_buffer_release(client->config.json, &request_body);
    (void)h2_pal_json_document_destroy(client->config.json, &request_document);
cleanup_headers:
    h2_pal_mem_free(client->config.mem, authorization);
    h2_pal_mem_free(client->config.mem, headers);
cleanup_url:
    h2_pal_mem_free(client->config.mem, url_data);
    if (result != H2_STATUS_OK && result != H2_STATUS_ERR_HTTP_STATUS) {
        const int completed_status = response->status_code;
        h2_status_get_health_response_deinit(response);
        response->status_code = completed_status;
        response->mem = client->config.mem;
    }
    return result;
}
