package(default_visibility = ["//visibility:public"])

filegroup(
    name = "lua-ferrofluid-intercom",
    srcs = [
        "data/skills/ferrofluid-intercom/SKILL.md",
        "data/skills/ferrofluid-intercom/scripts/main.lua",
        "//projects/example/apps/lua-ferrofluid-intercom/app:lua_ferrofluid_intercom",
    ],
)
