"""Build, package, serve and browser-test one app_host Web App target."""

load("@emsdk//emscripten_toolchain:wasm_rules.bzl", "wasm_cc_binary")
load(":web_board.bzl", "H2WebBoardInfo")
load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")
load("@rules_pkg//pkg:tar.bzl", "pkg_tar")
load("//tools/bazel:cc_options.bzl", "H2_C11_OPTS", "H2_WARNING_COPTS")
load("//tools/bazel:web_archive.bzl", "web_archive_browser_test", "web_archive_serve")
load("//tools/bazel/platforms:compatibility.bzl", "WEB_WASM32_ARTIFACT_COMPATIBILITY")

_DEFAULT_BOARD = Label("//libs/app_host:default_board")
_HOSTS = select({
    Label("//tools/bazel/platforms:host_linux_target_linux"): [],
    Label("//tools/bazel/platforms:host_macos_target_macos"): [],
    Label("//tools/bazel/platforms:host_windows_target_windows"): [],
    "//conditions:default": ["@platforms//:incompatible"],
})

def _c_string(value):
    return '"%s"' % value.replace("\\", "\\\\").replace('"', '\\"')

def _web_board_page_impl(ctx):
    board = ctx.attr.board[H2WebBoardInfo]
    skin_name = ctx.attr.skin or board.default_skin
    if skin_name and skin_name not in board.skins:
        fail("%s: board %s has no skin %r (skins: %s)" % (
            ctx.label,
            ctx.attr.board.label,
            skin_name,
            ", ".join(sorted(board.skins.keys())) or "none",
        ))
    skin = board.skins[skin_name] if skin_name else ctx.file._default_layout
    args = ctx.actions.args()
    args.add("--shell", ctx.file._shell)
    args.add("--layout", skin)
    args.add("--out", ctx.outputs.shell)
    ctx.actions.run(
        executable = ctx.executable._tool,
        arguments = [args],
        inputs = [ctx.file._shell, skin],
        outputs = [ctx.outputs.shell],
        mnemonic = "H2WebAppSkin",
        progress_message = "Injecting web board skin %{label}",
    )
    buttons = [
        "    {%s, %s}," % (_c_string(name), _c_string(key))
        for name, key in zip(board.button_names, board.button_keys)
    ]
    ctx.actions.write(ctx.outputs.source, "\n".join([
        "/* Generated by h2_web_app() from %s. */" % ctx.attr.board.label,
        '#include "h2_web_app_host.h"',
        "",
    ] + ([
        "static const h2_web_board_button_t k_buttons[] = {",
    ] + buttons + ["};"] if buttons else []) + [
        "const h2_web_board_t h2_web_board = {",
        "    .display_width = %d," % board.display_width,
        "    .display_height = %d," % board.display_height,
        "    .buttons = %s," % ("k_buttons" if buttons else "NULL"),
        "    .button_count = %d," % len(buttons),
        "};",
        "",
    ]))
    return [DefaultInfo(files = depset([ctx.outputs.shell, ctx.outputs.source]))]

_web_board_page = rule(
    implementation = _web_board_page_impl,
    attrs = {
        "board": attr.label(mandatory = True, providers = [H2WebBoardInfo]),
        "shell": attr.output(mandatory = True),
        "skin": attr.string(),
        "source": attr.output(mandatory = True),
        "_default_layout": attr.label(
            default = Label("//libs/app_host:default_layout.html"),
            allow_single_file = True,
        ),
        "_shell": attr.label(
            default = Label("//libs/app_host:shell.html"),
            allow_single_file = True,
        ),
        "_tool": attr.label(
            default = Label("//libs/app_host:inject_layout"),
            executable = True,
            cfg = "exec",
        ),
    },
)

def h2_web_app(
        name,
        srcs,
        deps,
        app_name,
        preload = {},
        passes = None,
        fails = [],
        test_timeout_s = 60,
        test_query = "",
        test_offline = None,
        test_webrtc_server = False,
        canvas_min = 0,
        presses = [],
        taps = [],
        clicks = [],
        evals = [],
        board = None,
        skin = None,
        copts = [],
        linkopts = []):
    """Declares `<name>` (web tar), `serve` and `browser_test` targets.

    Args:
      name: Archive target name; the tar is `<name>.web.tar`.
      srcs: The target's main.c, which calls h2_web_app_host_run().
      deps: The App library and anything main.c needs.
      app_name: Name the host prints in `H2_WEB_APP name=<app_name>` markers.
      preload: Map of file label to absolute path in the Emscripten filesystem.
      passes: Console regexes required for a pass; defaults to the host PASS.
      fails: Extra console regexes that fail the browser test.
      test_timeout_s: Seconds allowed for the browser test.
      test_query: Query string for the browser test page.
      test_offline: Optional [down, up] regexes toggling the page offline.
      test_webrtc_server: Start the WebRTC fixture for the browser test.
      canvas_min: Non-black canvas pixels the App must leave on screen.
      presses: [regex, key] pairs the browser test presses as keys.
      taps: [regex, x, y] canvas taps the browser test performs.
      clicks: [regex, css_selector] page-element clicks the browser test
        performs (pointer press and release at the element centre).
      evals: [regex, javascript] page scripts the browser test evaluates.
      board: h2_web_board() target that supplies the display size, the
        Buttons (name and key) and the skins; defaults to
        //libs/app_host:default_board (240x240, no Buttons, plain layout).
        Buttons in h2_web_app_host_config_t name a board Button; the board
        key drives it unless the config gives its own key.
      skin: Name of one of the board's skins (an unknown name fails
        analysis). Omitted: the board's default_skin, or the plain
        default_layout.html when the board has none.
      copts: Extra C compile options for srcs.
      linkopts: Extra Emscripten link options.
    """
    _web_board_page(
        name = name + "_board_page",
        board = board if board else _DEFAULT_BOARD,
        shell = name + "_shell.html",
        skin = skin or "",
        source = name + "_board.c",
    )
    shell = ":" + name + "_shell.html"
    preload_opts = []
    for label, path in preload.items():
        preload_opts += ["--preload-file", "$(location %s)@%s" % (label, path)]
    # The generated board definition is host code: caller copts stay off it.
    cc_library(
        name = name + "_board",
        srcs = [":" + name + "_board.c"],
        alwayslink = True,
        conlyopts = H2_C11_OPTS,
        copts = H2_WARNING_COPTS,
        target_compatible_with = WEB_WASM32_ARTIFACT_COMPATIBILITY,
        deps = [Label("//libs/app_host")],
    )
    cc_binary(
        name = "_wasm/index",
        srcs = srcs,
        additional_linker_inputs = [shell] + preload.keys(),
        conlyopts = H2_C11_OPTS,
        copts = H2_WARNING_COPTS + copts,
        features = ["-output_format_js"],
        linkopts = [
            "-sALLOW_MEMORY_GROWTH=1",
            "-sASSERTIONS=1",
            "-sASYNCIFY=1",
            "-sINITIAL_MEMORY=67108864",
            "-sSTACK_SIZE=1048576",
            "-sNO_EXIT_RUNTIME=1",
            "--shell-file",
            "$(location %s)" % shell,
            "--oformat=html",
        ] + preload_opts + linkopts,
        target_compatible_with = WEB_WASM32_ARTIFACT_COMPATIBILITY,
        deps = deps + [":" + name + "_board", Label("//libs/app_host")],
    )
    outputs = ["index.html", "index.js", "index.wasm"]
    if preload:
        outputs.append("index.data")
    wasm_cc_binary(
        name = name + "_wasm",
        cc_target = ":_wasm/index",
        outputs = outputs,
        target_compatible_with = _HOSTS,
    )
    pkg_tar(
        name = name,
        srcs = [":" + name + "_wasm"],
        out = name + ".web.tar",
        mode = "0644",
        portable_mtime = True,
        strip_prefix = ".",
        target_compatible_with = _HOSTS,
    )
    web_archive_serve(
        name = "serve",
        archive = ":" + name,
    )
    web_archive_browser_test(
        name = "browser_test",
        archive = ":" + name,
        passes = passes if passes != None else [
            "H2_WEB_APP name=%s result=PASS rc=0 fs=0 destroy=0" % app_name,
        ],
        fails = [
            "H2_WEB_APP name=%s result=FAIL" % app_name,
        ] + fails,
        query = test_query,
        timeout_s = test_timeout_s,
        offline = test_offline,
        webrtc_server = test_webrtc_server,
        canvas_min = canvas_min,
        presses = presses,
        taps = taps,
        clicks = clicks,
        evals = evals,
    )
