load("//tools/bazel:native_component.bzl", "firmware_native_component")

package(default_visibility = ["//visibility:public"])

firmware_native_component(
    name = "esp32p4",
    srcs = glob(
        [
            "**/*.c",
            "**/*.cc",
            "**/*.cpp",
            "**/*.cxx",
            "**/*.s",
            "**/*.S",
        ],
        allow_empty = True,
        exclude = [
            "examples/**",
            "test/**",
            "tests/**",
        ],
    ),
    hdrs = glob(
        [
            "**/*.h",
            "**/*.hh",
            "**/*.hpp",
            "**/*.hxx",
        ],
        allow_empty = True,
        exclude = [
            "examples/**",
            "test/**",
            "tests/**",
        ],
    ),
    component_directory = "boards/waveshare_esp32p4_wifi6_touch_lcd_4_3/esp32p4",
    component_name = "h2_esp_board",
    data = [
        "CMakeLists.txt",
        "idf_component.yml",
        "sdkconfig.defaults",
    ],
    tags = [
        "manual",
    ],
    deps = [
        "//libs/pal",
        "//libs/runtime",
    ],
)
