load("@rules_cc//cc:defs.bzl", "cc_library")
load("//tools/bazel:cc_options.bzl", "H2_C11_OPTS", "H2_WARNING_COPTS")

package(default_visibility = ["//projects/e2e:__subpackages__"])

cc_library(
    name = "runner",
    srcs = ["runner.c"],
    hdrs = ["runner.h"],
    conlyopts = H2_C11_OPTS,
    copts = H2_WARNING_COPTS,
    includes = ["."],
    target_compatible_with = select({
        "@platforms//os:ios": [],
        "@platforms//os:android": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = ["//projects/e2e/apps/pal-storage/app:pal_storage_e2e"],
)

exports_files(["run_mobile.py"])
