load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "partial_update_smoke",
    srcs = glob(
        [
            "**/*.c",
            "**/*.cc",
            "**/*.cpp",
            "**/*.cxx",
            "**/*.s",
            "**/*.S",
        ],
        allow_empty = True,
        exclude = [
            "examples/**",
            "test/**",
            "tests/**",
        ],
    ),
    hdrs = glob(
        [
            "**/*.h",
            "**/*.hh",
            "**/*.hpp",
            "**/*.hxx",
        ],
        allow_empty = True,
        exclude = [
            "examples/**",
            "test/**",
            "tests/**",
        ],
    ),
    data = glob(
        ["**"],
        allow_empty = True,
        exclude = [
            "BUILD.bazel",
            "**/*.c",
            "**/*.cc",
            "**/*.cpp",
            "**/*.cxx",
            "**/*.s",
            "**/*.S",
            "**/*.h",
            "**/*.hh",
            "**/*.hpp",
            "**/*.hxx",
            "examples/**",
            "test/**",
            "tests/**",
        ],
    ),
    includes = ["include"],
    tags = [
        "manual",
    ],
    deps = [
        "//libs/pal",
        "//libs/runtime",
    ],
)
