load("//tools/bazel:native_component.bzl", "firmware_native_component")

package(default_visibility = ["//visibility:public"])

exports_files([
    "partition.csv",
    "sdkconfig.defaults",
])

firmware_native_component(
    name = "esp32p4",
    srcs = ["src/h2_chip_board.c"],
    hdrs = ["include/h2_chip_board.h"],
    component_directory = "boards/esp32p4_chip/esp32p4",
    component_name = "h2_chip_board",
    data = [
        "CMakeLists.txt",
        "sdkconfig.defaults",
    ],
    tags = ["manual"],
)
