#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#define GPIO_DEFAULT_DEV_CONFIG  \
{\
    {GPIO_0, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_UART1_TXD, GPIO_IO_DISABLE, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
    {GPIO_1, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_UART1_RXD, GPIO_IO_DISABLE, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
    {GPIO_2,  GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_SDIO_HOST_CLK, GPIO_IO_DISABLE, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
    {GPIO_3,  GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_SDIO_HOST_CMD, GPIO_IO_DISABLE, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
    {GPIO_4,  GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_SDIO_HOST_DATA0, GPIO_IO_DISABLE, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
    {GPIO_5,  GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_INVALID, GPIO_INPUT_ENABLE, GPIO_PULL_UP_EN, GPIO_INT_ENABLE, GPIO_INT_TYPE_FALLING_EDGE, GPIO_LOW_POWER_KEEP_INPUT_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
    {GPIO_13, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE, GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
}

#ifdef __cplusplus
}
#endif

/* PWM1 drives the board LCD backlight on GPIO7. The SDK default GPIO19
 * belongs to LCD_R7 and must never be remapped by a brightness request. */
#define GPIO_PWM_MAP_TABLE { \
    {{GPIO_18, GPIO_DEV_PWM0}, {GPIO_7, GPIO_DEV_PWM1}, \
     {GPIO_8, GPIO_DEV_PWM2}, {GPIO_9, GPIO_DEV_PWM3}, \
     {GPIO_24, GPIO_DEV_PWM4}, {GPIO_25, GPIO_DEV_PWM5}}, \
    {{GPIO_32, GPIO_DEV_PWM6}, {GPIO_33, GPIO_DEV_PWM7}, \
     {GPIO_34, GPIO_DEV_PWM8}, {GPIO_35, GPIO_DEV_PWM9}, \
     {GPIO_36, GPIO_DEV_PWM10}, {GPIO_37, GPIO_DEV_PWM11}} \
}
