#ifndef H2_JIELI_AC791N_VENDOR_BLE_SMOKE_APP_CONFIG_H_
#define H2_JIELI_AC791N_VENDOR_BLE_SMOKE_APP_CONFIG_H_

/* JieLi demo_ble configuration, with only the physical Flash size changed to
 * the board's canonical H2Loader layout. */
#define __FLASH_SIZE__ (8 * 1024 * 1024)
#define CONFIG_NO_SDRAM_ENABLE
#define __SDRAM_SIZE__ (0 * 1024 * 1024)

#define CONFIG_DEBUG_ENABLE
#define RTOS_STACK_CHECK_ENABLE

#define TCFG_LOWPOWER_BTOSC_DISABLE 0
#define CONFIG_LOW_POWER_ENABLE
#define TCFG_LOWPOWER_LOWPOWER_SEL                                             \
  (RF_SLEEP_EN | SYS_SLEEP_EN | RF_FORCE_SYS_SLEEP_EN | SYS_SLEEP_BY_IDLE)
#define TCFG_LOWPOWER_VDDIOM_LEVEL VDDIOM_VOL_32V
#ifdef CONFIG_RTC_ENABLE
#define TCFG_LOWPOWER_VDDIOW_LEVEL VDDIOW_VOL_32V
#else
#define TCFG_LOWPOWER_VDDIOW_LEVEL VDDIOW_VOL_21V
#endif
#define VDC14_VOL_SEL_LEVEL VDC14_VOL_SEL_140V
#define SYSVDD_VOL_SEL_LEVEL SYSVDD_VOL_SEL_126V

#ifdef CONFIG_BT_ENABLE
#define CONFIG_BT_RX_BUFF_SIZE 0
#define CONFIG_BT_TX_BUFF_SIZE 0
#define TCFG_USER_BLE_ENABLE 1
#define TCFG_USER_BT_CLASSIC_ENABLE 0
#define BT_NET_HID_EN 0
#define TRANS_DATA_EN 1
#define BT_NET_CENTRAL_EN 0
#define TRANS_MULTI_BLE_EN 0
#define CONFIG_BLE_MESH_ENABLE 0
#define APP_NONCONN_24G 0
#define TCFG_BLE_SECURITY_EN 1
#endif

#define TCFG_ADKEY_ENABLE 0

#if !defined(CONFIG_DEBUG_ENABLE) || defined(CONFIG_LIB_DEBUG_DISABLE)
#define LIB_DEBUG 0
#else
#define LIB_DEBUG 1
#endif
#define CONFIG_DEBUG_LIB(value) ((value) & LIB_DEBUG)

#endif
