#ifndef H2_RUNTIME_INPUT_IMU_DEFS_H
#define H2_RUNTIME_INPUT_IMU_DEFS_H

#ifndef H2_RUNTIME_IMU_SHAKE_THRESHOLD_MG
#define H2_RUNTIME_IMU_SHAKE_THRESHOLD_MG 1500
#endif

#ifndef H2_RUNTIME_IMU_SHAKE_MIN_DURATION_MS
#define H2_RUNTIME_IMU_SHAKE_MIN_DURATION_MS 100u
#endif

#ifndef H2_RUNTIME_IMU_TILT_THRESHOLD_MG
#define H2_RUNTIME_IMU_TILT_THRESHOLD_MG 350
#endif

#ifndef H2_RUNTIME_IMU_TILT_DEBOUNCE_MS
#define H2_RUNTIME_IMU_TILT_DEBOUNCE_MS 200u
#endif

#ifndef H2_RUNTIME_IMU_FREE_FALL_THRESHOLD_MG
#define H2_RUNTIME_IMU_FREE_FALL_THRESHOLD_MG 250
#endif

#ifndef H2_RUNTIME_IMU_FREE_FALL_MIN_DURATION_MS
#define H2_RUNTIME_IMU_FREE_FALL_MIN_DURATION_MS 120u
#endif

#ifndef H2_RUNTIME_IMU_FLIP_GYRO_THRESHOLD_MDPS
#define H2_RUNTIME_IMU_FLIP_GYRO_THRESHOLD_MDPS 120000
#endif

#ifndef H2_RUNTIME_IMU_FLIP_DEBOUNCE_MS
#define H2_RUNTIME_IMU_FLIP_DEBOUNCE_MS 300u
#endif

#ifndef H2_RUNTIME_IMU_POLL_INTERVAL_MS
#define H2_RUNTIME_IMU_POLL_INTERVAL_MS 20u
#endif

#endif
