// Generated by //tools/openapi_codegen. DO NOT EDIT.
#ifndef H2_FIXTURE_API_H
#define H2_FIXTURE_API_H

#include "h2/pal/application/h2_pal_http.h"
#include "h2/pal/os/h2_pal_json.h"
#include "h2/pal/os/h2_pal_mem.h"

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum h2_fixture_result {
    H2_FIXTURE_OK = 0,
    H2_FIXTURE_ERR_INVALID_ARG = -1,
    H2_FIXTURE_ERR_NO_MEMORY = -2,
    H2_FIXTURE_ERR_NO_SPACE = -3,
    H2_FIXTURE_ERR_HTTP = -4,
    H2_FIXTURE_ERR_HTTP_STATUS = -5,
    H2_FIXTURE_ERR_UNEXPECTED_STATUS = -6,
    H2_FIXTURE_ERR_JSON = -7,
    H2_FIXTURE_ERR_UNSUPPORTED = -8
} h2_fixture_result_t;

#define H2_FIXTURE_MAX_URL_BYTES ((size_t)64u * 1024u)
#define H2_FIXTURE_MAX_RESPONSE_BYTES H2_PAL_JSON_DEFAULT_MAX_DOCUMENT_BYTES

#define H2_FIXTURE_OPERATION_COUNT 3u

/** UTF-8 byte view: borrowed in requests; response views are owned by their response. */
typedef struct h2_fixture_string {
    const char *data;
    size_t len;
} h2_fixture_string_t;

/** Opaque JSON value encoded as one complete UTF-8 JSON document. */
typedef h2_fixture_string_t h2_fixture_json_t;

/** Borrowed binary byte view used by multipart request fields. */
typedef struct h2_fixture_bytes {
    const uint8_t *data;
    size_t len;
} h2_fixture_bytes_t;

typedef struct h2_fixture_a h2_fixture_a_t;
typedef struct h2_fixture_b h2_fixture_b_t;
typedef struct h2_fixture_error h2_fixture_error_t;
typedef struct h2_fixture_list_items_response_200_body h2_fixture_list_items_response_200_body_t;
typedef struct h2_fixture_pet h2_fixture_pet_t;
typedef struct h2_fixture_upload_request_body h2_fixture_upload_request_body_t;
typedef struct h2_fixture_value h2_fixture_value_t;
typedef struct h2_fixture_value_choice h2_fixture_value_choice_t;

#define H2_FIXTURE_PET_KIND_0 "cat"
#define H2_FIXTURE_PET_KIND_1 "dog"

struct h2_fixture_a {
    h2_fixture_string_t a;
};

struct h2_fixture_b {
    bool b;
};

struct h2_fixture_error {
    h2_fixture_string_t message;
};

struct h2_fixture_list_items_response_200_body {
    struct {
        h2_fixture_value_t * *items;
        size_t count;
    } value;
};

struct h2_fixture_pet {
    bool active;
    int32_t age;
    h2_fixture_string_t kind;
    h2_fixture_string_t name;
    struct {
        h2_fixture_string_t *items;
        size_t count;
    } tags;
};

struct h2_fixture_upload_request_body {
    h2_fixture_string_t dir;
    h2_fixture_bytes_t file;
};

struct h2_fixture_value {
    bool has_choice;
    h2_fixture_value_choice_t * choice;
    bool has_metadata;
    h2_fixture_json_t metadata;
    bool has_name;
    bool is_name_null;
    h2_fixture_string_t name;
};

typedef enum h2_fixture_value_choice_kind {
    H2_FIXTURE_VALUE_CHOICE_NONE = 0,
    H2_FIXTURE_VALUE_CHOICE_A = 1,
    H2_FIXTURE_VALUE_CHOICE_B = 2,
} h2_fixture_value_choice_kind_t;

struct h2_fixture_value_choice {
    h2_fixture_value_choice_kind_t kind;
    union {
        h2_fixture_a_t * a;
        h2_fixture_b_t * b;
    } value;
};

/**
 * Synchronously edit request headers before encoding and transport.
 *
 * Entries below `*in_out_count` are initialized; remaining entries through
 * `capacity` are zeroed and available for additions. The callback must leave
 * `*in_out_count <= capacity`. Any name/value spans it supplies are borrowed
 * by the operation and must remain valid until that synchronous call returns.
 */
typedef h2_fixture_result_t (*h2_fixture_header_callback_t)(
    void *user,
    h2_pal_http_header_t *headers,
    size_t capacity,
    size_t *in_out_count);

/** Borrowed configuration. All pointed-to capabilities and strings must outlive calls. */
typedef struct h2_fixture_client_config {
    const h2_pal_http_api_t *http;
    const h2_pal_json_api_t *json;
    const h2_pal_mem_api_t *mem;
    const char *base_url;
    size_t max_url_bytes;
    int timeout_ms;
    size_t max_response_bytes;
    size_t max_request_bytes;
    size_t max_string_bytes;
    size_t max_array_items;
    h2_fixture_string_t bearer_token;
    h2_fixture_header_callback_t header_callback;
    void *header_user;
    size_t max_extra_headers;
} h2_fixture_client_config_t;

typedef struct h2_fixture_client {
    h2_fixture_client_config_t config;
} h2_fixture_client_t;

/** Initialize a client by borrowing all PAL capabilities and configuration strings. */
h2_fixture_result_t h2_fixture_client_init(h2_fixture_client_t *client, const h2_fixture_client_config_t *config);

typedef struct h2_fixture_list_items_request {
    bool has_tag;
    struct {
        h2_fixture_string_t *items;
        size_t count;
    } tag;
} h2_fixture_list_items_request_t;

/** Unique-owned response. Zero-initialize before first use; do not copy while live. */
typedef struct h2_fixture_list_items_response {
    int status_code;
    const h2_pal_mem_api_t *mem;
    bool has_body;
    union {
        h2_fixture_list_items_response_200_body_t status_200;
    } body;
} h2_fixture_list_items_response_t;

/** Execute synchronously. Request data is borrowed; any previous response value is released before reuse. */
h2_fixture_result_t h2_fixture_list_items(
    h2_fixture_client_t *client,
    const h2_fixture_list_items_request_t *request,
    h2_fixture_list_items_response_t *response);
/** Release all response-owned memory. Safe on a zeroed response. */
void h2_fixture_list_items_response_deinit(h2_fixture_list_items_response_t *response);

typedef struct h2_fixture_update_pet_request {
    h2_fixture_string_t x_device_id;
    h2_fixture_string_t pet_id;
    bool has_verbose;
    bool verbose;
    const h2_fixture_pet_t *body;
} h2_fixture_update_pet_request_t;

/** Unique-owned response. Zero-initialize before first use; do not copy while live. */
typedef struct h2_fixture_update_pet_response {
    int status_code;
    const h2_pal_mem_api_t *mem;
    bool has_body;
    union {
        h2_fixture_pet_t status_200;
        h2_fixture_error_t status_400;
    } body;
    bool has_x_trace;
    h2_fixture_string_t x_trace;
} h2_fixture_update_pet_response_t;

/** Execute synchronously. Request data is borrowed; any previous response value is released before reuse. */
h2_fixture_result_t h2_fixture_update_pet(
    h2_fixture_client_t *client,
    const h2_fixture_update_pet_request_t *request,
    h2_fixture_update_pet_response_t *response);
/** Release all response-owned memory. Safe on a zeroed response. */
void h2_fixture_update_pet_response_deinit(h2_fixture_update_pet_response_t *response);

typedef struct h2_fixture_upload_request {
    const h2_fixture_upload_request_body_t *body;
} h2_fixture_upload_request_t;

/** Unique-owned response. Zero-initialize before first use; do not copy while live. */
typedef struct h2_fixture_upload_response {
    int status_code;
    const h2_pal_mem_api_t *mem;
} h2_fixture_upload_response_t;

/** Execute synchronously. Request data is borrowed; any previous response value is released before reuse. */
h2_fixture_result_t h2_fixture_upload(
    h2_fixture_client_t *client,
    const h2_fixture_upload_request_t *request,
    h2_fixture_upload_response_t *response);
/** Release all response-owned memory. Safe on a zeroed response. */
void h2_fixture_upload_response_deinit(h2_fixture_upload_response_t *response);

#ifdef __cplusplus
}
#endif

#endif  // H2_FIXTURE_API_H
