// Generated by //tools/openapi_codegen. DO NOT EDIT.
#include "h2_fixture_api.h"

#include <float.h>
#include <math.h>
#include <stdio.h>
#include <string.h>

static h2_fixture_result_t h2_fixture_from_pal(h2_pal_result_t result) {
    if (result == H2_PAL_OK) return H2_FIXTURE_OK;
    if (result == H2_PAL_ERR_NO_MEMORY) return H2_FIXTURE_ERR_NO_MEMORY;
    if (result == H2_PAL_ERR_NO_SPACE) return H2_FIXTURE_ERR_NO_SPACE;
    if (result == H2_PAL_ERR_UNSUPPORTED) return H2_FIXTURE_ERR_UNSUPPORTED;
    return H2_FIXTURE_ERR_JSON;
}

static h2_fixture_result_t h2_fixture_from_http(int result) {
    if (result == H2_PAL_OK) return H2_FIXTURE_OK;
    if (result == H2_PAL_ERR_NO_MEMORY) return H2_FIXTURE_ERR_NO_MEMORY;
    if (result == H2_PAL_ERR_NO_SPACE) return H2_FIXTURE_ERR_NO_SPACE;
    if (result == H2_PAL_ERR_UNSUPPORTED) return H2_FIXTURE_ERR_UNSUPPORTED;
    return H2_FIXTURE_ERR_HTTP;
}

static bool h2_fixture_utf8_valid(const char *data, size_t len) {
    size_t i = 0u;
    while (i < len) {
        const unsigned char first = (unsigned char)data[i++];
        if (first == 0u) return false;
        if (first < 0x80u) continue;
        size_t remaining = 0u;
        unsigned int codepoint = 0u;
        unsigned int minimum = 0u;
        if (first >= 0xC2u && first <= 0xDFu) { remaining = 1u; codepoint = first & 0x1Fu; minimum = 0x80u; }
        else if (first >= 0xE0u && first <= 0xEFu) { remaining = 2u; codepoint = first & 0x0Fu; minimum = 0x800u; }
        else if (first >= 0xF0u && first <= 0xF4u) { remaining = 3u; codepoint = first & 0x07u; minimum = 0x10000u; }
        else return false;
        if (remaining > len - i) return false;
        while (remaining-- != 0u) {
            const unsigned char next = (unsigned char)data[i++];
            if ((next & 0xC0u) != 0x80u) return false;
            codepoint = (codepoint << 6) | (next & 0x3Fu);
        }
        if (codepoint < minimum || codepoint > 0x10FFFFu || (codepoint >= 0xD800u && codepoint <= 0xDFFFu)) return false;
    }
    return true;
}

static bool h2_fixture_string_valid(h2_fixture_string_t value, size_t minimum, size_t maximum) {
    return value.len >= minimum && value.len <= maximum && (value.data != NULL || value.len == 0u) && h2_fixture_utf8_valid(value.data, value.len);
}

static bool h2_fixture_header_value_valid(h2_fixture_string_t value, size_t minimum, size_t maximum) {
    if (!h2_fixture_string_valid(value, minimum, maximum)) return false;
    for (size_t i = 0u; i < value.len; ++i) if (value.data[i] == '\r' || value.data[i] == '\n') return false;
    return true;
}

static bool h2_fixture_http_header_valid(const h2_pal_http_header_t *header) {
    if (header == NULL || header->name.data == NULL || header->name.len == 0u || (header->value.data == NULL && header->value.len != 0u)) return false;
    for (size_t i = 0u; i < header->name.len; ++i) {
        const unsigned char value = (unsigned char)header->name.data[i];
        const bool alphanumeric = (value >= 'a' && value <= 'z') || (value >= 'A' && value <= 'Z') || (value >= '0' && value <= '9');
        const bool symbol = value == '!' || value == '#' || value == '$' || value == '%' || value == '&' || value == '\'' || value == '*' || value == '+' || value == '-' || value == '.' || value == '^' || value == '_' || value == '`' || value == '|' || value == '~';
        if (!alphanumeric && !symbol) return false;
    }
    for (size_t i = 0u; i < header->value.len; ++i) {
        const unsigned char value = (unsigned char)header->value.data[i];
        if ((value < 0x20u && value != '\t') || value == 0x7Fu) return false;
    }
    return true;
}

static bool h2_fixture_header_name_equal(h2_pal_http_str_t value, const char *expected, size_t expected_len) {
    if (value.len != expected_len || (value.data == NULL && value.len != 0u)) return false;
    for (size_t i = 0u; i < value.len; ++i) { unsigned char left = (unsigned char)value.data[i]; unsigned char right = (unsigned char)expected[i]; if (left >= 'A' && left <= 'Z') left = (unsigned char)(left + ('a' - 'A')); if (right >= 'A' && right <= 'Z') right = (unsigned char)(right + ('a' - 'A')); if (left != right) return false; }
    return true;
}

static bool h2_fixture_config_valid(const h2_fixture_client_config_t *config) {
    if (config == NULL || config->http == NULL || config->http->vtable == NULL || config->http->vtable->request == NULL || config->http->vtable->response_free == NULL || config->json == NULL || config->json->vtable == NULL || config->mem == NULL || config->mem->vtable == NULL || config->mem->vtable->alloc == NULL || config->mem->vtable->realloc == NULL || config->mem->vtable->free == NULL || config->base_url == NULL || config->base_url[0] == '\0') return false;
    if (config->max_url_bytes == 0u || config->max_url_bytes > H2_FIXTURE_MAX_URL_BYTES || config->max_response_bytes == 0u || config->max_response_bytes > H2_FIXTURE_MAX_RESPONSE_BYTES) return false;
    if (config->max_request_bytes == 0u || config->max_request_bytes == SIZE_MAX || config->max_string_bytes == 0u || config->max_string_bytes == SIZE_MAX || config->max_array_items == 0u) return false;
    if ((config->bearer_token.data == NULL && config->bearer_token.len != 0u) || !h2_fixture_utf8_valid(config->bearer_token.data, config->bearer_token.len)) return false;
    const h2_pal_json_vtable_t *json = config->json->vtable;
    return json->document_parse != NULL && json->document_create != NULL && json->document_destroy != NULL && json->document_root != NULL && json->document_set_root != NULL && json->value_create_null != NULL && json->value_create_boolean != NULL && json->value_create_number != NULL && json->value_create_string != NULL && json->value_create_array != NULL && json->value_create_object != NULL && json->value_type != NULL && json->value_get_boolean != NULL && json->value_get_number != NULL && json->value_get_string != NULL && json->array_size != NULL && json->array_get != NULL && json->array_append != NULL && json->object_size != NULL && json->object_entry != NULL && json->object_get != NULL && json->object_set != NULL && json->document_serialize != NULL && json->buffer_release != NULL;
}

static h2_fixture_result_t h2_fixture_copy_string(const h2_pal_mem_api_t *mem, h2_pal_json_string_view_t source, size_t maximum, h2_fixture_string_t *output) {
    if (source.len > maximum) return H2_FIXTURE_ERR_NO_SPACE;
    char *copy = h2_pal_mem_alloc(mem, source.len + 1u);
    if (copy == NULL) return H2_FIXTURE_ERR_NO_MEMORY;
    if (source.len != 0u) memcpy(copy, source.data, source.len);
    copy[source.len] = '\0';
    output->data = copy;
    output->len = source.len;
    return H2_FIXTURE_OK;
}

typedef struct h2_fixture_buffer { char *data; size_t len; size_t cap; } h2_fixture_buffer_t;

static h2_fixture_result_t h2_fixture_buffer_append(h2_fixture_buffer_t *buffer, const char *data, size_t len) {
    if (len > buffer->cap - buffer->len) return H2_FIXTURE_ERR_NO_SPACE;
    if (len != 0u) memcpy(buffer->data + buffer->len, data, len);
    buffer->len += len;
    buffer->data[buffer->len] = '\0';
    return H2_FIXTURE_OK;
}

static bool h2_fixture_bytes_contain(const void *data, size_t data_len, const char *needle, size_t needle_len) {
    if (needle_len == 0u) return true;
    if (data == NULL || needle == NULL || needle_len > data_len) return false;
    const uint8_t *bytes = data;
    for (size_t offset = 0u; offset <= data_len - needle_len; ++offset) if (memcmp(bytes + offset, needle, needle_len) == 0) return true;
    return false;
}

static bool h2_fixture_unreserved(unsigned char value) { return (value >= 'a' && value <= 'z') || (value >= 'A' && value <= 'Z') || (value >= '0' && value <= '9') || value == '-' || value == '.' || value == '_' || value == '~'; }

static h2_fixture_result_t h2_fixture_buffer_url_encode(h2_fixture_buffer_t *buffer, h2_fixture_string_t value) {
    static const char hex[] = "0123456789ABCDEF";
    for (size_t i = 0u; i < value.len; ++i) {
        unsigned char current = (unsigned char)value.data[i];
        if (h2_fixture_unreserved(current)) { h2_fixture_result_t result = h2_fixture_buffer_append(buffer, (const char *)&value.data[i], 1u); if (result != H2_FIXTURE_OK) return result; }
        else { char encoded[3] = {'%', hex[current >> 4], hex[current & 15u]}; h2_fixture_result_t result = h2_fixture_buffer_append(buffer, encoded, sizeof(encoded)); if (result != H2_FIXTURE_OK) return result; }
    }
    return H2_FIXTURE_OK;
}

static h2_fixture_result_t h2_fixture_json_clone(const h2_fixture_client_t *client, h2_pal_json_document_t *document, const h2_pal_json_value_t *source, h2_pal_json_value_t **target) {
    h2_pal_json_type_t type = H2_PAL_JSON_TYPE_INVALID;
    h2_fixture_result_t result = h2_fixture_from_pal(h2_pal_json_value_type(client->config.json, source, &type));
    if (result != H2_FIXTURE_OK) return result;
    switch (type) {
    case H2_PAL_JSON_TYPE_NULL: return h2_fixture_from_pal(h2_pal_json_value_create_null(client->config.json, document, target));
    case H2_PAL_JSON_TYPE_BOOLEAN: { bool value = false; result = h2_fixture_from_pal(h2_pal_json_value_get_boolean(client->config.json, source, &value)); if (result != H2_FIXTURE_OK) return result; return h2_fixture_from_pal(h2_pal_json_value_create_boolean(client->config.json, document, value, target)); }
    case H2_PAL_JSON_TYPE_NUMBER: { double value = 0.0; result = h2_fixture_from_pal(h2_pal_json_value_get_number(client->config.json, source, &value)); if (result != H2_FIXTURE_OK) return result; return h2_fixture_from_pal(h2_pal_json_value_create_number(client->config.json, document, value, target)); }
    case H2_PAL_JSON_TYPE_STRING: { h2_pal_json_string_view_t value = {0}; result = h2_fixture_from_pal(h2_pal_json_value_get_string(client->config.json, source, &value)); if (result != H2_FIXTURE_OK) return result; return h2_fixture_from_pal(h2_pal_json_value_create_string(client->config.json, document, value.data, value.len, target)); }
    case H2_PAL_JSON_TYPE_ARRAY: { size_t count = 0u; result = h2_fixture_from_pal(h2_pal_json_array_size(client->config.json, source, &count)); if (result != H2_FIXTURE_OK || count > client->config.max_array_items) return result == H2_FIXTURE_OK ? H2_FIXTURE_ERR_NO_SPACE : result; result = h2_fixture_from_pal(h2_pal_json_value_create_array(client->config.json, document, target)); if (result != H2_FIXTURE_OK) return result; for (size_t i = 0u; i < count; ++i) { h2_pal_json_value_t *item = NULL; h2_pal_json_value_t *copy = NULL; result = h2_fixture_from_pal(h2_pal_json_array_get(client->config.json, source, i, &item)); if (result == H2_FIXTURE_OK) result = h2_fixture_json_clone(client, document, item, &copy); if (result == H2_FIXTURE_OK) result = h2_fixture_from_pal(h2_pal_json_array_append(client->config.json, *target, copy)); if (result != H2_FIXTURE_OK) return result; } return H2_FIXTURE_OK; }
    case H2_PAL_JSON_TYPE_OBJECT: { size_t count = 0u; result = h2_fixture_from_pal(h2_pal_json_object_size(client->config.json, source, &count)); if (result != H2_FIXTURE_OK || count > client->config.max_array_items) return result == H2_FIXTURE_OK ? H2_FIXTURE_ERR_NO_SPACE : result; result = h2_fixture_from_pal(h2_pal_json_value_create_object(client->config.json, document, target)); if (result != H2_FIXTURE_OK) return result; for (size_t i = 0u; i < count; ++i) { h2_pal_json_string_view_t key = {0}; h2_pal_json_value_t *item = NULL; h2_pal_json_value_t *copy = NULL; result = h2_fixture_from_pal(h2_pal_json_object_entry(client->config.json, source, i, &key, &item)); if (result == H2_FIXTURE_OK && key.len > client->config.max_string_bytes) result = H2_FIXTURE_ERR_NO_SPACE; if (result == H2_FIXTURE_OK) result = h2_fixture_json_clone(client, document, item, &copy); if (result == H2_FIXTURE_OK) result = h2_fixture_from_pal(h2_pal_json_object_set(client->config.json, *target, key.data, key.len, copy)); if (result != H2_FIXTURE_OK) return result; } return H2_FIXTURE_OK; }
    default: return H2_FIXTURE_ERR_JSON;
    }
}

static h2_fixture_result_t h2_fixture_json_encode(const h2_fixture_client_t *client, h2_pal_json_document_t *document, h2_fixture_json_t value, h2_pal_json_value_t **target) {
    if (!h2_fixture_string_valid(value, 0u, client->config.max_string_bytes)) return H2_FIXTURE_ERR_INVALID_ARG;
    h2_pal_json_document_t *source_document = NULL; h2_pal_json_value_t *source_root = NULL; h2_pal_json_type_t source_type = H2_PAL_JSON_TYPE_INVALID;
    h2_fixture_result_t result = h2_fixture_from_pal(h2_pal_json_document_parse(client->config.json, (const uint8_t *)value.data, value.len, NULL, &source_document));
    if (result == H2_FIXTURE_OK) result = h2_fixture_from_pal(h2_pal_json_document_root(client->config.json, source_document, &source_root));
    if (result == H2_FIXTURE_OK) result = h2_fixture_from_pal(h2_pal_json_value_type(client->config.json, source_root, &source_type));
    if (result == H2_FIXTURE_OK && source_type != H2_PAL_JSON_TYPE_OBJECT) result = H2_FIXTURE_ERR_INVALID_ARG;
    if (result == H2_FIXTURE_OK) result = h2_fixture_json_clone(client, document, source_root, target);
    (void)h2_pal_json_document_destroy(client->config.json, &source_document);
    return result;
}

static h2_fixture_result_t h2_fixture_json_decode(const h2_fixture_client_t *client, const h2_pal_json_value_t *source, h2_fixture_json_t *target) {
    h2_pal_json_type_t source_type = H2_PAL_JSON_TYPE_INVALID; h2_pal_json_document_t *document = NULL; h2_pal_json_value_t *copy = NULL; h2_pal_json_buffer_t serialized = {0};
    h2_fixture_result_t result = h2_fixture_from_pal(h2_pal_json_value_type(client->config.json, source, &source_type));
    if (result == H2_FIXTURE_OK && source_type != H2_PAL_JSON_TYPE_OBJECT) result = H2_FIXTURE_ERR_JSON;
    if (result == H2_FIXTURE_OK) result = h2_fixture_from_pal(h2_pal_json_document_create(client->config.json, NULL, &document));
    if (result == H2_FIXTURE_OK) result = h2_fixture_json_clone(client, document, source, &copy);
    if (result == H2_FIXTURE_OK) result = h2_fixture_from_pal(h2_pal_json_document_set_root(client->config.json, document, copy));
    if (result == H2_FIXTURE_OK) result = h2_fixture_from_pal(h2_pal_json_document_serialize(client->config.json, document, &serialized));
    if (result == H2_FIXTURE_OK) result = h2_fixture_copy_string(client->config.mem, (h2_pal_json_string_view_t){(const char *)serialized.data, serialized.len}, client->config.max_string_bytes, target);
    (void)h2_pal_json_buffer_release(client->config.json, &serialized);
    (void)h2_pal_json_document_destroy(client->config.json, &document);
    return result;
}

static void h2_fixture_a_deinit(const h2_pal_mem_api_t *mem, h2_fixture_a_t *value);
static h2_fixture_result_t h2_fixture_a_encode(const h2_fixture_client_t *client, h2_pal_json_document_t *document, const h2_fixture_a_t *value, h2_pal_json_value_t **output);
static h2_fixture_result_t h2_fixture_a_decode(const h2_fixture_client_t *client, const h2_pal_json_value_t *input, h2_fixture_a_t *output);
static void h2_fixture_b_deinit(const h2_pal_mem_api_t *mem, h2_fixture_b_t *value);
static h2_fixture_result_t h2_fixture_b_encode(const h2_fixture_client_t *client, h2_pal_json_document_t *document, const h2_fixture_b_t *value, h2_pal_json_value_t **output);
static h2_fixture_result_t h2_fixture_b_decode(const h2_fixture_client_t *client, const h2_pal_json_value_t *input, h2_fixture_b_t *output);
static void h2_fixture_error_deinit(const h2_pal_mem_api_t *mem, h2_fixture_error_t *value);
static h2_fixture_result_t h2_fixture_error_encode(const h2_fixture_client_t *client, h2_pal_json_document_t *document, const h2_fixture_error_t *value, h2_pal_json_value_t **output);
static h2_fixture_result_t h2_fixture_error_decode(const h2_fixture_client_t *client, const h2_pal_json_value_t *input, h2_fixture_error_t *output);
static void h2_fixture_list_items_response_200_body_deinit(const h2_pal_mem_api_t *mem, h2_fixture_list_items_response_200_body_t *value);
static h2_fixture_result_t h2_fixture_list_items_response_200_body_encode(const h2_fixture_client_t *client, h2_pal_json_document_t *document, const h2_fixture_list_items_response_200_body_t *value, h2_pal_json_value_t **output);
static h2_fixture_result_t h2_fixture_list_items_response_200_body_decode(const h2_fixture_client_t *client, const h2_pal_json_value_t *input, h2_fixture_list_items_response_200_body_t *output);
static void h2_fixture_pet_deinit(const h2_pal_mem_api_t *mem, h2_fixture_pet_t *value);
static h2_fixture_result_t h2_fixture_pet_encode(const h2_fixture_client_t *client, h2_pal_json_document_t *document, const h2_fixture_pet_t *value, h2_pal_json_value_t **output);
static h2_fixture_result_t h2_fixture_pet_decode(const h2_fixture_client_t *client, const h2_pal_json_value_t *input, h2_fixture_pet_t *output);
static void h2_fixture_upload_request_body_deinit(const h2_pal_mem_api_t *mem, h2_fixture_upload_request_body_t *value);
static h2_fixture_result_t h2_fixture_upload_request_body_encode(const h2_fixture_client_t *client, h2_pal_json_document_t *document, const h2_fixture_upload_request_body_t *value, h2_pal_json_value_t **output);
static h2_fixture_result_t h2_fixture_upload_request_body_decode(const h2_fixture_client_t *client, const h2_pal_json_value_t *input, h2_fixture_upload_request_body_t *output);
static void h2_fixture_value_deinit(const h2_pal_mem_api_t *mem, h2_fixture_value_t *value);
static h2_fixture_result_t h2_fixture_value_encode(const h2_fixture_client_t *client, h2_pal_json_document_t *document, const h2_fixture_value_t *value, h2_pal_json_value_t **output);
static h2_fixture_result_t h2_fixture_value_decode(const h2_fixture_client_t *client, const h2_pal_json_value_t *input, h2_fixture_value_t *output);
static void h2_fixture_value_choice_deinit(const h2_pal_mem_api_t *mem, h2_fixture_value_choice_t *value);
static h2_fixture_result_t h2_fixture_value_choice_encode(const h2_fixture_client_t *client, h2_pal_json_document_t *document, const h2_fixture_value_choice_t *value, h2_pal_json_value_t **output);
static h2_fixture_result_t h2_fixture_value_choice_decode(const h2_fixture_client_t *client, const h2_pal_json_value_t *input, h2_fixture_value_choice_t *output);

static void h2_fixture_a_deinit(const h2_pal_mem_api_t *mem, h2_fixture_a_t *value) {
    if (mem == NULL || value == NULL) return;
    h2_pal_mem_free(mem, (void *)value->a.data);
    memset(value, 0, sizeof(*value));
}

static h2_fixture_result_t h2_fixture_a_encode(const h2_fixture_client_t *client, h2_pal_json_document_t *document, const h2_fixture_a_t *value, h2_pal_json_value_t **output) {
    if (value == NULL || output == NULL) return H2_FIXTURE_ERR_INVALID_ARG;
    h2_pal_json_value_t *object = NULL;
    h2_fixture_result_t result = h2_fixture_from_pal(h2_pal_json_value_create_object(client->config.json, document, &object));
    if (result != H2_FIXTURE_OK) return result;
    if (true) {
        h2_pal_json_value_t *field_0 = NULL;
        if (!h2_fixture_string_valid(value->a, 0, client->config.max_string_bytes)) return H2_FIXTURE_ERR_INVALID_ARG;
        result = h2_fixture_from_pal(h2_pal_json_value_create_string(client->config.json, document, value->a.data, value->a.len, &field_0));
        if (result != H2_FIXTURE_OK) return result;
        result = h2_fixture_from_pal(h2_pal_json_object_set(client->config.json, object, "a", 1, field_0));
        if (result != H2_FIXTURE_OK) return result;
    }
    *output = object;
    return H2_FIXTURE_OK;
}

static h2_fixture_result_t h2_fixture_a_decode(const h2_fixture_client_t *client, const h2_pal_json_value_t *input, h2_fixture_a_t *output) {
    if (input == NULL || output == NULL) return H2_FIXTURE_ERR_INVALID_ARG;
    memset(output, 0, sizeof(*output));
    h2_pal_json_type_t input_type = H2_PAL_JSON_TYPE_INVALID;
    h2_fixture_result_t result = h2_fixture_from_pal(h2_pal_json_value_type(client->config.json, input, &input_type));
    if (result != H2_FIXTURE_OK || input_type != H2_PAL_JSON_TYPE_OBJECT) return H2_FIXTURE_ERR_JSON;
    h2_pal_json_value_t *field_0 = NULL;
    h2_pal_result_t field_0_lookup = h2_pal_json_object_get(client->config.json, input, "a", 1, &field_0);
    if (field_0_lookup != H2_PAL_OK) return H2_FIXTURE_ERR_JSON;
    h2_pal_json_string_view_t string_1 = {0};
    result = h2_fixture_from_pal(h2_pal_json_value_get_string(client->config.json, field_0, &string_1));
    if (result != H2_FIXTURE_OK) return H2_FIXTURE_ERR_JSON;
    result = h2_fixture_copy_string(client->config.mem, string_1, client->config.max_string_bytes, &output->a);
    if (result != H2_FIXTURE_OK) return result;
    return H2_FIXTURE_OK;
}

static void h2_fixture_b_deinit(const h2_pal_mem_api_t *mem, h2_fixture_b_t *value) {
    if (mem == NULL || value == NULL) return;
    memset(value, 0, sizeof(*value));
}

static h2_fixture_result_t h2_fixture_b_encode(const h2_fixture_client_t *client, h2_pal_json_document_t *document, const h2_fixture_b_t *value, h2_pal_json_value_t **output) {
    if (value == NULL || output == NULL) return H2_FIXTURE_ERR_INVALID_ARG;
    h2_pal_json_value_t *object = NULL;
    h2_fixture_result_t result = h2_fixture_from_pal(h2_pal_json_value_create_object(client->config.json, document, &object));
    if (result != H2_FIXTURE_OK) return result;
    if (true) {
        h2_pal_json_value_t *field_0 = NULL;
        result = h2_fixture_from_pal(h2_pal_json_value_create_boolean(client->config.json, document, value->b, &field_0));
        if (result != H2_FIXTURE_OK) return result;
        result = h2_fixture_from_pal(h2_pal_json_object_set(client->config.json, object, "b", 1, field_0));
        if (result != H2_FIXTURE_OK) return result;
    }
    *output = object;
    return H2_FIXTURE_OK;
}

static h2_fixture_result_t h2_fixture_b_decode(const h2_fixture_client_t *client, const h2_pal_json_value_t *input, h2_fixture_b_t *output) {
    if (input == NULL || output == NULL) return H2_FIXTURE_ERR_INVALID_ARG;
    memset(output, 0, sizeof(*output));
    h2_pal_json_type_t input_type = H2_PAL_JSON_TYPE_INVALID;
    h2_fixture_result_t result = h2_fixture_from_pal(h2_pal_json_value_type(client->config.json, input, &input_type));
    if (result != H2_FIXTURE_OK || input_type != H2_PAL_JSON_TYPE_OBJECT) return H2_FIXTURE_ERR_JSON;
    h2_pal_json_value_t *field_0 = NULL;
    h2_pal_result_t field_0_lookup = h2_pal_json_object_get(client->config.json, input, "b", 1, &field_0);
    if (field_0_lookup != H2_PAL_OK) return H2_FIXTURE_ERR_JSON;
    result = h2_fixture_from_pal(h2_pal_json_value_get_boolean(client->config.json, field_0, &output->b));
    if (result != H2_FIXTURE_OK) return H2_FIXTURE_ERR_JSON;
    return H2_FIXTURE_OK;
}

static void h2_fixture_error_deinit(const h2_pal_mem_api_t *mem, h2_fixture_error_t *value) {
    if (mem == NULL || value == NULL) return;
    h2_pal_mem_free(mem, (void *)value->message.data);
    memset(value, 0, sizeof(*value));
}

static h2_fixture_result_t h2_fixture_error_encode(const h2_fixture_client_t *client, h2_pal_json_document_t *document, const h2_fixture_error_t *value, h2_pal_json_value_t **output) {
    if (value == NULL || output == NULL) return H2_FIXTURE_ERR_INVALID_ARG;
    h2_pal_json_value_t *object = NULL;
    h2_fixture_result_t result = h2_fixture_from_pal(h2_pal_json_value_create_object(client->config.json, document, &object));
    if (result != H2_FIXTURE_OK) return result;
    if (true) {
        h2_pal_json_value_t *field_0 = NULL;
        if (!h2_fixture_string_valid(value->message, 0, (size_t)64u)) return H2_FIXTURE_ERR_INVALID_ARG;
        result = h2_fixture_from_pal(h2_pal_json_value_create_string(client->config.json, document, value->message.data, value->message.len, &field_0));
        if (result != H2_FIXTURE_OK) return result;
        result = h2_fixture_from_pal(h2_pal_json_object_set(client->config.json, object, "message", 7, field_0));
        if (result != H2_FIXTURE_OK) return result;
    }
    *output = object;
    return H2_FIXTURE_OK;
}

static h2_fixture_result_t h2_fixture_error_decode(const h2_fixture_client_t *client, const h2_pal_json_value_t *input, h2_fixture_error_t *output) {
    if (input == NULL || output == NULL) return H2_FIXTURE_ERR_INVALID_ARG;
    memset(output, 0, sizeof(*output));
    h2_pal_json_type_t input_type = H2_PAL_JSON_TYPE_INVALID;
    h2_fixture_result_t result = h2_fixture_from_pal(h2_pal_json_value_type(client->config.json, input, &input_type));
    if (result != H2_FIXTURE_OK || input_type != H2_PAL_JSON_TYPE_OBJECT) return H2_FIXTURE_ERR_JSON;
    h2_pal_json_value_t *field_0 = NULL;
    h2_pal_result_t field_0_lookup = h2_pal_json_object_get(client->config.json, input, "message", 7, &field_0);
    if (field_0_lookup != H2_PAL_OK) return H2_FIXTURE_ERR_JSON;
    h2_pal_json_string_view_t string_1 = {0};
    result = h2_fixture_from_pal(h2_pal_json_value_get_string(client->config.json, field_0, &string_1));
    if (result != H2_FIXTURE_OK) return H2_FIXTURE_ERR_JSON;
    result = h2_fixture_copy_string(client->config.mem, string_1, (size_t)64u, &output->message);
    if (result != H2_FIXTURE_OK) return result;
    return H2_FIXTURE_OK;
}

static void h2_fixture_list_items_response_200_body_deinit(const h2_pal_mem_api_t *mem, h2_fixture_list_items_response_200_body_t *value) {
    if (mem == NULL || value == NULL) return;
    for (size_t i = 0u; i < value->value.count; ++i) {
        if (value->value.items[i] != NULL) { h2_fixture_value_deinit(mem, value->value.items[i]); h2_pal_mem_free(mem, value->value.items[i]); }
    }
    h2_pal_mem_free(mem, value->value.items);
    memset(value, 0, sizeof(*value));
}

static h2_fixture_result_t h2_fixture_list_items_response_200_body_encode(const h2_fixture_client_t *client, h2_pal_json_document_t *document, const h2_fixture_list_items_response_200_body_t *value, h2_pal_json_value_t **output) {
    if (value == NULL || output == NULL) return H2_FIXTURE_ERR_INVALID_ARG;
    h2_fixture_result_t result = H2_FIXTURE_OK;
    h2_pal_json_value_t *alias = NULL;
    if (value->value.count > client->config.max_array_items || (value->value.items == NULL && value->value.count != 0u)) return H2_FIXTURE_ERR_INVALID_ARG;
    result = h2_fixture_from_pal(h2_pal_json_value_create_array(client->config.json, document, &alias));
    if (result != H2_FIXTURE_OK) return result;
    for (size_t i = 0u; i < value->value.count; ++i) {
        h2_pal_json_value_t *item_0 = NULL;
        if (value->value.items[i] == NULL) return H2_FIXTURE_ERR_INVALID_ARG;
        result = h2_fixture_value_encode(client, document, value->value.items[i], &item_0);
        if (result != H2_FIXTURE_OK) return result;
        result = h2_fixture_from_pal(h2_pal_json_array_append(client->config.json, alias, item_0));
        if (result != H2_FIXTURE_OK) return result;
    }
    if (result != H2_FIXTURE_OK) return result;
    *output = alias;
    return H2_FIXTURE_OK;
}

static h2_fixture_result_t h2_fixture_list_items_response_200_body_decode(const h2_fixture_client_t *client, const h2_pal_json_value_t *input, h2_fixture_list_items_response_200_body_t *output) {
    if (input == NULL || output == NULL) return H2_FIXTURE_ERR_INVALID_ARG;
    memset(output, 0, sizeof(*output));
    h2_pal_json_type_t input_type = H2_PAL_JSON_TYPE_INVALID;
    h2_fixture_result_t result = h2_fixture_from_pal(h2_pal_json_value_type(client->config.json, input, &input_type));
    size_t count_0 = 0u;
    result = h2_fixture_from_pal(h2_pal_json_array_size(client->config.json, input, &count_0));
    if (result != H2_FIXTURE_OK || count_0 > client->config.max_array_items) return H2_FIXTURE_ERR_JSON;
    if (count_0 != 0u) {
        if (count_0 > SIZE_MAX / sizeof(*output->value.items)) return H2_FIXTURE_ERR_NO_SPACE;
        output->value.items = h2_pal_mem_alloc(client->config.mem, sizeof(*output->value.items) * count_0);
        if (output->value.items == NULL) return H2_FIXTURE_ERR_NO_MEMORY;
        memset(output->value.items, 0, sizeof(*output->value.items) * count_0);
    }
    output->value.count = count_0;
    for (size_t i = 0u; i < count_0; ++i) {
        h2_pal_json_value_t *item_1 = NULL;
        result = h2_fixture_from_pal(h2_pal_json_array_get(client->config.json, input, i, &item_1));
        if (result != H2_FIXTURE_OK) return H2_FIXTURE_ERR_JSON;
        output->value.items[i] = h2_pal_mem_alloc(client->config.mem, sizeof(*output->value.items[i]));
        if (output->value.items[i] == NULL) return H2_FIXTURE_ERR_NO_MEMORY;
        result = h2_fixture_value_decode(client, item_1, output->value.items[i]);
        if (result != H2_FIXTURE_OK) return result;
    }
    return H2_FIXTURE_OK;
}

static void h2_fixture_pet_deinit(const h2_pal_mem_api_t *mem, h2_fixture_pet_t *value) {
    if (mem == NULL || value == NULL) return;
    h2_pal_mem_free(mem, (void *)value->kind.data);
    h2_pal_mem_free(mem, (void *)value->name.data);
    for (size_t i = 0u; i < value->tags.count; ++i) {
        h2_pal_mem_free(mem, (void *)value->tags.items[i].data);
    }
    h2_pal_mem_free(mem, value->tags.items);
    memset(value, 0, sizeof(*value));
}

static h2_fixture_result_t h2_fixture_pet_encode(const h2_fixture_client_t *client, h2_pal_json_document_t *document, const h2_fixture_pet_t *value, h2_pal_json_value_t **output) {
    if (value == NULL || output == NULL) return H2_FIXTURE_ERR_INVALID_ARG;
    h2_pal_json_value_t *object = NULL;
    h2_fixture_result_t result = h2_fixture_from_pal(h2_pal_json_value_create_object(client->config.json, document, &object));
    if (result != H2_FIXTURE_OK) return result;
    if (true) {
        h2_pal_json_value_t *field_0 = NULL;
        result = h2_fixture_from_pal(h2_pal_json_value_create_boolean(client->config.json, document, value->active, &field_0));
        if (result != H2_FIXTURE_OK) return result;
        result = h2_fixture_from_pal(h2_pal_json_object_set(client->config.json, object, "active", 6, field_0));
        if (result != H2_FIXTURE_OK) return result;
    }
    if (true) {
        h2_pal_json_value_t *field_1 = NULL;
        result = h2_fixture_from_pal(h2_pal_json_value_create_number(client->config.json, document, (double)value->age, &field_1));
        if (result != H2_FIXTURE_OK) return result;
        result = h2_fixture_from_pal(h2_pal_json_object_set(client->config.json, object, "age", 3, field_1));
        if (result != H2_FIXTURE_OK) return result;
    }
    if (true) {
        h2_pal_json_value_t *field_2 = NULL;
        if (!h2_fixture_string_valid(value->kind, 0, (size_t)8u)) return H2_FIXTURE_ERR_INVALID_ARG;
        if (!((value->kind.len == 3 && memcmp(value->kind.data, "cat", 3) == 0) || (value->kind.len == 3 && memcmp(value->kind.data, "dog", 3) == 0))) return H2_FIXTURE_ERR_INVALID_ARG;
        result = h2_fixture_from_pal(h2_pal_json_value_create_string(client->config.json, document, value->kind.data, value->kind.len, &field_2));
        if (result != H2_FIXTURE_OK) return result;
        result = h2_fixture_from_pal(h2_pal_json_object_set(client->config.json, object, "kind", 4, field_2));
        if (result != H2_FIXTURE_OK) return result;
    }
    if (true) {
        h2_pal_json_value_t *field_3 = NULL;
        if (!h2_fixture_string_valid(value->name, 0, (size_t)48u)) return H2_FIXTURE_ERR_INVALID_ARG;
        result = h2_fixture_from_pal(h2_pal_json_value_create_string(client->config.json, document, value->name.data, value->name.len, &field_3));
        if (result != H2_FIXTURE_OK) return result;
        result = h2_fixture_from_pal(h2_pal_json_object_set(client->config.json, object, "name", 4, field_3));
        if (result != H2_FIXTURE_OK) return result;
    }
    if (true) {
        h2_pal_json_value_t *field_4 = NULL;
        if (value->tags.count > (size_t)4u || (value->tags.items == NULL && value->tags.count != 0u)) return H2_FIXTURE_ERR_INVALID_ARG;
        result = h2_fixture_from_pal(h2_pal_json_value_create_array(client->config.json, document, &field_4));
        if (result != H2_FIXTURE_OK) return result;
        for (size_t i = 0u; i < value->tags.count; ++i) {
            h2_pal_json_value_t *item_5 = NULL;
            if (!h2_fixture_string_valid(value->tags.items[i], 0, (size_t)12u)) return H2_FIXTURE_ERR_INVALID_ARG;
            result = h2_fixture_from_pal(h2_pal_json_value_create_string(client->config.json, document, value->tags.items[i].data, value->tags.items[i].len, &item_5));
            if (result != H2_FIXTURE_OK) return result;
            result = h2_fixture_from_pal(h2_pal_json_array_append(client->config.json, field_4, item_5));
            if (result != H2_FIXTURE_OK) return result;
        }
        if (result != H2_FIXTURE_OK) return result;
        result = h2_fixture_from_pal(h2_pal_json_object_set(client->config.json, object, "tags", 4, field_4));
        if (result != H2_FIXTURE_OK) return result;
    }
    *output = object;
    return H2_FIXTURE_OK;
}

static h2_fixture_result_t h2_fixture_pet_decode(const h2_fixture_client_t *client, const h2_pal_json_value_t *input, h2_fixture_pet_t *output) {
    if (input == NULL || output == NULL) return H2_FIXTURE_ERR_INVALID_ARG;
    memset(output, 0, sizeof(*output));
    h2_pal_json_type_t input_type = H2_PAL_JSON_TYPE_INVALID;
    h2_fixture_result_t result = h2_fixture_from_pal(h2_pal_json_value_type(client->config.json, input, &input_type));
    if (result != H2_FIXTURE_OK || input_type != H2_PAL_JSON_TYPE_OBJECT) return H2_FIXTURE_ERR_JSON;
    h2_pal_json_value_t *field_0 = NULL;
    h2_pal_result_t field_0_lookup = h2_pal_json_object_get(client->config.json, input, "active", 6, &field_0);
    if (field_0_lookup != H2_PAL_OK) return H2_FIXTURE_ERR_JSON;
    result = h2_fixture_from_pal(h2_pal_json_value_get_boolean(client->config.json, field_0, &output->active));
    if (result != H2_FIXTURE_OK) return H2_FIXTURE_ERR_JSON;
    h2_pal_json_value_t *field_1 = NULL;
    h2_pal_result_t field_1_lookup = h2_pal_json_object_get(client->config.json, input, "age", 3, &field_1);
    if (field_1_lookup != H2_PAL_OK) return H2_FIXTURE_ERR_JSON;
    double number_2 = 0.0;
    result = h2_fixture_from_pal(h2_pal_json_value_get_number(client->config.json, field_1, &number_2));
    if (result != H2_FIXTURE_OK || !isfinite(number_2) || number_2 < INT32_MIN || number_2 > INT32_MAX || number_2 != (double)(int32_t)number_2) return H2_FIXTURE_ERR_JSON;
    output->age = (int32_t)number_2;
    h2_pal_json_value_t *field_3 = NULL;
    h2_pal_result_t field_3_lookup = h2_pal_json_object_get(client->config.json, input, "kind", 4, &field_3);
    if (field_3_lookup != H2_PAL_OK) return H2_FIXTURE_ERR_JSON;
    h2_pal_json_string_view_t string_4 = {0};
    result = h2_fixture_from_pal(h2_pal_json_value_get_string(client->config.json, field_3, &string_4));
    if (result != H2_FIXTURE_OK) return H2_FIXTURE_ERR_JSON;
    result = h2_fixture_copy_string(client->config.mem, string_4, (size_t)8u, &output->kind);
    if (result != H2_FIXTURE_OK) return result;
    if (!((output->kind.len == 3 && memcmp(output->kind.data, "cat", 3) == 0) || (output->kind.len == 3 && memcmp(output->kind.data, "dog", 3) == 0))) return H2_FIXTURE_ERR_JSON;
    h2_pal_json_value_t *field_5 = NULL;
    h2_pal_result_t field_5_lookup = h2_pal_json_object_get(client->config.json, input, "name", 4, &field_5);
    if (field_5_lookup != H2_PAL_OK) return H2_FIXTURE_ERR_JSON;
    h2_pal_json_string_view_t string_6 = {0};
    result = h2_fixture_from_pal(h2_pal_json_value_get_string(client->config.json, field_5, &string_6));
    if (result != H2_FIXTURE_OK) return H2_FIXTURE_ERR_JSON;
    result = h2_fixture_copy_string(client->config.mem, string_6, (size_t)48u, &output->name);
    if (result != H2_FIXTURE_OK) return result;
    h2_pal_json_value_t *field_7 = NULL;
    h2_pal_result_t field_7_lookup = h2_pal_json_object_get(client->config.json, input, "tags", 4, &field_7);
    if (field_7_lookup != H2_PAL_OK) return H2_FIXTURE_ERR_JSON;
    size_t count_8 = 0u;
    result = h2_fixture_from_pal(h2_pal_json_array_size(client->config.json, field_7, &count_8));
    if (result != H2_FIXTURE_OK || count_8 > (size_t)4u) return H2_FIXTURE_ERR_JSON;
    if (count_8 != 0u) {
        if (count_8 > SIZE_MAX / sizeof(*output->tags.items)) return H2_FIXTURE_ERR_NO_SPACE;
        output->tags.items = h2_pal_mem_alloc(client->config.mem, sizeof(*output->tags.items) * count_8);
        if (output->tags.items == NULL) return H2_FIXTURE_ERR_NO_MEMORY;
        memset(output->tags.items, 0, sizeof(*output->tags.items) * count_8);
    }
    output->tags.count = count_8;
    for (size_t i = 0u; i < count_8; ++i) {
        h2_pal_json_value_t *item_9 = NULL;
        result = h2_fixture_from_pal(h2_pal_json_array_get(client->config.json, field_7, i, &item_9));
        if (result != H2_FIXTURE_OK) return H2_FIXTURE_ERR_JSON;
        h2_pal_json_string_view_t string_10 = {0};
        result = h2_fixture_from_pal(h2_pal_json_value_get_string(client->config.json, item_9, &string_10));
        if (result != H2_FIXTURE_OK) return H2_FIXTURE_ERR_JSON;
        result = h2_fixture_copy_string(client->config.mem, string_10, (size_t)12u, &output->tags.items[i]);
        if (result != H2_FIXTURE_OK) return result;
    }
    return H2_FIXTURE_OK;
}

static void h2_fixture_upload_request_body_deinit(const h2_pal_mem_api_t *mem, h2_fixture_upload_request_body_t *value) {
    if (mem == NULL || value == NULL) return;
    h2_pal_mem_free(mem, (void *)value->dir.data);
    memset(value, 0, sizeof(*value));
}

static h2_fixture_result_t h2_fixture_upload_request_body_encode(const h2_fixture_client_t *client, h2_pal_json_document_t *document, const h2_fixture_upload_request_body_t *value, h2_pal_json_value_t **output) {
    if (value == NULL || output == NULL) return H2_FIXTURE_ERR_INVALID_ARG;
    h2_pal_json_value_t *object = NULL;
    h2_fixture_result_t result = h2_fixture_from_pal(h2_pal_json_value_create_object(client->config.json, document, &object));
    if (result != H2_FIXTURE_OK) return result;
    if (true) {
        h2_pal_json_value_t *field_0 = NULL;
        if (!h2_fixture_string_valid(value->dir, 0, client->config.max_string_bytes)) return H2_FIXTURE_ERR_INVALID_ARG;
        result = h2_fixture_from_pal(h2_pal_json_value_create_string(client->config.json, document, value->dir.data, value->dir.len, &field_0));
        if (result != H2_FIXTURE_OK) return result;
        result = h2_fixture_from_pal(h2_pal_json_object_set(client->config.json, object, "dir", 3, field_0));
        if (result != H2_FIXTURE_OK) return result;
    }
    if (true) {
        h2_pal_json_value_t *field_1 = NULL;
        (void)value->file; result = H2_FIXTURE_ERR_UNSUPPORTED;
        if (result != H2_FIXTURE_OK) return result;
        result = h2_fixture_from_pal(h2_pal_json_object_set(client->config.json, object, "file", 4, field_1));
        if (result != H2_FIXTURE_OK) return result;
    }
    *output = object;
    return H2_FIXTURE_OK;
}

static h2_fixture_result_t h2_fixture_upload_request_body_decode(const h2_fixture_client_t *client, const h2_pal_json_value_t *input, h2_fixture_upload_request_body_t *output) {
    if (input == NULL || output == NULL) return H2_FIXTURE_ERR_INVALID_ARG;
    memset(output, 0, sizeof(*output));
    h2_pal_json_type_t input_type = H2_PAL_JSON_TYPE_INVALID;
    h2_fixture_result_t result = h2_fixture_from_pal(h2_pal_json_value_type(client->config.json, input, &input_type));
    if (result != H2_FIXTURE_OK || input_type != H2_PAL_JSON_TYPE_OBJECT) return H2_FIXTURE_ERR_JSON;
    h2_pal_json_value_t *field_0 = NULL;
    h2_pal_result_t field_0_lookup = h2_pal_json_object_get(client->config.json, input, "dir", 3, &field_0);
    if (field_0_lookup != H2_PAL_OK) return H2_FIXTURE_ERR_JSON;
    h2_pal_json_string_view_t string_1 = {0};
    result = h2_fixture_from_pal(h2_pal_json_value_get_string(client->config.json, field_0, &string_1));
    if (result != H2_FIXTURE_OK) return H2_FIXTURE_ERR_JSON;
    result = h2_fixture_copy_string(client->config.mem, string_1, client->config.max_string_bytes, &output->dir);
    if (result != H2_FIXTURE_OK) return result;
    h2_pal_json_value_t *field_2 = NULL;
    h2_pal_result_t field_2_lookup = h2_pal_json_object_get(client->config.json, input, "file", 4, &field_2);
    if (field_2_lookup != H2_PAL_OK) return H2_FIXTURE_ERR_JSON;
    (void)field_2; (void)output->file; return H2_FIXTURE_ERR_UNSUPPORTED;
    return H2_FIXTURE_OK;
}

static void h2_fixture_value_deinit(const h2_pal_mem_api_t *mem, h2_fixture_value_t *value) {
    if (mem == NULL || value == NULL) return;
    if (value->choice != NULL) { h2_fixture_value_choice_deinit(mem, value->choice); h2_pal_mem_free(mem, value->choice); }
    h2_pal_mem_free(mem, (void *)value->metadata.data);
    h2_pal_mem_free(mem, (void *)value->name.data);
    memset(value, 0, sizeof(*value));
}

static h2_fixture_result_t h2_fixture_value_encode(const h2_fixture_client_t *client, h2_pal_json_document_t *document, const h2_fixture_value_t *value, h2_pal_json_value_t **output) {
    if (value == NULL || output == NULL) return H2_FIXTURE_ERR_INVALID_ARG;
    h2_pal_json_value_t *object = NULL;
    h2_fixture_result_t result = h2_fixture_from_pal(h2_pal_json_value_create_object(client->config.json, document, &object));
    if (result != H2_FIXTURE_OK) return result;
    if (value->has_choice) {
        h2_pal_json_value_t *field_0 = NULL;
        if (value->choice == NULL) return H2_FIXTURE_ERR_INVALID_ARG;
        result = h2_fixture_value_choice_encode(client, document, value->choice, &field_0);
        if (result != H2_FIXTURE_OK) return result;
        result = h2_fixture_from_pal(h2_pal_json_object_set(client->config.json, object, "choice", 6, field_0));
        if (result != H2_FIXTURE_OK) return result;
    }
    if (value->has_metadata) {
        h2_pal_json_value_t *field_1 = NULL;
        result = h2_fixture_json_encode(client, document, value->metadata, &field_1);
        if (result != H2_FIXTURE_OK) return result;
        result = h2_fixture_from_pal(h2_pal_json_object_set(client->config.json, object, "metadata", 8, field_1));
        if (result != H2_FIXTURE_OK) return result;
    }
    if (value->has_name) {
        h2_pal_json_value_t *field_2 = NULL;
        if (value->is_name_null) { result = h2_fixture_from_pal(h2_pal_json_value_create_null(client->config.json, document, &field_2)); } else {
            h2_pal_json_value_t *field_2_value = NULL;
            if (!h2_fixture_string_valid(value->name, 0, client->config.max_string_bytes)) return H2_FIXTURE_ERR_INVALID_ARG;
            result = h2_fixture_from_pal(h2_pal_json_value_create_string(client->config.json, document, value->name.data, value->name.len, &field_2_value));
            if (result != H2_FIXTURE_OK) return result;
            field_2 = field_2_value;
        }
        if (result != H2_FIXTURE_OK) return result;
        result = h2_fixture_from_pal(h2_pal_json_object_set(client->config.json, object, "name", 4, field_2));
        if (result != H2_FIXTURE_OK) return result;
    }
    *output = object;
    return H2_FIXTURE_OK;
}

static h2_fixture_result_t h2_fixture_value_decode(const h2_fixture_client_t *client, const h2_pal_json_value_t *input, h2_fixture_value_t *output) {
    if (input == NULL || output == NULL) return H2_FIXTURE_ERR_INVALID_ARG;
    memset(output, 0, sizeof(*output));
    h2_pal_json_type_t input_type = H2_PAL_JSON_TYPE_INVALID;
    h2_fixture_result_t result = h2_fixture_from_pal(h2_pal_json_value_type(client->config.json, input, &input_type));
    if (result != H2_FIXTURE_OK || input_type != H2_PAL_JSON_TYPE_OBJECT) return H2_FIXTURE_ERR_JSON;
    h2_pal_json_value_t *field_0 = NULL;
    h2_pal_result_t field_0_lookup = h2_pal_json_object_get(client->config.json, input, "choice", 6, &field_0);
    if (field_0_lookup == H2_PAL_OK) {
        output->has_choice = true;
        output->choice = h2_pal_mem_alloc(client->config.mem, sizeof(*output->choice));
        if (output->choice == NULL) return H2_FIXTURE_ERR_NO_MEMORY;
        result = h2_fixture_value_choice_decode(client, field_0, output->choice);
        if (result != H2_FIXTURE_OK) return result;
    } else if (field_0_lookup != H2_PAL_ERR_NOT_FOUND) { return H2_FIXTURE_ERR_JSON; }
    h2_pal_json_value_t *field_1 = NULL;
    h2_pal_result_t field_1_lookup = h2_pal_json_object_get(client->config.json, input, "metadata", 8, &field_1);
    if (field_1_lookup == H2_PAL_OK) {
        output->has_metadata = true;
        result = h2_fixture_json_decode(client, field_1, &output->metadata);
        if (result != H2_FIXTURE_OK) return result;
    } else if (field_1_lookup != H2_PAL_ERR_NOT_FOUND) { return H2_FIXTURE_ERR_JSON; }
    h2_pal_json_value_t *field_2 = NULL;
    h2_pal_result_t field_2_lookup = h2_pal_json_object_get(client->config.json, input, "name", 4, &field_2);
    if (field_2_lookup == H2_PAL_OK) {
        output->has_name = true;
        h2_pal_json_type_t nullable_type_3 = H2_PAL_JSON_TYPE_INVALID;
        result = h2_fixture_from_pal(h2_pal_json_value_type(client->config.json, field_2, &nullable_type_3));
        if (result != H2_FIXTURE_OK) return H2_FIXTURE_ERR_JSON;
        if (nullable_type_3 == H2_PAL_JSON_TYPE_NULL) { output->is_name_null = true; } else {
            h2_pal_json_string_view_t string_4 = {0};
            result = h2_fixture_from_pal(h2_pal_json_value_get_string(client->config.json, field_2, &string_4));
            if (result != H2_FIXTURE_OK) return H2_FIXTURE_ERR_JSON;
            result = h2_fixture_copy_string(client->config.mem, string_4, client->config.max_string_bytes, &output->name);
            if (result != H2_FIXTURE_OK) return result;
        }
    } else if (field_2_lookup != H2_PAL_ERR_NOT_FOUND) { return H2_FIXTURE_ERR_JSON; }
    return H2_FIXTURE_OK;
}

static void h2_fixture_value_choice_deinit(const h2_pal_mem_api_t *mem, h2_fixture_value_choice_t *value) {
    if (mem == NULL || value == NULL) return;
    switch (value->kind) {
    case H2_FIXTURE_VALUE_CHOICE_A:
        if (value->value.a != NULL) { h2_fixture_a_deinit(mem, value->value.a); h2_pal_mem_free(mem, value->value.a); }
        break;
    case H2_FIXTURE_VALUE_CHOICE_B:
        if (value->value.b != NULL) { h2_fixture_b_deinit(mem, value->value.b); h2_pal_mem_free(mem, value->value.b); }
        break;
    default: break;
    }
    memset(value, 0, sizeof(*value));
}

static h2_fixture_result_t h2_fixture_value_choice_encode(const h2_fixture_client_t *client, h2_pal_json_document_t *document, const h2_fixture_value_choice_t *value, h2_pal_json_value_t **output) {
    if (value == NULL || output == NULL) return H2_FIXTURE_ERR_INVALID_ARG;
    h2_fixture_result_t result = H2_FIXTURE_OK;
    switch (value->kind) {
    case H2_FIXTURE_VALUE_CHOICE_A: {
        h2_pal_json_value_t *variant = NULL;
        if (value->value.a == NULL) return H2_FIXTURE_ERR_INVALID_ARG;
        result = h2_fixture_a_encode(client, document, value->value.a, &variant);
        if (result != H2_FIXTURE_OK) return result;
        *output = variant;
        return H2_FIXTURE_OK;
    }
    case H2_FIXTURE_VALUE_CHOICE_B: {
        h2_pal_json_value_t *variant = NULL;
        if (value->value.b == NULL) return H2_FIXTURE_ERR_INVALID_ARG;
        result = h2_fixture_b_encode(client, document, value->value.b, &variant);
        if (result != H2_FIXTURE_OK) return result;
        *output = variant;
        return H2_FIXTURE_OK;
    }
    default: return H2_FIXTURE_ERR_INVALID_ARG;
    }
}

static h2_fixture_result_t h2_fixture_value_choice_decode(const h2_fixture_client_t *client, const h2_pal_json_value_t *input, h2_fixture_value_choice_t *output) {
    if (input == NULL || output == NULL) return H2_FIXTURE_ERR_INVALID_ARG;
    memset(output, 0, sizeof(*output));
    h2_pal_json_type_t input_type = H2_PAL_JSON_TYPE_INVALID;
    h2_fixture_result_t result = h2_fixture_from_pal(h2_pal_json_value_type(client->config.json, input, &input_type));
    if (result != H2_FIXTURE_OK || input_type != H2_PAL_JSON_TYPE_OBJECT) return H2_FIXTURE_ERR_JSON;
    size_t matches = 0u;
    h2_fixture_a_t * candidate_0 = NULL;
    candidate_0 = h2_pal_mem_alloc(client->config.mem, sizeof(*candidate_0));
    if (candidate_0 == NULL) return H2_FIXTURE_ERR_NO_MEMORY;
    result = h2_fixture_a_decode(client, input, candidate_0);
    if (result == H2_FIXTURE_OK) { ++matches; } else { if (candidate_0 != NULL) { h2_fixture_a_deinit(client->config.mem, candidate_0); h2_pal_mem_free(client->config.mem, candidate_0); candidate_0 = NULL; } if (result != H2_FIXTURE_ERR_JSON) {
        return result;
    } result = H2_FIXTURE_OK; }
    h2_fixture_b_t * candidate_1 = NULL;
    candidate_1 = h2_pal_mem_alloc(client->config.mem, sizeof(*candidate_1));
    if (candidate_1 == NULL) return H2_FIXTURE_ERR_NO_MEMORY;
    result = h2_fixture_b_decode(client, input, candidate_1);
    if (result == H2_FIXTURE_OK) { ++matches; } else { if (candidate_1 != NULL) { h2_fixture_b_deinit(client->config.mem, candidate_1); h2_pal_mem_free(client->config.mem, candidate_1); candidate_1 = NULL; } if (result != H2_FIXTURE_ERR_JSON) {
        if (candidate_0 != NULL) { h2_fixture_a_deinit(client->config.mem, candidate_0); h2_pal_mem_free(client->config.mem, candidate_0); }
        return result;
    } result = H2_FIXTURE_OK; }
    if (matches != 1u) {
        if (candidate_0 != NULL) { h2_fixture_a_deinit(client->config.mem, candidate_0); h2_pal_mem_free(client->config.mem, candidate_0); }
        if (candidate_1 != NULL) { h2_fixture_b_deinit(client->config.mem, candidate_1); h2_pal_mem_free(client->config.mem, candidate_1); }
        return H2_FIXTURE_ERR_JSON;
    }
    if (candidate_0 != NULL) { output->kind = H2_FIXTURE_VALUE_CHOICE_A; output->value.a = candidate_0; } else if (candidate_1 != NULL) { output->kind = H2_FIXTURE_VALUE_CHOICE_B; output->value.b = candidate_1; }
    return H2_FIXTURE_OK;
}

h2_fixture_result_t h2_fixture_client_init(h2_fixture_client_t *client, const h2_fixture_client_config_t *config) {
    (void)h2_fixture_from_pal;
    (void)h2_fixture_from_http;
    (void)h2_fixture_utf8_valid;
    (void)h2_fixture_string_valid;
    (void)h2_fixture_header_value_valid;
    (void)h2_fixture_http_header_valid;
    (void)h2_fixture_header_name_equal;
    (void)h2_fixture_copy_string;
    (void)h2_fixture_buffer_append;
    (void)h2_fixture_bytes_contain;
    (void)h2_fixture_unreserved;
    (void)h2_fixture_buffer_url_encode;
    (void)h2_fixture_json_clone;
    (void)h2_fixture_json_encode;
    (void)h2_fixture_json_decode;
    (void)h2_fixture_a_deinit;
    (void)h2_fixture_a_encode;
    (void)h2_fixture_a_decode;
    (void)h2_fixture_b_deinit;
    (void)h2_fixture_b_encode;
    (void)h2_fixture_b_decode;
    (void)h2_fixture_error_deinit;
    (void)h2_fixture_error_encode;
    (void)h2_fixture_error_decode;
    (void)h2_fixture_list_items_response_200_body_deinit;
    (void)h2_fixture_list_items_response_200_body_encode;
    (void)h2_fixture_list_items_response_200_body_decode;
    (void)h2_fixture_pet_deinit;
    (void)h2_fixture_pet_encode;
    (void)h2_fixture_pet_decode;
    (void)h2_fixture_upload_request_body_deinit;
    (void)h2_fixture_upload_request_body_encode;
    (void)h2_fixture_upload_request_body_decode;
    (void)h2_fixture_value_deinit;
    (void)h2_fixture_value_encode;
    (void)h2_fixture_value_decode;
    (void)h2_fixture_value_choice_deinit;
    (void)h2_fixture_value_choice_encode;
    (void)h2_fixture_value_choice_decode;
    if (client == NULL || !h2_fixture_config_valid(config)) { return H2_FIXTURE_ERR_INVALID_ARG; }
    client->config = *config;
    return H2_FIXTURE_OK;
}

void h2_fixture_list_items_response_deinit(h2_fixture_list_items_response_t *response) {
    if (response == NULL) return;
    if (response->mem != NULL && response->has_body) {
        switch (response->status_code) {
        case 200: h2_fixture_list_items_response_200_body_deinit(response->mem, &response->body.status_200); break;
        default: break;
        }
    }
    memset(response, 0, sizeof(*response));
}

h2_fixture_result_t h2_fixture_list_items(h2_fixture_client_t *client, const h2_fixture_list_items_request_t *request, h2_fixture_list_items_response_t *response) {
    if (client == NULL || request == NULL || response == NULL || !h2_fixture_config_valid(&client->config)) return H2_FIXTURE_ERR_INVALID_ARG;
    h2_fixture_list_items_response_deinit(response);
    response->mem = client->config.mem;
    if (request->has_tag && (request->tag.count > client->config.max_array_items || (request->tag.items == NULL && request->tag.count != 0u))) return H2_FIXTURE_ERR_INVALID_ARG;
    char *url_data = h2_pal_mem_alloc(client->config.mem, client->config.max_url_bytes + 1u);
    if (url_data == NULL) return H2_FIXTURE_ERR_NO_MEMORY;
    h2_fixture_buffer_t url = {url_data, 0u, client->config.max_url_bytes};
    h2_fixture_result_t result = h2_fixture_buffer_append(&url, client->config.base_url, strlen(client->config.base_url));
    if (result != H2_FIXTURE_OK) goto cleanup_url;
    result = h2_fixture_buffer_append(&url, "/items", 6); if (result != H2_FIXTURE_OK) goto cleanup_url;
    bool url_has_query = false;
    if (request->has_tag) {
        for (size_t query_index = 0u; query_index < request->tag.count; ++query_index) {
            result = h2_fixture_buffer_append(&url, url_has_query ? "&tag=" : "?tag=", 5); if (result != H2_FIXTURE_OK) goto cleanup_url;
            url_has_query = true;
            if (!h2_fixture_string_valid(request->tag.items[query_index], 0, client->config.max_string_bytes)) { result = H2_FIXTURE_ERR_INVALID_ARG; goto cleanup_url; }
            result = h2_fixture_buffer_url_encode(&url, request->tag.items[query_index]); if (result != H2_FIXTURE_OK) goto cleanup_url;
        }
    }
    if (client->config.max_extra_headers > SIZE_MAX - 2) { result = H2_FIXTURE_ERR_NO_SPACE; goto cleanup_url; }
    size_t header_capacity = 2 + client->config.max_extra_headers;
    if (header_capacity > SIZE_MAX / sizeof(h2_pal_http_header_t)) { result = H2_FIXTURE_ERR_NO_SPACE; goto cleanup_url; }
    h2_pal_http_header_t *headers = NULL;
    if (header_capacity != 0u) headers = h2_pal_mem_alloc(client->config.mem, sizeof(*headers) * header_capacity);
    if (header_capacity != 0u && headers == NULL) { result = H2_FIXTURE_ERR_NO_MEMORY; goto cleanup_url; }
    if (headers != NULL) memset(headers, 0, sizeof(*headers) * header_capacity);
    size_t header_count = 0u;
    char *authorization = NULL;
    if (client->config.bearer_token.len == 0u || client->config.bearer_token.len > SIZE_MAX - 8u) { result = H2_FIXTURE_ERR_INVALID_ARG; goto cleanup_headers; }
    authorization = h2_pal_mem_alloc(client->config.mem, client->config.bearer_token.len + 8u);
    if (authorization == NULL) { result = H2_FIXTURE_ERR_NO_MEMORY; goto cleanup_headers; }
    memcpy(authorization, "Bearer ", 7u); memcpy(authorization + 7u, client->config.bearer_token.data, client->config.bearer_token.len); authorization[client->config.bearer_token.len + 7u] = '\0';
    headers[header_count++] = (h2_pal_http_header_t){{"Authorization", 13u}, {authorization, client->config.bearer_token.len + 7u}};
    headers[header_count++] = (h2_pal_http_header_t){{"Accept", 6u}, {"application/json", 16u}};
    if (client->config.header_callback != NULL) {
        result = client->config.header_callback(client->config.header_user, headers, header_capacity, &header_count);
        if (result != H2_FIXTURE_OK || header_count > header_capacity) { if (result == H2_FIXTURE_OK) result = H2_FIXTURE_ERR_INVALID_ARG; goto cleanup_headers; }
    }
    for (size_t i = 0u; i < header_count; ++i) { if (!h2_fixture_http_header_valid(&headers[i])) { result = H2_FIXTURE_ERR_INVALID_ARG; goto cleanup_headers; } }
    h2_pal_json_document_t *request_document = NULL;
    h2_pal_json_buffer_t request_body = {0};
    char *multipart_body = NULL;
    size_t multipart_body_len = 0u;
    uint8_t *response_buffer = h2_pal_mem_alloc(client->config.mem, client->config.max_response_bytes);
    if (response_buffer == NULL) { result = H2_FIXTURE_ERR_NO_MEMORY; goto cleanup_json; }
    h2_pal_http_request_t http_request = {
        .method = H2_PAL_HTTP_GET, .url = {url.data, url.len}, .headers = headers, .header_count = header_count,
        .body = multipart_body != NULL ? (const uint8_t *)multipart_body : request_body.data, .body_len = multipart_body != NULL ? multipart_body_len : request_body.len, .timeout_ms = client->config.timeout_ms,
        .response_buf = response_buffer, .response_buf_cap = client->config.max_response_bytes, .allocator = client->config.mem,
    };
    h2_pal_http_response_t http_response = {0};
    result = h2_fixture_from_http(h2_pal_http_request(client->config.http, &http_request, &http_response));
    if (result != H2_FIXTURE_OK) goto cleanup_http_response;
    response->status_code = http_response.status_code;
    result = (http_response.status_code >= 200 && http_response.status_code < 300) ? H2_FIXTURE_ERR_UNEXPECTED_STATUS : H2_FIXTURE_ERR_HTTP_STATUS;
    switch (http_response.status_code) {
    case 200:
    {
        h2_pal_json_document_t *response_document = NULL;
        response->has_body = true;
        result = h2_fixture_from_pal(h2_pal_json_document_parse(client->config.json, http_response.body, http_response.body_len, NULL, &response_document));
        h2_pal_json_value_t *response_root = NULL;
        if (result == H2_FIXTURE_OK) result = h2_fixture_from_pal(h2_pal_json_document_root(client->config.json, response_document, &response_root));
        if (result == H2_FIXTURE_OK) result = h2_fixture_list_items_response_200_body_decode(client, response_root, &response->body.status_200);
        (void)h2_pal_json_document_destroy(client->config.json, &response_document);
        if (result == H2_FIXTURE_OK) result = H2_FIXTURE_OK;
        break;
    }
    default:
        break;
    }
cleanup_http_response:
    h2_pal_http_response_free(client->config.http, &http_response);
    h2_pal_mem_free(client->config.mem, response_buffer);
cleanup_json:
    h2_pal_mem_free(client->config.mem, multipart_body);
    (void)h2_pal_json_buffer_release(client->config.json, &request_body);
    (void)h2_pal_json_document_destroy(client->config.json, &request_document);
cleanup_headers:
    h2_pal_mem_free(client->config.mem, authorization);
    h2_pal_mem_free(client->config.mem, headers);
cleanup_url:
    h2_pal_mem_free(client->config.mem, url_data);
    if (result != H2_FIXTURE_OK && result != H2_FIXTURE_ERR_HTTP_STATUS) {
        const int completed_status = response->status_code;
        h2_fixture_list_items_response_deinit(response);
        response->status_code = completed_status;
        response->mem = client->config.mem;
    }
    return result;
}

typedef struct h2_fixture_update_pet_response_header_context { const h2_fixture_client_t *client; h2_fixture_update_pet_response_t *response; } h2_fixture_update_pet_response_header_context_t;
static int h2_fixture_update_pet_response_header(void *user, const h2_pal_http_request_t *request, h2_pal_http_str_t name, h2_pal_http_str_t value) {
    (void)request;
    h2_fixture_update_pet_response_header_context_t *context = user;
    if (context == NULL || context->client == NULL || context->response == NULL || context->response->mem == NULL) return H2_PAL_ERR_INVALID_ARG;
    const h2_fixture_client_t *client = context->client;
    h2_fixture_update_pet_response_t *response = context->response;
    (void)client;
    if (h2_fixture_header_name_equal(name, "X-Trace", 7u)) {
        h2_fixture_string_t view = {value.data, value.len};
        if (!h2_fixture_string_valid(view, 1, (size_t)16u)) return H2_PAL_ERR_INVALID_ARG;
        if (!((view.len == 7 && memcmp(view.data, "trace-1", 7) == 0))) return H2_PAL_ERR_INVALID_ARG;
        char *copy = h2_pal_mem_alloc(response->mem, value.len + 1u);
        if (copy == NULL) return H2_PAL_ERR_NO_MEMORY;
        if (value.len != 0u) memcpy(copy, value.data, value.len);
        copy[value.len] = '\0';
        if (response->has_x_trace) h2_pal_mem_free(response->mem, (void *)response->x_trace.data);
        response->x_trace = (h2_fixture_string_t){copy, value.len};
        response->has_x_trace = true;
        return H2_PAL_OK;
    }
    return H2_PAL_OK;
}

void h2_fixture_update_pet_response_deinit(h2_fixture_update_pet_response_t *response) {
    if (response == NULL) return;
    const h2_pal_mem_api_t *mem = response->mem;
    if (mem != NULL && response->has_body) {
        switch (response->status_code) {
        case 200: h2_fixture_pet_deinit(mem, &response->body.status_200); break;
        case 400: h2_fixture_error_deinit(mem, &response->body.status_400); break;
        default: break;
        }
    }
    if (mem != NULL && response->has_x_trace) {
        h2_pal_mem_free(mem, (void *)response->x_trace.data);
    }
    memset(response, 0, sizeof(*response));
}

h2_fixture_result_t h2_fixture_update_pet(h2_fixture_client_t *client, const h2_fixture_update_pet_request_t *request, h2_fixture_update_pet_response_t *response) {
    if (client == NULL || request == NULL || response == NULL || !h2_fixture_config_valid(&client->config)) return H2_FIXTURE_ERR_INVALID_ARG;
    h2_fixture_update_pet_response_deinit(response);
    response->mem = client->config.mem;
    if (true && !h2_fixture_header_value_valid(request->x_device_id, 0, (size_t)36u)) return H2_FIXTURE_ERR_INVALID_ARG;
    if (true && !h2_fixture_string_valid(request->pet_id, 0, (size_t)32u)) return H2_FIXTURE_ERR_INVALID_ARG;
    if (true && request->body == NULL) return H2_FIXTURE_ERR_INVALID_ARG;
    char *url_data = h2_pal_mem_alloc(client->config.mem, client->config.max_url_bytes + 1u);
    if (url_data == NULL) return H2_FIXTURE_ERR_NO_MEMORY;
    h2_fixture_buffer_t url = {url_data, 0u, client->config.max_url_bytes};
    h2_fixture_result_t result = h2_fixture_buffer_append(&url, client->config.base_url, strlen(client->config.base_url));
    if (result != H2_FIXTURE_OK) goto cleanup_url;
    result = h2_fixture_buffer_append(&url, "/pets/", 6); if (result != H2_FIXTURE_OK) goto cleanup_url;
    result = h2_fixture_buffer_url_encode(&url, request->pet_id); if (result != H2_FIXTURE_OK) goto cleanup_url;
    bool url_has_query = false;
    if (request->has_verbose) {
        result = h2_fixture_buffer_append(&url, url_has_query ? "&verbose=" : "?verbose=", 9); if (result != H2_FIXTURE_OK) goto cleanup_url;
        url_has_query = true;
        result = h2_fixture_buffer_append(&url, request->verbose ? "true" : "false", request->verbose ? 4u : 5u); if (result != H2_FIXTURE_OK) goto cleanup_url;
    }
    if (client->config.max_extra_headers > SIZE_MAX - 3) { result = H2_FIXTURE_ERR_NO_SPACE; goto cleanup_url; }
    size_t header_capacity = 3 + client->config.max_extra_headers;
    if (header_capacity > SIZE_MAX / sizeof(h2_pal_http_header_t)) { result = H2_FIXTURE_ERR_NO_SPACE; goto cleanup_url; }
    h2_pal_http_header_t *headers = NULL;
    if (header_capacity != 0u) headers = h2_pal_mem_alloc(client->config.mem, sizeof(*headers) * header_capacity);
    if (header_capacity != 0u && headers == NULL) { result = H2_FIXTURE_ERR_NO_MEMORY; goto cleanup_url; }
    if (headers != NULL) memset(headers, 0, sizeof(*headers) * header_capacity);
    size_t header_count = 0u;
    char *authorization = NULL;
    if (true) {
        headers[header_count++] = (h2_pal_http_header_t){{"X-Device-ID", 11}, {request->x_device_id.data, request->x_device_id.len}};
    }
    if (true) headers[header_count++] = (h2_pal_http_header_t){{"Content-Type", 12u}, {"application/json", 16u}};
    headers[header_count++] = (h2_pal_http_header_t){{"Accept", 6u}, {"application/json", 16u}};
    if (client->config.header_callback != NULL) {
        result = client->config.header_callback(client->config.header_user, headers, header_capacity, &header_count);
        if (result != H2_FIXTURE_OK || header_count > header_capacity) { if (result == H2_FIXTURE_OK) result = H2_FIXTURE_ERR_INVALID_ARG; goto cleanup_headers; }
    }
    for (size_t i = 0u; i < header_count; ++i) { if (!h2_fixture_http_header_valid(&headers[i])) { result = H2_FIXTURE_ERR_INVALID_ARG; goto cleanup_headers; } }
    h2_pal_json_document_t *request_document = NULL;
    h2_pal_json_buffer_t request_body = {0};
    char *multipart_body = NULL;
    size_t multipart_body_len = 0u;
    if (true) {
        result = h2_fixture_from_pal(h2_pal_json_document_create(client->config.json, NULL, &request_document));
        if (result != H2_FIXTURE_OK) goto cleanup_headers;
        h2_pal_json_value_t *request_root = NULL;
        result = h2_fixture_pet_encode(client, request_document, request->body, &request_root);
        if (result != H2_FIXTURE_OK) goto cleanup_json;
        result = h2_fixture_from_pal(h2_pal_json_document_set_root(client->config.json, request_document, request_root));
        if (result != H2_FIXTURE_OK) goto cleanup_json;
        result = h2_fixture_from_pal(h2_pal_json_document_serialize(client->config.json, request_document, &request_body));
        if (result != H2_FIXTURE_OK || request_body.len > client->config.max_request_bytes) { if (result == H2_FIXTURE_OK) result = H2_FIXTURE_ERR_NO_SPACE; goto cleanup_json; }
    }
    uint8_t *response_buffer = h2_pal_mem_alloc(client->config.mem, client->config.max_response_bytes);
    if (response_buffer == NULL) { result = H2_FIXTURE_ERR_NO_MEMORY; goto cleanup_json; }
    h2_fixture_update_pet_response_header_context_t response_header_context = {client, response};
    h2_pal_http_request_t http_request = {
        .method = H2_PAL_HTTP_POST, .url = {url.data, url.len}, .headers = headers, .header_count = header_count,
        .body = multipart_body != NULL ? (const uint8_t *)multipart_body : request_body.data, .body_len = multipart_body != NULL ? multipart_body_len : request_body.len, .timeout_ms = client->config.timeout_ms,
        .response_buf = response_buffer, .response_buf_cap = client->config.max_response_bytes, .allocator = client->config.mem,
        .response_header_cb = h2_fixture_update_pet_response_header, .response_header_user = &response_header_context,
    };
    h2_pal_http_response_t http_response = {0};
    result = h2_fixture_from_http(h2_pal_http_request(client->config.http, &http_request, &http_response));
    if (result != H2_FIXTURE_OK) goto cleanup_http_response;
    response->status_code = http_response.status_code;
    result = (http_response.status_code >= 200 && http_response.status_code < 300) ? H2_FIXTURE_ERR_UNEXPECTED_STATUS : H2_FIXTURE_ERR_HTTP_STATUS;
    switch (http_response.status_code) {
    case 200:
    {
        h2_pal_json_document_t *response_document = NULL;
        response->has_body = true;
        result = h2_fixture_from_pal(h2_pal_json_document_parse(client->config.json, http_response.body, http_response.body_len, NULL, &response_document));
        h2_pal_json_value_t *response_root = NULL;
        if (result == H2_FIXTURE_OK) result = h2_fixture_from_pal(h2_pal_json_document_root(client->config.json, response_document, &response_root));
        if (result == H2_FIXTURE_OK) result = h2_fixture_pet_decode(client, response_root, &response->body.status_200);
        (void)h2_pal_json_document_destroy(client->config.json, &response_document);
        if (result == H2_FIXTURE_OK) result = H2_FIXTURE_OK;
        break;
    }
    case 400:
    {
        h2_pal_json_document_t *response_document = NULL;
        response->has_body = true;
        result = h2_fixture_from_pal(h2_pal_json_document_parse(client->config.json, http_response.body, http_response.body_len, NULL, &response_document));
        h2_pal_json_value_t *response_root = NULL;
        if (result == H2_FIXTURE_OK) result = h2_fixture_from_pal(h2_pal_json_document_root(client->config.json, response_document, &response_root));
        if (result == H2_FIXTURE_OK) result = h2_fixture_error_decode(client, response_root, &response->body.status_400);
        (void)h2_pal_json_document_destroy(client->config.json, &response_document);
        if (result == H2_FIXTURE_OK) result = H2_FIXTURE_ERR_HTTP_STATUS;
        break;
    }
    default:
        break;
    }
cleanup_http_response:
    h2_pal_http_response_free(client->config.http, &http_response);
    h2_pal_mem_free(client->config.mem, response_buffer);
cleanup_json:
    h2_pal_mem_free(client->config.mem, multipart_body);
    (void)h2_pal_json_buffer_release(client->config.json, &request_body);
    (void)h2_pal_json_document_destroy(client->config.json, &request_document);
cleanup_headers:
    h2_pal_mem_free(client->config.mem, authorization);
    h2_pal_mem_free(client->config.mem, headers);
cleanup_url:
    h2_pal_mem_free(client->config.mem, url_data);
    if (result != H2_FIXTURE_OK && result != H2_FIXTURE_ERR_HTTP_STATUS) {
        const int completed_status = response->status_code;
        h2_fixture_update_pet_response_deinit(response);
        response->status_code = completed_status;
        response->mem = client->config.mem;
    }
    return result;
}

void h2_fixture_upload_response_deinit(h2_fixture_upload_response_t *response) {
    if (response == NULL) return;
    memset(response, 0, sizeof(*response));
}

h2_fixture_result_t h2_fixture_upload(h2_fixture_client_t *client, const h2_fixture_upload_request_t *request, h2_fixture_upload_response_t *response) {
    if (client == NULL || request == NULL || response == NULL || !h2_fixture_config_valid(&client->config)) return H2_FIXTURE_ERR_INVALID_ARG;
    h2_fixture_upload_response_deinit(response);
    response->mem = client->config.mem;
    char multipart_boundary[48] = {0};
    size_t multipart_boundary_len = 0u;
    char multipart_content_type[80] = {0};
    size_t multipart_content_type_len = 0u;
    if (true && request->body == NULL) return H2_FIXTURE_ERR_INVALID_ARG;
    if (true) {
        uint64_t multipart_boundary_index = 0u;
        for (;;) {
            int boundary_len = snprintf(multipart_boundary, sizeof(multipart_boundary), "h2-openapi-boundary-%016llx", (unsigned long long)multipart_boundary_index);
            if (boundary_len < 0 || (size_t)boundary_len >= sizeof(multipart_boundary)) return H2_FIXTURE_ERR_NO_SPACE;
            multipart_boundary_len = (size_t)boundary_len;
            bool boundary_conflict = false;
            if (true && h2_fixture_bytes_contain(request->body->dir.data, request->body->dir.len, multipart_boundary, multipart_boundary_len)) boundary_conflict = true;
            if (true && h2_fixture_bytes_contain(request->body->file.data, request->body->file.len, multipart_boundary, multipart_boundary_len)) boundary_conflict = true;
            if (!boundary_conflict) break;
            ++multipart_boundary_index;
        }
        int content_type_len = snprintf(multipart_content_type, sizeof(multipart_content_type), "multipart/form-data; boundary=%s", multipart_boundary);
        if (content_type_len < 0 || (size_t)content_type_len >= sizeof(multipart_content_type)) return H2_FIXTURE_ERR_NO_SPACE;
        multipart_content_type_len = (size_t)content_type_len;
    }
    char *url_data = h2_pal_mem_alloc(client->config.mem, client->config.max_url_bytes + 1u);
    if (url_data == NULL) return H2_FIXTURE_ERR_NO_MEMORY;
    h2_fixture_buffer_t url = {url_data, 0u, client->config.max_url_bytes};
    h2_fixture_result_t result = h2_fixture_buffer_append(&url, client->config.base_url, strlen(client->config.base_url));
    if (result != H2_FIXTURE_OK) goto cleanup_url;
    result = h2_fixture_buffer_append(&url, "/upload", 7); if (result != H2_FIXTURE_OK) goto cleanup_url;
    if (client->config.max_extra_headers > SIZE_MAX - 1) { result = H2_FIXTURE_ERR_NO_SPACE; goto cleanup_url; }
    size_t header_capacity = 1 + client->config.max_extra_headers;
    if (header_capacity > SIZE_MAX / sizeof(h2_pal_http_header_t)) { result = H2_FIXTURE_ERR_NO_SPACE; goto cleanup_url; }
    h2_pal_http_header_t *headers = NULL;
    if (header_capacity != 0u) headers = h2_pal_mem_alloc(client->config.mem, sizeof(*headers) * header_capacity);
    if (header_capacity != 0u && headers == NULL) { result = H2_FIXTURE_ERR_NO_MEMORY; goto cleanup_url; }
    if (headers != NULL) memset(headers, 0, sizeof(*headers) * header_capacity);
    size_t header_count = 0u;
    char *authorization = NULL;
    if (true) headers[header_count++] = (h2_pal_http_header_t){{"Content-Type", 12u}, {multipart_content_type, multipart_content_type_len}};
    if (client->config.header_callback != NULL) {
        result = client->config.header_callback(client->config.header_user, headers, header_capacity, &header_count);
        if (result != H2_FIXTURE_OK || header_count > header_capacity) { if (result == H2_FIXTURE_OK) result = H2_FIXTURE_ERR_INVALID_ARG; goto cleanup_headers; }
    }
    for (size_t i = 0u; i < header_count; ++i) { if (!h2_fixture_http_header_valid(&headers[i])) { result = H2_FIXTURE_ERR_INVALID_ARG; goto cleanup_headers; } }
    h2_pal_json_document_t *request_document = NULL;
    h2_pal_json_buffer_t request_body = {0};
    char *multipart_body = NULL;
    size_t multipart_body_len = 0u;
    if (true) {
        if (client->config.max_request_bytes == SIZE_MAX) { result = H2_FIXTURE_ERR_NO_SPACE; goto cleanup_json; }
        multipart_body = h2_pal_mem_alloc(client->config.mem, client->config.max_request_bytes + 1u);
        if (multipart_body == NULL) { result = H2_FIXTURE_ERR_NO_MEMORY; goto cleanup_json; }
        h2_fixture_buffer_t multipart = {multipart_body, 0u, client->config.max_request_bytes};
        if (true) {
            result = h2_fixture_buffer_append(&multipart, "--", 2u); if (result != H2_FIXTURE_OK) goto cleanup_json;
            result = h2_fixture_buffer_append(&multipart, multipart_boundary, multipart_boundary_len); if (result != H2_FIXTURE_OK) goto cleanup_json;
            result = h2_fixture_buffer_append(&multipart, "\015\012Content-Disposition: form-data; name=\"dir\"\015\012\015\012", 48u); if (result != H2_FIXTURE_OK) goto cleanup_json;
            if (!h2_fixture_string_valid(request->body->dir, 0, client->config.max_string_bytes)) { result = H2_FIXTURE_ERR_INVALID_ARG; goto cleanup_json; }
            result = h2_fixture_buffer_append(&multipart, request->body->dir.data, request->body->dir.len); if (result != H2_FIXTURE_OK) goto cleanup_json;
            result = h2_fixture_buffer_append(&multipart, "\r\n", 2u); if (result != H2_FIXTURE_OK) goto cleanup_json;
        }
        if (true) {
            result = h2_fixture_buffer_append(&multipart, "--", 2u); if (result != H2_FIXTURE_OK) goto cleanup_json;
            result = h2_fixture_buffer_append(&multipart, multipart_boundary, multipart_boundary_len); if (result != H2_FIXTURE_OK) goto cleanup_json;
            result = h2_fixture_buffer_append(&multipart, "\015\012Content-Disposition: form-data; name=\"file\"; filename=\"blob\"\015\012Content-Type: application/octet-stream\015\012\015\012", 106u); if (result != H2_FIXTURE_OK) goto cleanup_json;
            if (request->body->file.data == NULL && request->body->file.len != 0u) { result = H2_FIXTURE_ERR_INVALID_ARG; goto cleanup_json; }
            result = h2_fixture_buffer_append(&multipart, (const char *)request->body->file.data, request->body->file.len); if (result != H2_FIXTURE_OK) goto cleanup_json;
            result = h2_fixture_buffer_append(&multipart, "\r\n", 2u); if (result != H2_FIXTURE_OK) goto cleanup_json;
        }
        result = h2_fixture_buffer_append(&multipart, "--", 2u); if (result != H2_FIXTURE_OK) goto cleanup_json;
        result = h2_fixture_buffer_append(&multipart, multipart_boundary, multipart_boundary_len); if (result != H2_FIXTURE_OK) goto cleanup_json;
        result = h2_fixture_buffer_append(&multipart, "--\r\n", 4u); if (result != H2_FIXTURE_OK) goto cleanup_json;
        multipart_body_len = multipart.len;
    }
    uint8_t *response_buffer = h2_pal_mem_alloc(client->config.mem, client->config.max_response_bytes);
    if (response_buffer == NULL) { result = H2_FIXTURE_ERR_NO_MEMORY; goto cleanup_json; }
    h2_pal_http_request_t http_request = {
        .method = H2_PAL_HTTP_POST, .url = {url.data, url.len}, .headers = headers, .header_count = header_count,
        .body = multipart_body != NULL ? (const uint8_t *)multipart_body : request_body.data, .body_len = multipart_body != NULL ? multipart_body_len : request_body.len, .timeout_ms = client->config.timeout_ms,
        .response_buf = response_buffer, .response_buf_cap = client->config.max_response_bytes, .allocator = client->config.mem,
    };
    h2_pal_http_response_t http_response = {0};
    result = h2_fixture_from_http(h2_pal_http_request(client->config.http, &http_request, &http_response));
    if (result != H2_FIXTURE_OK) goto cleanup_http_response;
    response->status_code = http_response.status_code;
    result = (http_response.status_code >= 200 && http_response.status_code < 300) ? H2_FIXTURE_ERR_UNEXPECTED_STATUS : H2_FIXTURE_ERR_HTTP_STATUS;
    switch (http_response.status_code) {
    case 204:
        result = H2_FIXTURE_OK;
        break;
    default:
        break;
    }
cleanup_http_response:
    h2_pal_http_response_free(client->config.http, &http_response);
    h2_pal_mem_free(client->config.mem, response_buffer);
cleanup_json:
    h2_pal_mem_free(client->config.mem, multipart_body);
    (void)h2_pal_json_buffer_release(client->config.json, &request_body);
    (void)h2_pal_json_document_destroy(client->config.json, &request_document);
cleanup_headers:
    h2_pal_mem_free(client->config.mem, authorization);
    h2_pal_mem_free(client->config.mem, headers);
cleanup_url:
    h2_pal_mem_free(client->config.mem, url_data);
    if (result != H2_FIXTURE_OK && result != H2_FIXTURE_ERR_HTTP_STATUS) {
        const int completed_status = response->status_code;
        h2_fixture_upload_response_deinit(response);
        response->status_code = completed_status;
        response->mem = client->config.mem;
    }
    return result;
}
