#ifndef BOARDS_AC695N_CHIP_AC695N_LAYOUTS_COMPILE_ONLY_INCLUDE_APP_CONFIG_H_
#define BOARDS_AC695N_CHIP_AC695N_LAYOUTS_COMPILE_ONLY_INCLUDE_APP_CONFIG_H_

#define ENABLE 1
#define DISABLE 0
#define NO_CONFIG_PORT (-1)

#define CONFIG_FLASH_SIZE (1024 * 1024)
#define CONFIG_DEBUG_ENABLE

#ifdef CONFIG_RELEASE_ENABLE
#define LIB_DEBUG 0
#else
#define LIB_DEBUG 1
#endif

#define CONFIG_DEBUG_LIB(value) ((value) & LIB_DEBUG)

#define AUDIO_OUTPUT_WAY_DAC 0
#define AUDIO_OUTPUT_WAY_FM 2
#define AUDIO_OUTPUT_WAY AUDIO_OUTPUT_WAY_DAC

#define TCFG_UART0_ENABLE ENABLE
#define TCFG_UART0_RX_PORT NO_CONFIG_PORT
#define TCFG_UART0_TX_PORT IO_PORTA_05
#define TCFG_UART0_BAUDRATE 1000000

#define TCFG_CLOCK_SYS_SRC SYS_CLOCK_INPUT_PLL_BT_OSC
#define TCFG_CLOCK_SYS_HZ 24000000
#define TCFG_CLOCK_OSC_HZ 24000000
#define TCFG_CLOCK_MODE CLOCK_MODE_ADAPTIVE

#define TCFG_LOWPOWER_POWER_SEL PWR_LDO15
#define TCFG_LOWPOWER_BTOSC_DISABLE 0
#define TCFG_LOWPOWER_LOWPOWER_SEL 0
#define TCFG_LOWPOWER_VDDIOM_LEVEL VDDIOM_VOL_34V
#define TCFG_LOWPOWER_VDDIOW_LEVEL VDDIOW_VOL_28V

#define TCFG_LED7_RUN_RAM 0
#define TCFG_CODE_RUN_RAM_FM_MODE 0
#define TCFG_FM_INSIDE_ENABLE 0
#define TCFG_USB_CDC_BACKGROUND_RUN 0
#define TCFG_VIR_UDISK_ENABLE 0
#define TCFG_KWS_VOICE_RECOGNITION_ENABLE 0
#define TCFG_USER_TWS_ENABLE 0
#define TCFG_NORFLASH_DEV_ENABLE 0

#endif
