// Based on the BK7258 widgets_v9 board GPIO map from Armino v3.1.1.
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#define GPIO_DEFAULT_DEV_CONFIG  \
{\
	{GPIO_0,  GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_UART1_TXD, GPIO_IO_DISABLE, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_1,  GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_UART1_RXD, GPIO_IO_DISABLE, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_2,  GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_SDIO_HOST_CLK, GPIO_IO_DISABLE, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_3,  GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_SDIO_HOST_CMD, GPIO_IO_DISABLE, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_4,  GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_SDIO_HOST_DATA0, GPIO_IO_DISABLE, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_6,  GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_I2S1_CLK, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_7,  GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_I2S1_SYNC, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_8,  GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_9,  GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_I2S1_DOUT, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_12, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_13, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_14, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_CLK, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_15, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_DISP, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_16, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_DE, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_17, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_HSYNC, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_18, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_VSYNC, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_19, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_R7, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_20, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_R6, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_21, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_R5, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_22, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_R4, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_23, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_R3, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_24, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_G7, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_25, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_G6, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_26, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_G5, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_27, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_JPEG_MCLK, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_28, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_ADC4, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_29, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_JPEG_PCLK, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_30, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_JPEG_HSYNC, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_31, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_JPEG_VSYNC, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_32, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_JPEG_PXDATA0, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_33, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_JPEG_PXDATA1, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_34, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_JPEG_PXDATA2, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_35, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_JPEG_PXDATA3, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_36, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_JPEG_PXDATA4, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_37, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_JPEG_PXDATA5, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_38, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_JPEG_PXDATA6, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_39, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_JPEG_PXDATA7, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_40, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_G4, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_41, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_G3, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_42, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_G2, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_43, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_B7, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_44, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_B6, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_45, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_B5, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_46, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_B4, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_47, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_B3, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_48, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_R2, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_49, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_R1, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_50, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_R0, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_51, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_G1, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_52, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_G0, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_53, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_B2, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_54, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_B1, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_55, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_B0, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
}

#ifdef __cplusplus
}
#endif

/* PWM1 drives the board LCD backlight on GPIO7. The SDK default GPIO19
 * belongs to LCD_R7 and must never be remapped by a brightness request. */
#define GPIO_PWM_MAP_TABLE { \
    {{GPIO_18, GPIO_DEV_PWM0}, {GPIO_7, GPIO_DEV_PWM1}, \
     {GPIO_8, GPIO_DEV_PWM2}, {GPIO_9, GPIO_DEV_PWM3}, \
     {GPIO_24, GPIO_DEV_PWM4}, {GPIO_25, GPIO_DEV_PWM5}}, \
    {{GPIO_32, GPIO_DEV_PWM6}, {GPIO_33, GPIO_DEV_PWM7}, \
     {GPIO_34, GPIO_DEV_PWM8}, {GPIO_35, GPIO_DEV_PWM9}, \
     {GPIO_36, GPIO_DEV_PWM10}, {GPIO_37, GPIO_DEV_PWM11}} \
}
