load("//tools/bazel:native_component.bzl", "firmware_native_component")

package(default_visibility = ["//visibility:public"])

firmware_native_component(
    name = "h2_esp_audio_decoder",
    srcs = glob(
        [
            "**/*.c",
            "**/*.cc",
            "**/*.cpp",
            "**/*.cxx",
            "**/*.s",
            "**/*.S",
        ],
        allow_empty = True,
        exclude = [
            "examples/**",
            "test/**",
            "tests/**",
        ],
    ),
    hdrs = glob(
        [
            "**/*.h",
            "**/*.hh",
            "**/*.hpp",
            "**/*.hxx",
        ],
        allow_empty = True,
        exclude = [
            "examples/**",
            "test/**",
            "tests/**",
        ],
    ),
    data = [
        "CMakeLists.txt",
        "idf_component.yml",
    ],
    tags = [
        "manual",
    ],
    deps = [
        "//native_component_src/esp-idf6.x/h2_pal_core",
    ],
)
