load("@rules_cc//cc:defs.bzl", "cc_test")
load("//tools/bazel:cc_options.bzl", "H2_C11_OPTS", "H2_WARNING_COPTS")

package(default_visibility = ["//visibility:public"])

cc_test(
    name = "atomic_e2e_test",
    srcs = ["test_atomic_e2e.c"],
    conlyopts = H2_C11_OPTS,
    copts = H2_WARNING_COPTS,
    deps = [
        "//libs/atomic/providers/c11",
        "//libs/pal/providers/desktop/pal_core",
        "//projects/e2e/apps/atomic/app:atomic_e2e",
        "//projects/e2e/apps/atomic/app:c11_comparison",
    ],
)
