/* Public PSA entry points used by PAL and the SDK TLS/DTLS stack.
 * Included with H2_BK_PSA_CALL defined; signatures inherit SDK psa/crypto.h. */
H2_BK_PSA_CALL(psa_crypto_init, (void), ())
H2_BK_PSA_CALL(psa_destroy_key, (mbedtls_svc_key_id_t key), (key))
H2_BK_PSA_CALL(psa_import_key, (const psa_key_attributes_t *attributes, const uint8_t *data, size_t data_length, mbedtls_svc_key_id_t *key), (attributes, data, data_length, key))
H2_BK_PSA_CALL(psa_export_key, (mbedtls_svc_key_id_t key, uint8_t *data, size_t data_size, size_t *data_length), (key, data, data_size, data_length))
H2_BK_PSA_CALL(psa_export_public_key, (mbedtls_svc_key_id_t key, uint8_t *data, size_t data_size, size_t *data_length), (key, data, data_size, data_length))
H2_BK_PSA_CALL(psa_hash_compute, (psa_algorithm_t alg, const uint8_t *input, size_t input_length, uint8_t *hash, size_t hash_size, size_t *hash_length), (alg, input, input_length, hash, hash_size, hash_length))
H2_BK_PSA_CALL(psa_hash_setup, (psa_hash_operation_t *operation, psa_algorithm_t alg), (operation, alg))
H2_BK_PSA_CALL(psa_hash_update, (psa_hash_operation_t *operation, const uint8_t *input, size_t input_length), (operation, input, input_length))
H2_BK_PSA_CALL(psa_hash_finish, (psa_hash_operation_t *operation, uint8_t *hash, size_t hash_size, size_t *hash_length), (operation, hash, hash_size, hash_length))
H2_BK_PSA_CALL(psa_hash_abort, (psa_hash_operation_t *operation), (operation))
H2_BK_PSA_CALL(psa_mac_compute, (mbedtls_svc_key_id_t key, psa_algorithm_t alg, const uint8_t *input, size_t input_length, uint8_t *mac, size_t mac_size, size_t *mac_length), (key, alg, input, input_length, mac, mac_size, mac_length))
H2_BK_PSA_CALL(psa_mac_update, (psa_mac_operation_t *operation, const uint8_t *input, size_t input_length), (operation, input, input_length))
H2_BK_PSA_CALL(psa_mac_sign_finish, (psa_mac_operation_t *operation, uint8_t *mac, size_t mac_size, size_t *mac_length), (operation, mac, mac_size, mac_length))
H2_BK_PSA_CALL(psa_mac_abort, (psa_mac_operation_t *operation), (operation))
H2_BK_PSA_CALL(psa_cipher_encrypt_setup, (psa_cipher_operation_t *operation, mbedtls_svc_key_id_t key, psa_algorithm_t alg), (operation, key, alg))
H2_BK_PSA_CALL(psa_cipher_set_iv, (psa_cipher_operation_t *operation, const uint8_t *iv, size_t iv_length), (operation, iv, iv_length))
H2_BK_PSA_CALL(psa_cipher_update, (psa_cipher_operation_t *operation, const uint8_t *input, size_t input_length, uint8_t *output, size_t output_size, size_t *output_length), (operation, input, input_length, output, output_size, output_length))
H2_BK_PSA_CALL(psa_cipher_finish, (psa_cipher_operation_t *operation, uint8_t *output, size_t output_size, size_t *output_length), (operation, output, output_size, output_length))
H2_BK_PSA_CALL(psa_cipher_abort, (psa_cipher_operation_t *operation), (operation))
H2_BK_PSA_CALL(psa_aead_encrypt, (mbedtls_svc_key_id_t key, psa_algorithm_t alg, const uint8_t *nonce, size_t nonce_length, const uint8_t *additional_data, size_t additional_data_length, const uint8_t *plaintext, size_t plaintext_length, uint8_t *ciphertext, size_t ciphertext_size, size_t *ciphertext_length), (key, alg, nonce, nonce_length, additional_data, additional_data_length, plaintext, plaintext_length, ciphertext, ciphertext_size, ciphertext_length))
H2_BK_PSA_CALL(psa_aead_decrypt, (mbedtls_svc_key_id_t key, psa_algorithm_t alg, const uint8_t *nonce, size_t nonce_length, const uint8_t *additional_data, size_t additional_data_length, const uint8_t *ciphertext, size_t ciphertext_length, uint8_t *plaintext, size_t plaintext_size, size_t *plaintext_length), (key, alg, nonce, nonce_length, additional_data, additional_data_length, ciphertext, ciphertext_length, plaintext, plaintext_size, plaintext_length))
H2_BK_PSA_CALL(psa_sign_message, (mbedtls_svc_key_id_t key, psa_algorithm_t alg, const uint8_t *input, size_t input_length, uint8_t *signature, size_t signature_size, size_t *signature_length), (key, alg, input, input_length, signature, signature_size, signature_length))
H2_BK_PSA_CALL(psa_verify_message, (mbedtls_svc_key_id_t key, psa_algorithm_t alg, const uint8_t *input, size_t input_length, const uint8_t *signature, size_t signature_length), (key, alg, input, input_length, signature, signature_length))
H2_BK_PSA_CALL(psa_key_derivation_setup, (psa_key_derivation_operation_t *operation, psa_algorithm_t alg), (operation, alg))
H2_BK_PSA_CALL(psa_key_derivation_input_bytes, (psa_key_derivation_operation_t *operation, psa_key_derivation_step_t step, const uint8_t *data, size_t data_length), (operation, step, data, data_length))
H2_BK_PSA_CALL(psa_key_derivation_output_bytes, (psa_key_derivation_operation_t *operation, uint8_t *output, size_t output_length), (operation, output, output_length))
H2_BK_PSA_CALL(psa_key_derivation_abort, (psa_key_derivation_operation_t *operation), (operation))
H2_BK_PSA_CALL(psa_raw_key_agreement, (psa_algorithm_t alg, mbedtls_svc_key_id_t private_key, const uint8_t *peer_key, size_t peer_key_length, uint8_t *output, size_t output_size, size_t *output_length), (alg, private_key, peer_key, peer_key_length, output, output_size, output_length))
H2_BK_PSA_CALL(psa_generate_random, (uint8_t *output, size_t output_size), (output, output_size))
H2_BK_PSA_CALL(psa_generate_key, (const psa_key_attributes_t *attributes, mbedtls_svc_key_id_t *key), (attributes, key))
