#ifndef H2_ESP_BOARD_CONFIG_H
#define H2_ESP_BOARD_CONFIG_H

#define H2_ESP_BOARD_NAME "amoled"
#define H2_ESP_BOARD_FS_BASE_PATH "/h2fs"
#define H2_ESP_BOARD_FS_PARTITION_LABEL "h2test"

#define H2_AMOLED_BOOT_BUTTON_ID 101u
#define H2_AMOLED_POWER_BUTTON_ID 102u
#define H2_AMOLED_QMI8658_MOTION_ID 301u

#endif
