load("//tools/bazel:native_component.bzl", "firmware_native_component")

package(default_visibility = ["//visibility:public"])

firmware_native_component(
    name = "ac791n",
    srcs = ["src/h2_ac791n_chip_board.c"],
    component_name = "h2_ac791n_chip_board",
    tags = ["manual"],
    target_compatible_with = select({
        "//tools/bazel/platforms:ci_graph": [],
        "//tools/bazel/platforms:is_ac791n": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
)
