export const apiSources = [
  { id: "app_test", roots: ["libs/app_test/include"] },
  { id: "audio_mixer", roots: ["libs/audio_mixer/include"] },
  { id: "bleikcp", roots: ["libs/bleikcp/include"] },
  { id: "bundle", roots: ["libs/bundle/include"] },
  { id: "command", roots: ["libs/command/include"] },
  { id: "corehttp", roots: ["libs/pal/providers/corehttp/include"] },
  { id: "coremqtt", roots: ["libs/pal/providers/coremqtt/include"] },
  { id: "dns", roots: ["libs/dns/include"] },
  { id: "ffmpeg", roots: ["libs/pal/providers/ffmpeg/include"] },
  {
    id: "drivers",
    roots: [
      "libs/pal/providers/modem/quectel/include",
      "libs/drivers/motion/qmi8658/include",
      "libs/drivers/nfc/fm175xx/include",
    ],
  },
  { id: "game_runtime", roots: ["libs/game_runtime/include"] },
  { id: "gizclaw", roots: ["libs/gizclaw/include"] },
  { id: "h2loader", roots: ["projects/h2loader/libs/h2loader/include"] },
  { id: "h2peer", roots: ["libs/pal/providers/h2peer/include"] },
  { id: "h2sctp", roots: ["libs/pal/providers/h2sctp/include"] },
  { id: "iostreamikcp", roots: ["libs/iostreamikcp/include"] },
  { id: "libco", roots: ["libs/pal/providers/libco/include"] },
  { id: "lvgl", roots: ["libs/lvgl/include"] },
  { id: "mp4_decoder", roots: ["libs/mp4_decoder/include"] },
  { id: "ntp", roots: ["libs/ntp/include"] },
  { id: "pal", roots: ["libs/pal/include"] },
  { id: "pixa", roots: ["libs/pixa/include"] },
  { id: "portaudio", roots: ["libs/pal/providers/portaudio/include"] },
  { id: "runtime", roots: ["libs/runtime/include"] },
  { id: "sdl3", roots: ["libs/pal/providers/sdl3/include"] },
  { id: "sqlite", roots: ["libs/pal/providers/sqlite/include"] },
  { id: "tinyh264", roots: ["libs/pal/providers/tinyh264/include"] },
  { id: "utils", roots: ["libs/utils/include"] },
  { id: "wolfssl", roots: ["libs/pal/providers/wolfssl/include"] },
];
