#ifndef LV_CONF_H
#define LV_CONF_H

#define LV_COLOR_DEPTH 16
#define LV_USE_OS LV_OS_NONE

#define LV_DEF_REFR_PERIOD 16
#define LV_DPI_DEF 160

#define LV_USE_STDLIB_MALLOC LV_STDLIB_CLIB
#define LV_USE_STDLIB_STRING LV_STDLIB_CLIB
#define LV_USE_STDLIB_SPRINTF LV_STDLIB_CLIB

#define LV_DRAW_SW_DRAW_UNIT_CNT 1
#define LV_USE_DRAW_SW 1

#define LV_USE_LOG 1
#define LV_LOG_LEVEL LV_LOG_LEVEL_WARN

#define LV_USE_OBSERVER 1
#define LV_USE_TRANSLATION 0
#define LV_USE_OBJ_NAME 1
#define LV_USE_TINY_TTF 0
#define LV_FONT_MONTSERRAT_20 1
#define LV_FONT_MONTSERRAT_42 1

#define LV_USE_SYSMON 0
#define LV_USE_PERF_MONITOR 0
#define LV_USE_MEM_MONITOR 0

#endif
