#!/usr/bin/env python3
"""Master selected battle voice clips and embed animation-aligned PCM; stdlib only."""
import math
import struct
import wave
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RATE = 16000
# Excerpts include about 30 ms of natural attack. Align the audible onset with
# ACTIONS windup in main.lua. Charge starts during the gathering motion.
LEAD_MS = {"charge": 0, "wave": 450, "absorb": 330, "guard": 200, "hurt": 720}


def master(kind):
    with wave.open(str(ROOT / 'assets/source/voices' / (kind + '.wav')), 'rb') as src:
        assert (src.getnchannels(), src.getsampwidth(), src.getframerate()) == (1, 2, RATE)
        data = src.readframes(src.getnframes())
    values = struct.unpack('<' + 'h' * (len(data)//2), data)
    samples, previous, filtered = [], 0., 0.
    alpha = math.exp(-math.tau * 90 / RATE)
    for i, value in enumerate(values):
        # Remove handling rumble while retaining the real voice and breath.
        filtered = alpha * (filtered + value - previous)
        previous = value
        fade = min(1, i/(RATE*.012), (len(values)-1-i)/(RATE*.055))
        samples.append(filtered * fade)
    peak = max(abs(v) for v in samples)
    assert peak > 0
    pcm = [round(v/peak * 23170) for v in samples]
    return struct.pack('<' + 'h'*len(pcm), *pcm)


def main():
    target = ROOT / 'assets/generated/sounds'
    target.mkdir(parents=True, exist_ok=True)
    lua = ['-- Battle voice clips; see assets/source/voices/CREDITS.md for provenance.',
           '-- Generated by app/tools/generate_sounds.py; mono S16LE / 16000 Hz.',
           '-- Includes leading silence to align vocals with skill windup.', 'return {']
    previews = []
    for kind, lead in LEAD_MS.items():
        dry = master(kind)
        previews.append(dry)
        with wave.open(str(target / (kind + '.wav')), 'wb') as out:
            out.setparams((1, 2, RATE, 0, 'NONE', 'not compressed'))
            out.writeframes(dry)
        pcm = bytes(lead*32) + dry
        lua.append('  ' + kind + ' =')
        for pos in range(0, len(pcm), 512):
            chunk = ''.join('\\%03d' % b for b in pcm[pos:pos+512])
            lua.append('    "' + chunk + '"' + (' ..' if pos+512 < len(pcm) else ','))
        print(f'{kind}: voice={len(dry)/32000:.2f}s, lead={lead}ms, end={len(pcm)/32000:.2f}s')
    lua.append('}')
    (target / 'sounds_pcm.lua').write_text('\n'.join(lua)+'\n')
    # Audition sequence only; not loaded by the game or padded with windup.
    with wave.open(str(target / 'dragonball-preview.wav'), 'wb') as out:
        out.setparams((1, 2, RATE, 0, 'NONE', 'not compressed'))
        out.writeframes(bytes(9600).join(previews))


if __name__ == '__main__':
    main()
