#ifndef BOARDS_AC791N_CHIP_AC791N_LAYOUTS_COMPILE_ONLY_INCLUDE_APP_CONFIG_H_
#define BOARDS_AC791N_CHIP_AC791N_LAYOUTS_COMPILE_ONLY_INCLUDE_APP_CONFIG_H_

#define __FLASH_SIZE__ (4 * 1024 * 1024)
#define __SDRAM_SIZE__ (2 * 1024 * 1024)

#define TCFG_LOWPOWER_BTOSC_DISABLE 0
#define TCFG_LOWPOWER_LOWPOWER_SEL 0
#define TCFG_LOWPOWER_VDDIOM_LEVEL VDDIOM_VOL_32V

#ifdef CONFIG_RTC_ENABLE
#define TCFG_LOWPOWER_VDDIOW_LEVEL VDDIOW_VOL_32V
#else
#define TCFG_LOWPOWER_VDDIOW_LEVEL VDDIOW_VOL_21V
#endif

#define VDC14_VOL_SEL_LEVEL VDC14_VOL_SEL_140V
#define SYSVDD_VOL_SEL_LEVEL SYSVDD_VOL_SEL_126V

#define CONFIG_CXX_SUPPORT
#define CONFIG_DEBUG_ENABLE

#if !defined(CONFIG_DEBUG_ENABLE) || defined(CONFIG_LIB_DEBUG_DISABLE)
#define LIB_DEBUG 0
#else
#define LIB_DEBUG 1
#endif

#define CONFIG_DEBUG_LIB(value) ((value) & LIB_DEBUG)

#endif
