load("@lvgl_font_conv_npm//:defs.bzl", "npm_link_all_packages")
load("@lvgl_font_conv_npm//tools/lvgl/font_conv:lv_font_conv/package_json.bzl", lv_font_conv_bin = "bin")
load("@rules_python//python:defs.bzl", "py_binary", "py_test")
load("//tools/bazel/platforms:compatibility.bzl", "HOST_TOOL_COMPATIBILITY")

package(default_visibility = ["//visibility:public"])

npm_link_all_packages(name = "node_modules")

filegroup(
    name = "metadata",
    srcs = [
        "package.json",
        "package-lock.json",
        "pnpm-lock.yaml",
    ],
)

lv_font_conv_bin.lv_font_conv_binary(
    name = "lv_font_conv",
    target_compatible_with = HOST_TOOL_COMPATIBILITY,
)

py_binary(
    name = "font_conv_runner",
    srcs = ["font_conv_runner.py"],
    legacy_create_init = 0,
    python_version = "PY3",
    target_compatible_with = HOST_TOOL_COMPATIBILITY,
)

py_binary(
    name = "fake_font_conv",
    srcs = ["tests/fake_font_conv.py"],
    legacy_create_init = 0,
    python_version = "PY3",
    target_compatible_with = HOST_TOOL_COMPATIBILITY,
)

py_test(
    name = "font_conv_runner_test",
    srcs = [
        "font_conv_runner.py",
        "tests/test_font_conv_runner.py",
    ],
    data = [":fake_font_conv"],
    imports = ["."],
    legacy_create_init = 0,
    main = "tests/test_font_conv_runner.py",
    python_version = "PY3",
    target_compatible_with = HOST_TOOL_COMPATIBILITY,
    deps = ["@rules_python//python/runfiles"],
)

exports_files(["font_conv.bzl"])
