load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "atomic",
    hdrs = ["include/h2_atomic.h"],
    includes = ["include"],
)

cc_library(
    name = "locked_template",
    hdrs = ["providers/locked/h2_atomic_locked_impl.h"],
    includes = ["providers/locked"],
    deps = [":atomic"],
)
