package(default_visibility = ["//visibility:public"])

filegroup(
    name = "jieli_ac791n_devkit",
    srcs = glob(
        ["**"],
        allow_empty = True,
        exclude = ["BUILD.bazel"],
    ) + ["//boards/jieli_ac791n_devkit/ac791n"],
    target_compatible_with = select({
        "//tools/bazel/platforms:ci_graph": [],
        "//tools/bazel/platforms:is_ac791n": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
)
