#ifndef CORE_MQTT_CONFIG_H
#define CORE_MQTT_CONFIG_H

#define MQTT_SUB_UNSUB_MAX_VECTORS 8U
#define MQTT_RECV_POLLING_TIMEOUT_MS 10U
#define MQTT_SEND_TIMEOUT_MS 10U
#define MQTT_PINGRESP_TIMEOUT_MS 1000U
#define MQTT_MAX_CONNACK_RECEIVE_RETRY_COUNT 10U

#endif
