load("@rules_cc//cc:defs.bzl", "cc_binary")
load("//tools/bazel:cc_options.bzl", "H2_C11_OPTS", "H2_WARNING_COPTS")

load("//tools/bazel/platforms:compatibility.bzl", "LINUX_ARMV7_GNUEABIHF_ARTIFACT_COMPATIBILITY")

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "mp4_player",
    srcs = ["main/main.c"],
    conlyopts = H2_C11_OPTS,
    copts = H2_WARNING_COPTS,
    data = [
        "package/mp4-player.service",
        "//projects/example/apps/mp4-player:large_media",
        "@h2_k4b_cedarx_sdk//:runtime_libraries",
    ],
    tags = ["manual"],
    target_compatible_with = LINUX_ARMV7_GNUEABIHF_ARTIFACT_COMPATIBILITY,
    deps = [
        "//boards/kickpi_k4b/t113-s3:t113_s3",
        "//libs/pal/providers/allwinner-linux/cedarx_video_decoder",
        "//libs/pal/providers/linux/alsa_audio",
        "//libs/pal/providers/linux/fdk_aac_decoder",
        "//projects/example/apps/mp4-player/app:mp4_player",
    ],
)
