"""Run one embedded Lua script as an app_host Web App."""

load("@bazel_skylib//rules:write_file.bzl", "write_file")
load("@rules_cc//cc:defs.bzl", "cc_library")
load("//libs/lua:lua_resource.bzl", "h2_lua_resource")
load("//libs/pal/providers/web/app_host:web_app.bzl", "h2_web_app")

_NAME_CHARS = "abcdefghijklmnopqrstuvwxyz0123456789_"
_MAX_BUTTONS = 8  # H2_WEB_APP_HOST_MAX_BUTTONS

def lua_web_app_argument_error(buttons, exit_button):
    """Returns why h2_lua_web_app() arguments are invalid, or "" when valid."""
    if not buttons or len(buttons) > _MAX_BUTTONS:
        return "buttons needs 1..%d entries" % _MAX_BUTTONS
    for button in buttons.keys():
        if not button or [c for c in button.elems() if c not in _NAME_CHARS]:
            return "Button name %r must use [a-z0-9_]" % button
    if exit_button != None and exit_button not in buttons:
        return "exit_button %r is not in buttons" % exit_button
    return ""

def _c_string(value):
    return '"%s"' % value.replace("\\", "\\\\").replace('"', '\\"')

def h2_lua_web_app(
        name,
        script,
        buttons,
        exit_button = None,
        extension = None,
        display_width = 240,
        display_height = 240,
        run_ms = 0,
        **kwargs):
    """Declares `<name>` (web tar), `serve` and `browser_test` for one script.

    The script is embedded with h2_lua_resource() and run by a generic App
    entry on app_host: every Button reaches the script as `args.<name>` (its
    Runtime component id, 1..N in `buttons` order) and its Runtime events are
    dispatched to the job. The exit Button ends the job instead; so does the
    page's Stop button. Use one h2_lua_web_app per package.

    Args:
      name: Archive target name; also the `H2_WEB_APP name=` marker.
      script: Label of the `.lua` source.
      buttons: Ordered dict of Button name ([a-z0-9_]) to the DOM
        `KeyboardEvent.key` that drives it, at most 8.
      exit_button: Optional Button name that cancels the job.
      extension: Optional cc_library defining `h2_web_lua_app_extension`
        (//libs/lua/web:lua_app_extension) to register
        modules or capabilities and to decide when the exit Button ends the job.
      display_width: Canvas width in pixels.
      display_height: Canvas height in pixels.
      run_ms: Nonzero stops the App after this long exactly as the page Stop
        button does (for tests).
      **kwargs: Passed to h2_web_app() (passes, fails, presses, taps,
        canvas_min, test_timeout_s, ...).
    """
    error = lua_web_app_argument_error(buttons, exit_button)
    if error:
        fail("h2_lua_web_app: " + error)
    names = list(buttons.keys())
    symbol = name.replace("-", "_") + "_script"

    h2_lua_resource(
        name = name + "_script",
        src = script,
        symbol = symbol,
    )

    write_file(
        name = name + "_config_header",
        out = name + "_config/h2_web_lua_app_config.h",
        content = [
            "#ifndef H2_WEB_LUA_APP_CONFIG_H",
            "#define H2_WEB_LUA_APP_CONFIG_H",
            "/* Generated by h2_lua_web_app(%s). */" % name,
            '#include "%s_script_generated.h"' % name,
            "#define H2_WEB_LUA_APP_NAME %s" % _c_string(name),
            "#define H2_WEB_LUA_APP_SOURCE %s" % symbol,
            "#define H2_WEB_LUA_APP_SOURCE_SIZE %s_size" % symbol,
            "#define H2_WEB_LUA_APP_BUTTONS(X)%s" % "".join([
                " X(%s, %s)" % (_c_string(button), _c_string(buttons[button]))
                for button in names
            ]),
            "#define H2_WEB_LUA_APP_EXIT_BUTTON %du" % (
                names.index(exit_button) + 1 if exit_button != None else 0
            ),
            "#define H2_WEB_LUA_APP_EXTENSION %d" % (1 if extension else 0),
            "#define H2_WEB_LUA_APP_DISPLAY_WIDTH %d" % display_width,
            "#define H2_WEB_LUA_APP_DISPLAY_HEIGHT %d" % display_height,
            "#define H2_WEB_LUA_APP_RUN_MS %du" % run_ms,
            "#endif",
            "",
        ],
    )

    cc_library(
        name = name + "_config",
        hdrs = [name + "_config/h2_web_lua_app_config.h"],
        strip_include_prefix = name + "_config",
        deps = [":" + name + "_script"],
    )

    linkopts = kwargs.pop("linkopts", [])
    h2_web_app(
        name = name,
        srcs = [Label("//libs/lua/web:src/h2_web_lua_app.c")],
        app_name = name,
        linkopts = ["-sASYNCIFY_REMOVE=['lua*','yyjson*']"] + linkopts,
        deps = [
            ":" + name + "_config",
            Label("//libs/lua"),
            Label("//libs/lua/web:lua_app_extension"),
        ] + ([extension] if extension else []),
        **kwargs
    )
