load("//tools/bazel:native_component.bzl", "firmware_native_component")

package(default_visibility = ["//visibility:public"])

firmware_native_component(
    name = "h2loader_bk",
    srcs = glob(
        [
            "**/*.c",
            "**/*.cc",
            "**/*.cpp",
            "**/*.cxx",
            "**/*.s",
            "**/*.S",
        ],
        allow_empty = True,
        exclude = [
            "examples/**",
            "test/**",
            "tests/**",
        ],
    ),
    hdrs = glob(
        [
            "**/*.h",
            "**/*.hh",
            "**/*.hpp",
            "**/*.hxx",
        ],
        allow_empty = True,
        exclude = [
            "examples/**",
            "test/**",
            "tests/**",
        ],
    ),
    data = [
        "CMakeLists.txt",
    ],
    execution_unit = "ap",
    native_srcs = [
        "//projects/h2loader/libs/h2loader:src/h2_loader_app_client.c",
        "//projects/h2loader/libs/h2loader:src/h2_loader_ble.c",
        "//projects/h2loader/libs/h2loader:src/h2_loader_boot.c",
        "//projects/h2loader/libs/h2loader:src/h2_loader_status.c",
    ],
    tags = [
        "manual",
    ],
    deps = [
        "//libs/bundle",
        "//libs/command",
        "//libs/iostreamikcp",
        "//libs/pal:unsupported",
        "//libs/trie:bk7258_ap_native_component",
        "//projects/h2loader/libs/h2loader",
    ],
)
