load("@rules_cc//cc:defs.bzl", "cc_binary")
load("//tools/bazel:cc_options.bzl", "H2_CXX17_OPTS", "H2_WARNING_COPTS")

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "e2e-h2loader-serial",
    srcs = ["main.cpp"],
    copts = H2_WARNING_COPTS,
    cxxopts = H2_CXX17_OPTS,
    deps = [
        "//libs/pal/providers/desktop/app_support",
        "//libs/pal/providers/desktop/pal_core",
        "//libs/runtime",
        "//projects/e2e/apps/h2loader-serial/app:h2loader_serial_e2e",
    ],
)
